<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<link rel="stylesheet" type="text/css" href="bc.css">
</head>

<h3>Revit 2015 API News &ndash; DevDays Online Recording</h3>

<p>As

<a href="http://www.jabberwocky.com/carroll/walrus.html">
the Walrus said</a>,

now "the time has come ... to talk of many things", including the highlights of the new Revit API functionality, so here we go!</p>

<p>Welcome to my first post on the Revit 2015 API, disregarding the

<a href="http://thebuildingcoder.typepad.com/blog/2014/04/revitlookup-for-revit-2015.html">
RevitLookup migration to Revit 2015</a>,

of course.</p>

<p>A couple of posts on upcoming Revit 2015 product functionality were already published in the past week or so, e.g.:</p>

<ul>
<li><a href="http://synergiscadblog.com/2014/04/02/whats-new-in-autodesk-revit-2015">Overview of new features by synergiscad</a></li>
<li><a href="http://revitking.blogspot.ch/2014/03/new-feature-list-for-revit-2015.html">Feature list by Revit.King</a></li>
<li><a href="http://www.seandburke.com/blog/2014/03/27/whats-new-in-revit-2015/">Highlighted features and enhancements by Paradigm shift</a></li>
<li><a href="http://www.cadlinecommunity.co.uk/Blogs/Blog.aspx?ScoId=cf9f3cac-1748-4f84-a025-07968741c658&returnTo=%2fBlogs%2finsider%2fDefault.aspx&returnTitle=Insider%20Blog">Screen snapshots by cadline</a></li>
<li><a href="http://bimopedia.com/2014/03/27/videos-whats-new-in-revit-2015">Videos by BIMopedia</a></li>
</ul>

<p>I will therefore skip all product related stuff and dive straight into the API instead.</p>

<p>Here is the Revit 2015 DevDays Online recording material, based on the presentations shown at the confidential Autodesk DevDays conferences in and around December 2013.</p>

<ul>

<li>Presentation
<a href="http://thebuildingcoder.typepad.com/devday/2013/online/Revit_2015_API_News/Revit_2015_API_News_Slides.pdf">slide deck</a> (23 MB) &nbsp;
<a href="file:////a/devdays/2013/online/Revit_2015_API_News_Slides.pdf">^</a>
</li>

<li>Presentation
<a href="http://thebuildingcoder.typepad.com/devday/2013/online/Revit_2015_API_News/index.html">recording</a> with table of contents navigation (354 MB) &nbsp;
<a href="file:////a/devdays/2013/online/cam/Revit_2015_API_News/index.html">^</a>
</li>

<li>Presentation
<a href="http://thebuildingcoder.typepad.com/devday/2013/online/Revit_2015_API_News/Revit_2015_API_News_Notes.pdf">notes</a> (198 KB) &nbsp;
<a href="file:////a/devdays/2013/online/Revit_2015_API_News_Notes.pdf">^</a>
</li>

<li>
<a href="http://thebuildingcoder.typepad.com/devday/2013/online/Revit_2015_API_News/Revit_2015_API_Samples.zip">Sample code incl. RVT models</a> (45 MB) &nbsp;
<a href="file:////a/devdays/2013/online/Revit_2015_API_Samples.zip">^</a>
</li>

<li>
<a href="http://thebuildingcoder.typepad.com/devday/2013/online/Revit_2015_API_News/Revit_2015_API_Samples_No_RVT.zip">Sample code excl. RVT models</a> (1.5 MB) &nbsp;
<a href="file:////a/devdays/2013/online/Revit_2015_API_Samples_No_RVT.zip">^</a>
</li>
</ul>

<p>The next thing I want to do is to publish the "What's New" section from the updated Revit API help file RevitAPI.chm, to ensure it is available for and easily found by online searches, as for the past few releases:

<ul>
<li><a href="http://thebuildingcoder.typepad.com/blog/2013/02/whats-new-in-the-revit-2010-api.html">What's New in the Revit 2010 API</a></li>
<li><a href="http://thebuildingcoder.typepad.com/blog/2013/02/whats-new-in-the-revit-2011-api.html">What's New in the Revit 2011 API</a></li>
<li><a href="http://thebuildingcoder.typepad.com/blog/2013/02/whats-new-in-the-revit-2012-api.html">What's New in the Revit 2012 API</a></li>
<li><a href="http://thebuildingcoder.typepad.com/blog/2013/03/whats-new-in-the-revit-2013-api.html">What's New in the Revit 2013 API</a></li>
<li><a href="http://thebuildingcoder.typepad.com/blog/2013/04/whats-new-in-the-revit-2014-api.html">What's New in the Revit 2014 API</a></li>
</ul>

<p>That is always the first place to explore if you have any questions about or problems with your migration or the new functionality provided.</p>

<p>I wish you lots of fun and excitement exploring the new possibilities provided by the Revit 2015 API!</p>

<!--

March 27, 2014.

http://www.seandburke.com/blog/2014/03/27/whats-new-in-revit-2015/

What’s new in Revit 2015

Date: 27 March 2014

http://www.cadlinecommunity.co.uk/Blogs/Blog.aspx?ScoId=cf9f3cac-1748-4f84-a025-07968741c658&returnTo=%2fBlogs%2finsider%2fDefault.aspx&returnTitle=Insider%20Blog

What's New in Revit 2015

March 27, 2014

http://revitking.blogspot.ch/2014/03/new-feature-list-for-revit-2015.html

New Feature List for Revit 2015
Revit.King's BIM coordinator/ Revit Blog

March 27, 2014
http://bimopedia.com/2014/03/27/videos-whats-new-in-revit-2015/
Videos – What’s New in Revit 2015

synergiscad on April 2, 2014
http://synergiscadblog.com/2014/04/02/whats-new-in-autodesk-revit-2015/
What’s New in Autodesk Revit 2015?

-->


<!--

09349837 [GUI design for Revit]

Ryan CameronSinclair Hille Architects

http://forums.autodesk.com/t5/Revit-API/GUI-design-for-Revit/m-p/4884362

-->

<a name="2"></a>

<h4>Right Click Circle of Commands GUI Design for Revit</h4>

<p>Sticking with what we already have for the moment, another interesting this that just came up on the Revit API forum is this discussion thread initiated by Ryan on

<a href="http://forums.autodesk.com/t5/Revit-API/GUI-design-for-Revit/m-p/4944720">
GUI design for Revit</a>.

<p>Ryan suggests developing a secondary user-infterface for Revit, like the right-click command in Fusion 360, or Inventor, a wheel (or circle) showing a pre-determined list of commands.</p>

<p>The Revit user interface could look something like this:</p>

<center>
<img src="img/rb_revit_user_interface.jpg" alt="Revit user interface" width="400"/>
</center>

<p>Commands placed on circle segments:</p>

<center>
<img src="img/rb_project_circle_screenshot_in_use.jpg" alt="Commands placed on circle segments" width="400"/>
</center>

<p>Interactive command population:</p>

<center>
<img src="img/rb_img_20131031_091527.jpg" alt="Interactive command population" width="400"/>
</center>

<p>Now Brett of <a href="http://brevitb.blogspot.com.au/">BRevit</a> presented a

<a href="https://www.youtube.com/watch?v=lYrpJe2484E&feature=youtu.be">20-second video of WheelConcept</a>,

a working implementation of a right-click circle of commands based on the PostCommand API.</p>

<p>In his own words:</p>

<p>I think a lot can be achieved with the postcommand function. Hope you don't mind but i took your idea and gave it a crack....</p>

<p>Firstly i created a form with the wheel as the background. I created a public property on the form which is the id of the command to issue:</p>

<pre class="code">
&nbsp; <span class="blue">Public</span> CommandToIssue <span class="blue">As</span> <span class="teal">RevitCommandId</span>
</pre>

<p>I then created transparent picture boxes over the various icons. Clicking on a picturebox asigns a command id and closes the form:</p>

<pre class="code">
&nbsp; <span class="blue">Private</span> <span class="blue">Sub</span> PictureBox2_Click( _
&nbsp; &nbsp; <span class="blue">ByVal</span> sender <span class="blue">As</span> <span class="blue">Object</span>, _
&nbsp; &nbsp; <span class="blue">ByVal</span> e <span class="blue">As</span> EventArgs) _
&nbsp; <span class="blue">Handles</span> PictureBox2.Click
&nbsp; &nbsp; CommandToIssue _
&nbsp; &nbsp; &nbsp; = <span class="teal">RevitCommandId</span>.LookupPostableCommandId( _
&nbsp; &nbsp; &nbsp; &nbsp; <span class="teal">PostableCommand</span>.StructuralColumn)
&nbsp; &nbsp; Close()
&nbsp; <span class="blue">End</span> <span class="blue">Sub</span>
</pre>

<p>Under the forms show event i added code to locate the form at the mouses current position:</p>

<pre class="code">
&nbsp; <span class="blue">Private</span> <span class="blue">Sub</span> WheelForm_Shown( _
&nbsp; &nbsp; <span class="blue">ByVal</span> sender <span class="blue">As</span> <span class="blue">Object</span>, _
&nbsp; &nbsp; <span class="blue">ByVal</span> e <span class="blue">As</span> EventArgs) _
&nbsp; <span class="blue">Handles</span> <span class="blue">Me</span>.Shown
&nbsp; &nbsp; Location = <span class="blue">New</span> System.Drawing.<span class="teal">Point</span>( _
&nbsp; &nbsp; &nbsp; <span class="blue">CInt</span>(MousePosition.X - (<span class="blue">Me</span>.Width / 2)), _
&nbsp; &nbsp; &nbsp; <span class="blue">CInt</span>(MousePosition.Y - (<span class="blue">Me</span>.Width / 2)))
&nbsp; <span class="blue">End</span> <span class="blue">Sub</span>
</pre>

<p>Finally I setup a command to display the wheel, and post the command:</p>

<pre class="code">
<span class="blue">Option Strict On</span>
<span class="blue">Option Explicit On</span>
&nbsp;
<span class="blue">Imports</span> Autodesk.Revit.Attributes
<span class="blue">Imports</span> Autodesk.Revit.UI
&nbsp;
<span class="blue">Imports</span> BrevitTools.UI.Wheel
&nbsp;
&lt;<span class="teal">Transaction</span>(<span class="teal">TransactionMode</span>.Manual)&gt; _
<span class="blue">Public</span> <span class="blue">Class</span> <span class="teal">Wheel</span>
&nbsp; <span class="blue">Implements</span> <span class="teal">IExternalCommand</span>
&nbsp;
&nbsp; <span class="blue">Public</span> <span class="blue">Function</span> Execute( _
&nbsp; &nbsp; <span class="blue">ByVal</span> cmdData <span class="blue">As</span> <span class="teal">ExternalCommandData</span>, _
&nbsp; &nbsp; <span class="blue">ByRef</span> message <span class="blue">As</span> <span class="blue">String</span>, _
&nbsp; &nbsp; <span class="blue">ByVal</span> elements <span class="blue">As</span> Autodesk.Revit.DB.<span class="teal">ElementSet</span>) _
&nbsp; <span class="blue">As</span> <span class="teal">Result</span> <span class="blue">Implements</span> <span class="teal">IExternalCommand</span>.Execute
&nbsp;
&nbsp; &nbsp; <span class="blue">Dim</span> form <span class="blue">As</span> <span class="blue">New</span> WheelForm
&nbsp; &nbsp; form.ShowDialog()
&nbsp;
&nbsp; &nbsp; <span class="blue">If</span> form.CommandToIssue <span class="blue">IsNot</span> <span class="blue">Nothing</span> <span class="blue">Then</span>
&nbsp; &nbsp; &nbsp; cmdData.Application.PostCommand(
&nbsp; &nbsp; &nbsp; &nbsp; form.CommandToIssue)
&nbsp; &nbsp; <span class="blue">End</span> <span class="blue">If</span>
&nbsp;
&nbsp; &nbsp; <span class="blue">Return</span> <span class="teal">Result</span>.Succeeded
&nbsp;
&nbsp; <span class="blue">End</span> <span class="blue">Function</span>
&nbsp;
<span class="blue">End</span> <span class="blue">Class</span>
</pre>

<p>To display the wheel inside Revit I assigned a shotcut key (ww).</p>

<p>Here is link to a

<a href="https://www.youtube.com/watch?v=lYrpJe2484E&feature=youtu.be">
video of it in action</a>.</p>

<p>I think there is loads of potential for this. You could easily add code to check what elements are preselected and then display a contextual wheel.</p>

<p>Thank you very much, Brett, for sharing this!</p>
