<p><head>
<title>The Building Coder</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<link rel="stylesheet" type="text/css" href="3dwc.css"/>
<script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js?autoload=true" defer="defer"></script>
</head></p>
<!---

The Birth of Roomedit3dv3 and Forge Webinar 2 #revitapi #3dwebcoder @AutodeskRevit @AutodeskForge #aec #bim

I made my choice on the starting point for the new <code>roomedit3d</code> incarnation, and the second Forge webinar was successfully held
&ndash; The birth of Roomedit3dv3
&ndash; Forge webinar session 2 on OAuth and the Data Management API...

-->

<h3>Flipping a Section View and Forge Webinar 3</h3>
<p>I already created a starting point for the
new <a href="https://github.com/jeremytammik/roomedit3d">roomedit3d</a> incarnation
last week, in its own
repository <a href="https://github.com/jeremytammik/roomedit3dv3">roomedit3dv3</a>.</p>
<p>However, please forget that right away.</p>
<p>This week, I agreeing with Philippe to retain the new project in an own
dedicated <a href="https://github.com/Autodesk-Forge/forge-boilers.nodejs/tree/roomedit3d">roomedit3d branch</a> within his
original <a href="https://github.com/Autodesk-Forge/forge-boilers.nodejs">Forge boilerplate code sample collection</a>.</p>
<p>Hopefully, that will simplify keeping my BIM sample synchronised with any future updates that he makes.</p>
<p>Now I need to get started implementing and testing the actual viewer extension functionality itself.</p>
<p>My main topic today is something different and pure Revit API oriented, besides the next Forge session:</p>
<ul>
<li><a href="#2">Flipping a Section View</a></li>
<li><a href="#3">Forge webinar series</a></li>
</ul>
<h4><a name="2"></a>Flipping a Section View</h4>
<p>Here is a recent interting little case handled by Jim Jia and answered by Paolo Serra:</p>
<p><strong>Question:</strong> I want to create a new model with a section view based on an existing one with the same cross-sectional view but a different crop box.</p>
<p>To do so, I perform, these steps:</p>
<ol>
<li>
<p>Open the old model file, find the required cross-sectional view.</p>
</li>
<li>
<p>Create a new model within the same bounding box, using the old model view CropBox created like this:</p>
</li>
</ol>
<pre class="code">
&nbsp;&nbsp;<span style="color:#2b91af;">Transform</span>&nbsp;transform&nbsp;=&nbsp;view.CropBox.Transform;
&nbsp;&nbsp;<span style="color:#2b91af;">BoundingBoxXYZ</span>&nbsp;box&nbsp;=&nbsp;<span style="color:blue;">new</span>&nbsp;<span style="color:#2b91af;">BoundingBoxXYZ</span>();
&nbsp;&nbsp;box.Enabled&nbsp;=&nbsp;<span style="color:blue;">true</span>;
&nbsp;&nbsp;<span style="color:#2b91af;">XYZ</span>&nbsp;maxPoint&nbsp;=&nbsp;view.CropBox.Max;
&nbsp;&nbsp;<span style="color:#2b91af;">XYZ</span>&nbsp;minPoint&nbsp;=&nbsp;view.CropBox.Min;
&nbsp;&nbsp;box.Transform&nbsp;=&nbsp;transform;
&nbsp;&nbsp;box.Max&nbsp;=&nbsp;maxPoint;
&nbsp;&nbsp;box.Min&nbsp;=&nbsp;minPoint;
&nbsp;&nbsp;<span style="color:#2b91af;">ViewSection</span>&nbsp;viewSection&nbsp;=&nbsp;<span style="color:#2b91af;">ViewSection</span>.CreateSection(&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;doc,&nbsp;view.GetTypeId(),&nbsp;box&nbsp;);
</pre>

<p>This works and I can create a cross-sectional view through this method, but in the opposite direction of the existing view, like this:</p>
<p><center>
<img src="img/viewsection_flipped.png" alt="Section view flipped" width="515">
</center></p>
<p>How can I flip the view direction to solve this problem?</p>
<p><strong>Answer:</strong> A few days ago I was trying to do the same.</p>
<p>What worked for me was to reverse the <code>RightDirection</code> vector of the original view and recreate a transform to apply to the <code>BoundingBoxXYZ</code>.</p>
<p>You should also take into consideration the different transforms you might have in the two documents.</p>
<pre class="code">
&nbsp;&nbsp;<span style="color:#2b91af;">Transform</span>&nbsp;tr&nbsp;=&nbsp;view.CropBox.Transform;

&nbsp;&nbsp;tr.BasisX&nbsp;=&nbsp;-view.RightDirection;
&nbsp;&nbsp;tr.BasisY&nbsp;=&nbsp;<span style="color:#2b91af;">XYZ</span>.BasisZ;
&nbsp;&nbsp;tr.BasisZ&nbsp;=&nbsp;tr.BasisX.CrossProduct(&nbsp;tr.BasisY&nbsp;);

&nbsp;&nbsp;<span style="color:#2b91af;">BoundingBoxXYZ</span>&nbsp;bb&nbsp;=&nbsp;<span style="color:blue;">new</span>&nbsp;<span style="color:#2b91af;">BoundingBoxXYZ</span>();
&nbsp;&nbsp;bb.Transform&nbsp;=&nbsp;tr;
&nbsp;&nbsp;<span style="color:#2b91af;">XYZ</span>&nbsp;min&nbsp;=&nbsp;view.CropBox.Min;
&nbsp;&nbsp;<span style="color:#2b91af;">XYZ</span>&nbsp;max&nbsp;=&nbsp;view.CropBox.Max;
&nbsp;&nbsp;bb.Min&nbsp;=&nbsp;<span style="color:blue;">new</span>&nbsp;<span style="color:#2b91af;">XYZ</span>(&nbsp;min.X,&nbsp;min.Y,&nbsp;0&nbsp;);
&nbsp;&nbsp;bb.Max&nbsp;=&nbsp;<span style="color:blue;">new</span>&nbsp;<span style="color:#2b91af;">XYZ</span>(&nbsp;max.X,&nbsp;max.Y,&nbsp;-min.Z&nbsp;);

&nbsp;&nbsp;<span style="color:#2b91af;">ElementId</span>&nbsp;vftId&nbsp;=&nbsp;<span style="color:blue;">new</span>&nbsp;<span style="color:#2b91af;">FilteredElementCollector</span>(&nbsp;doc&nbsp;)
&nbsp;&nbsp;&nbsp;&nbsp;.OfClass(&nbsp;<span style="color:blue;">typeof</span>(&nbsp;<span style="color:#2b91af;">ViewFamilyType</span>&nbsp;)&nbsp;)
&nbsp;&nbsp;&nbsp;&nbsp;.WhereElementIsElementType()
&nbsp;&nbsp;&nbsp;&nbsp;.Cast&lt;<span style="color:#2b91af;">ViewFamilyType</span>&gt;()
&nbsp;&nbsp;&nbsp;&nbsp;.First(&nbsp;x&nbsp;=&gt;&nbsp;x.ViewFamily&nbsp;==&nbsp;<span style="color:#2b91af;">ViewFamily</span>.Section&nbsp;)
&nbsp;&nbsp;&nbsp;&nbsp;.Id;

&nbsp;&nbsp;<span style="color:#2b91af;">View</span>&nbsp;newView&nbsp;=&nbsp;<span style="color:#2b91af;">ViewSection</span>.CreateSection(&nbsp;doc,&nbsp;vftId,&nbsp;bb&nbsp;);
</pre>

<p><strong>Response:</strong> Thanks a lot, it works!</p>
<p>Many thanks to Jim and Paolo for sharing this!</p>
<h4><a name="3"></a>Forge Webinar Series</h4>
<p>Tomorrow we are presenting the third session in the ongoing Forge webinar series.</p>
<p>Support documentation and recordings from the frst two sessions for your future reference and enjoyment:</p>
<ul>
<li>September 20 <a href="http://adndevblog.typepad.com/cloud_and_mobile/2016/09/introduction-to-autodesk-forge-and-the-autodesk-app-store.html">Introduction to Autodesk Forge and the Autodesk App Store</a></li>
<li>September 22 <a href="http://adndevblog.typepad.com/cloud_and_mobile/2016/09/introduction-to-oauth-and-data-management-api.html">Introduction to OAuth and Data Management API</a>
&ndash; on <a href="https://developer.autodesk.com/en/docs/oauth/v2/overview">OAuth</a>
and <a href="https://developer.autodesk.com/en/docs/data/v2/overview">Data Management API</a>, providing token-based authentication, authorization and a unified and consistent way to access data across A360, Fusion 360, and the Object Storage Service.</li>
</ul>
<p>Upcoming sessions continuing during the remainder of
the <a href="http://autodeskforge.devpost.com">Autodesk App Store Forge and Fusion 360 Hackathon</a> until the end of October:</p>
<ul>
<li>September 27 &ndash; <a href="https://developer.autodesk.com/en/docs/model-derivative/v2/overview">Model Derivative API</a> &ndash; enable users to represent and share their designs in different formats and extract metadata.</li>
<li>September 29 &ndash; <a href="https://developer.autodesk.com/en/docs/viewer/v2/overview">Viewer API</a> &ndash; 
formerly part of the 'View and Data API', a WebGL-based, JavaScript library for 3D and 2D model rendering a CAD data from seed models, e.g., <a href="http://www.autodesk.com/products/autocad/overview">AutoCAD</a>, <a href="http://www.autodesk.com/products/fusion-360/overview">Fusion 360</a>, <a href="http://www.autodesk.com/products/revit-family/overview">Revit</a>, and many other formats.</li>
<li>October 4 &ndash; <a href="https://developer.autodesk.com/en/docs/design-automation/v2/overview">Design Automation API</a> &ndash; formerly known as 'AutoCAD I/O', run scripts on design files.</li>
<li>October 6 &ndash; <a href="https://developer.autodesk.com/en/docs/bim360/v1/overview">BIM360</a> &ndash; develop apps that integrate with BIM 360 to extend its capabilities in the construction ecosystem.</li>
<li>October 11 &ndash; <a href="http://help.autodesk.com/view/NINVFUS/ENU/?guid=GUID-A92A4B10-3781-4925-94C6-47DA85A4F65A">Fusion 360 Client API</a> &ndash; an integrated CAD, CAM, and CAE tool for product development, built for the new ways products are designed and made.</li>
<li>October 13 &ndash; Q&amp;A on all APIs.</li>
<li>October 20 &ndash; Q&amp;A on all APIs.</li>
<li>October 27 &ndash; Submitting a web service app to Autodesk App store.</li>
</ul>
<p><center>
<img src="img/forge_accelerator.png" alt="Forge &ndash; build the future of making things together" width="400">
</center></p>