<p><head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<link rel="stylesheet" type="text/css" href="bc.css">
<script src="run_prettify.js" type="text/javascript"></script>
<!--
<script src="https://google-code-prettify.googlecode.com/svn/loader/run_prettify.js" type="text/javascript"></script>
-->
</head></p>
<!---

http://thebuildingcoder.typepad.com/blog/2014/04/determining-the-size-and-location-of-viewports-on-a-sheet.html#comment-3045289101

 #RevitAPI @AutodeskRevit #aec #bim #dynamobim @AutodeskForge

&ndash; 
...

-->

<h3>Viewport Bring to Front</h3>
<p>Joshua Lumley submitted
a <a href="http://thebuildingcoder.typepad.com/blog/2014/04/determining-the-size-and-location-of-viewports-on-a-sheet.html#comment-3045289101">comment</a> on
the discussion on <a href="http://thebuildingcoder.typepad.com/blog/2014/04/determining-the-size-and-location-of-viewports-on-a-sheet.html">Determining the Size and Location of Viewports on a Sheet</a>,
suggesting:</p>
<blockquote>
<p>I made code that will change the draw order of a viewport (bring to front) in the cases when you need to use simplified duplicate of the same view for background (ceiling grid for example). Are you interested in it? I was hoping you could make a post and share it with the world (it has impressed my colleagues anyway).</p>
<p>Here is the essence of the code:</p>
</blockquote>
<pre class="code">
&nbsp;&nbsp;<span style="color:#2b91af;">ElementId</span>&nbsp;ViewElementID&nbsp;=&nbsp;ViewportList1[listBox1.SelectedIndex].ViewId;
&nbsp;&nbsp;<span style="color:#2b91af;">XYZ</span>&nbsp;storetheposition&nbsp;=&nbsp;ViewportList1[listBox1.SelectedIndex].GetBoxCenter();
&nbsp;&nbsp;<span style="color:#2b91af;">ElementId</span>&nbsp;storetypetypeID&nbsp;=&nbsp;ViewportList1[listBox1.SelectedIndex].GetTypeId();

&nbsp;&nbsp;Autodesk.Revit.DB.<span style="color:#2b91af;">View</span>&nbsp;pView&nbsp;=&nbsp;doc.ActiveView;&nbsp;Autodesk.Revit.DB.<span style="color:#2b91af;">Transaction</span>
&nbsp;&nbsp;&nbsp;t&nbsp;=&nbsp;<span style="color:blue;">new</span>&nbsp;Autodesk.Revit.DB.<span style="color:#2b91af;">Transaction</span>(&nbsp;doc,&nbsp;<span style="color:#a31515;">&quot;Form_2&quot;</span>&nbsp;);
&nbsp;&nbsp;t.Start();
&nbsp;&nbsp;ViewSheet1.DeleteViewport(&nbsp;ViewportList1[listBox1.SelectedIndex]&nbsp;);
&nbsp;&nbsp;<span style="color:#2b91af;">Viewport</span>&nbsp;vvp&nbsp;=&nbsp;<span style="color:#2b91af;">Viewport</span>.Create(&nbsp;doc,&nbsp;ViewSheet1.Id,&nbsp;ViewElementID,&nbsp;storetheposition&nbsp;);
&nbsp;&nbsp;vvp.ChangeTypeId(&nbsp;storetypetypeID&nbsp;);
&nbsp;&nbsp;t.Commit();</pre>

</pre>

<p>As you can see, it is simply taking out a viewport and putting it back in the same place, because Revit paints viewports in the order they were created, so the most recently created viewport will come to the front.</p>
<p>This is the first view which has been placed on a sheet:</p>
<p><center>
<img src="img/viewport_bring_front_1_initial_view.jpg" alt="The intial view" width="368"/>
</center></p>
<p>Now we need to pretty it up with patterns, e.g., the ceiling grid and cable ladder fill taken from a 'medium' level detail view:</p>
<p><center>
<img src="img/viewport_bring_front_2_second_third_view.jpg" alt="Placing a second and third view for ceiling grid and cable ladder background" width="369"/>
</center></p>
<p>As you can see, these new views have been placed over the main view and now block it.</p>
<p>The code automates removing a viewport and making an identical one in the same place with a new element ID. </p>
<p><center>
<img src="img/viewport_bring_front_3_reordering.jpg" alt="Reordering the viewports and done" width="375"/>
</center></p>
<p>You can see here the supplementry ceiling grid and ladder background (filtered to appear light red) adds value, but does not interfere with main view because it is now 'behind'. btw i changed the furntire to halftone manually, this is not an effect of the layering.</p>
<p>Obviously the perfect draftsman would be placing views in the correct sequence to begin with, but because the stylistic 'touch ups' are the last stages of making a drawing and you can never know in advanced what your going to need.</p>
<p>In my opinion making a drawing nice to look at is just as important as the content itself.</p>
<h4><a name="2"></a>Code Clean-Up</h4>
<p>I cleaned up the initial code suggestion like this:</p>
<pre class="code">
<span style="color:gray;">///</span><span style="color:green;">&nbsp;</span><span style="color:gray;">&lt;</span><span style="color:gray;">summary</span><span style="color:gray;">&gt;</span>
<span style="color:gray;">///</span><span style="color:green;">&nbsp;Bring&nbsp;viewport&nbsp;to&nbsp;front&nbsp;by&nbsp;</span>
<span style="color:gray;">///</span><span style="color:green;">&nbsp;deleting&nbsp;and&nbsp;recreating&nbsp;it.</span>
<span style="color:gray;">///</span><span style="color:green;">&nbsp;</span><span style="color:gray;">&lt;/</span><span style="color:gray;">summary</span><span style="color:gray;">&gt;</span>
<span style="color:blue;">void</span>&nbsp;ViewportBringToFront(&nbsp;<span style="color:#2b91af;">ViewSheet</span>&nbsp;sheet,&nbsp;<span style="color:#2b91af;">Viewport</span>&nbsp;viewport&nbsp;)
{
&nbsp;&nbsp;<span style="color:#2b91af;">Document</span>&nbsp;doc&nbsp;=&nbsp;sheet.Document;

&nbsp;&nbsp;<span style="color:#2b91af;">ElementId</span>&nbsp;viewId&nbsp;=&nbsp;viewport.ViewId;
&nbsp;&nbsp;<span style="color:#2b91af;">XYZ</span>&nbsp;boxCenter&nbsp;=&nbsp;viewport.GetBoxCenter();

&nbsp;&nbsp;<span style="color:green;">//ElementId&nbsp;typeId&nbsp;=&nbsp;viewport.GetTypeId();</span>
&nbsp;&nbsp;<span style="color:green;">//View&nbsp;view&nbsp;=&nbsp;doc.ActiveView;</span>

&nbsp;&nbsp;<span style="color:blue;">using</span>(&nbsp;<span style="color:#2b91af;">Transaction</span>&nbsp;t&nbsp;=&nbsp;<span style="color:blue;">new</span>&nbsp;<span style="color:#2b91af;">Transaction</span>(&nbsp;doc&nbsp;)&nbsp;)
&nbsp;&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;t.Start(&nbsp;<span style="color:#a31515;">&quot;Delete&nbsp;and&nbsp;Recreate&nbsp;Viewport&quot;</span>&nbsp;);
&nbsp;&nbsp;&nbsp;&nbsp;sheet.DeleteViewport(&nbsp;viewport&nbsp;);
&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#2b91af;">Viewport</span>&nbsp;vvp&nbsp;=&nbsp;<span style="color:#2b91af;">Viewport</span>.Create(&nbsp;doc,&nbsp;sheet.Id,&nbsp;viewId,&nbsp;boxCenter&nbsp;);
&nbsp;&nbsp;&nbsp;&nbsp;vvp.ChangeTypeId(&nbsp;typeId&nbsp;);
&nbsp;&nbsp;&nbsp;&nbsp;t.Commit();
&nbsp;&nbsp;}
}
</pre>

<p>Notes:</p>
<ul>
<li>Separate code from user interface implementation details. Isolate real functionality in separate methods. <a href="https://en.wikipedia.org/wiki/KISS_principle">Keep it simple</a>!</li>
<li>Encapsulate <code>Transaction</code> use in a separate <code>using</code> statement. Look at the explanations in The Building Coder topic group on <a href="http://thebuildingcoder.typepad.com/blog/about-the-author.html#5.53">handling transactions and transaction groups</a>.</li>
<li>Simplified variable names for better readability and clarity.</li>
<li>Commented out unused variables.</li>
</ul>
<p>I added this method to <a href="https://github.com/jeremytammik/the_building_coder_samples">The Building Coder samples</a> in the
<a href="https://github.com/jeremytammik/the_building_coder_samples/blob/master/BuildingCoder/BuildingCoder/CmdViewsShowingElements.cs#L424-L445">module CmdViewsShowingElements.cs line 424-445</a>.</p>
<p>Very many thanks to Joshua for sharing this and putting in all the work to document it, edit the draft markdown file and create
a <a href="https://github.com/jeremytammik/tbc/pull/1">pull request</a> for it in
the <a href="https://github.com/jeremytammik/tbc">tbc GitHub repo</a>!</p>