<p><head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<link rel="stylesheet" type="text/css" href="bc.css">
<script src="run_prettify.js" type="text/javascript"></script>
<!--
<script src="https://google-code-prettify.googlecode.com/svn/loader/run_prettify.js" type="text/javascript"></script>
-->
</head></p>
<!---

- http://thebuildingcoder.typepad.com/blog/2016/12/nuget-revit-api-package.html#comment-3133102375
  Eric Anastas: I created another Revit related Nuget package you and your readers may be interested in. It's a .NET library that wraps the Revit Server REST API.
  https://www.nuget.org/packages/RevitServerAPILib/
  https://bitbucket.org/somddg/revitserverapilib

- merged [pull request #21](https://github.com/jeremytammik/RevitLookup/pull/21) by [@eibre](https://github.com/eibre) adding `UnitType` property on the parameter `Definition` class
  https://github.com/jeremytammik/RevitLookup/releases/tag/2017.0.0.12

- Component of a truss: Truss.Members and FamilyInstance.GetSubComponentIds
  http://forums.autodesk.com/t5/revit-api-forum/component-of-a-truss/m-p/6845784

- GeometryObject layer name
  http://forums.autodesk.com/t5/revit-api-forum/geometryobject-layer-name/m-p/6835165

#RevitAPI @AutodeskRevit #aec #bim #dynamobim @AutodeskForge

Today, we proudly present
&ndash; NuGet Revit Server REST API Library
&ndash; RevitLookup Updates
&ndash; Truss Members and FamilyInstance Sub-Components
&ndash; GeometryObject Layer Name...

-->

<h3>Revit Server API Lib, Truss Members and Layers</h3>
<p>Today, we proudly present:</p>
<ul>
<li><a href="#2">NuGet Revit Server REST API Library</a></li>
<li><a href="#3">RevitLookup Updates</a></li>
<li><a href="#4">Truss Members and FamilyInstance Sub-Components</a></li>
<li><a href="#5">GeometryObject Layer Name</a></li>
</ul>
<h4><a name="2"></a>NuGet Revit Server REST API Library</h4>
<p>Eric Anastas posted
a <a href="http://thebuildingcoder.typepad.com/blog/2016/12/nuget-revit-api-package.html#comment-3133102375">comment</a> on
the discussion of Andrey Bushman's <a href="http://thebuildingcoder.typepad.com/blog/2016/12/nuget-revit-api-package.html">NuGet Revit API package</a>:</p>
<blockquote>
<p>I created another Revit related Nuget package you and your readers may be interested in.
It's a .NET library that wraps the Revit Server REST API:</p>
</blockquote>
<ul>
<li><a href="https://www.nuget.org/packages/RevitServerAPILib">RevitServerAPILib package on NuGet </a></li>
<li><a href="https://bitbucket.org/somddg/revitserverapilib">RevitServerAPILib source on BitBucket</a></li>
</ul>
<p>Many thanks to Eric for implementing and sharing this!</p>
<p><center>
<img src="img/nuget_logo.png" alt="" width="64"/>
</center></p>
<h4><a name="3"></a>RevitLookup Updates</h4>
<p>I integrated another couple of pull requests into RevitLookup.</p>
<p>Today, I added <a href="https://github.com/eibre">Einar Raknes</a>' simple but significant one-liner
to <a href="https://github.com/jeremytammik/RevitLookup/compare/2017.0.0.11...2017.0.0.12">display the <code>UnitType</code> or a parameter <code>Definition</code> class instance</a>:</p>
<pre class="code">
&nbsp;&nbsp;data.Add(&nbsp;<span style="color:blue;">new</span>&nbsp;Snoop.Data.<span style="color:#2b91af;">String</span>(&nbsp;<span style="color:#a31515;">&quot;Unit&nbsp;type&quot;</span>,
&nbsp;&nbsp;&nbsp;&nbsp;paramDef.UnitType.ToString()&nbsp;)&nbsp;);
</pre>

<p>Thanks to Einar for spotting this and creating the <a href="https://github.com/jeremytammik/RevitLookup/pull/21">pull request #21</a> for it!</p>
<p>Here it is with a little bit more context:</p>
<pre class="code">
<span style="color:blue;">private</span>&nbsp;<span style="color:blue;">void</span>
Stream(&nbsp;<span style="color:#2b91af;">ArrayList</span>&nbsp;data,&nbsp;<span style="color:#2b91af;">Definition</span>&nbsp;paramDef&nbsp;)
{
&nbsp;&nbsp;data.Add(&nbsp;<span style="color:blue;">new</span>&nbsp;Snoop.Data.<span style="color:#2b91af;">ClassSeparator</span>(&nbsp;<span style="color:blue;">typeof</span>(&nbsp;<span style="color:#2b91af;">Definition</span>&nbsp;)&nbsp;)&nbsp;);

&nbsp;&nbsp;data.Add(&nbsp;<span style="color:blue;">new</span>&nbsp;Snoop.Data.<span style="color:#2b91af;">String</span>(&nbsp;<span style="color:#a31515;">&quot;Name&quot;</span>,&nbsp;paramDef.Name&nbsp;)&nbsp;);
&nbsp;&nbsp;data.Add(&nbsp;<span style="color:blue;">new</span>&nbsp;Snoop.Data.<span style="color:#2b91af;">String</span>(&nbsp;<span style="color:#a31515;">&quot;Parameter&nbsp;type&quot;</span>,&nbsp;paramDef.ParameterType.ToString()&nbsp;)&nbsp;);
&nbsp;&nbsp;data.Add(&nbsp;<span style="color:blue;">new</span>&nbsp;Snoop.Data.<span style="color:#2b91af;">String</span>(&nbsp;<span style="color:#a31515;">&quot;Parameter&nbsp;group&quot;</span>,&nbsp;paramDef.ParameterGroup.ToString()&nbsp;)&nbsp;);
&nbsp;&nbsp;data.Add(&nbsp;<span style="color:blue;">new</span>&nbsp;Snoop.Data.<span style="color:#2b91af;">String</span>(&nbsp;<span style="color:#a31515;">&quot;Unit&nbsp;type&quot;</span>,&nbsp;paramDef.UnitType.ToString()&nbsp;)&nbsp;);

&nbsp;&nbsp;<span style="color:#2b91af;">ExternalDefinition</span>&nbsp;extDef&nbsp;=&nbsp;paramDef&nbsp;<span style="color:blue;">as</span>&nbsp;<span style="color:#2b91af;">ExternalDefinition</span>;
&nbsp;&nbsp;<span style="color:blue;">if</span>(&nbsp;extDef&nbsp;!=&nbsp;<span style="color:blue;">null</span>&nbsp;)
&nbsp;&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;Stream(&nbsp;data,&nbsp;extDef&nbsp;);
&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:blue;">return</span>;
&nbsp;&nbsp;}

&nbsp;&nbsp;<span style="color:#2b91af;">InternalDefinition</span>&nbsp;intrnalDef&nbsp;=&nbsp;paramDef&nbsp;<span style="color:blue;">as</span>&nbsp;<span style="color:#2b91af;">InternalDefinition</span>;
&nbsp;&nbsp;<span style="color:blue;">if</span>(&nbsp;intrnalDef&nbsp;!=&nbsp;<span style="color:blue;">null</span>&nbsp;)
&nbsp;&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;Stream(&nbsp;data,&nbsp;intrnalDef&nbsp;);
&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:blue;">return</span>;
&nbsp;&nbsp;}
}
</pre>

<p>Check out the newest release in the <a href="https://github.com/jeremytammik/RevitLookup">RevitLookup GitHub repository</a>.</p>
<p>I am looking forward to your pull requests to add further enhancements that are important for you.</p>
<h4><a name="4"></a>Truss Members and FamilyInstance Sub-Components</h4>
<p>I have been pretty active lately in
the <a href="http://forums.autodesk.com/t5/revit-api-forum/bd-p/160">Revit API discussion forum</a>,
and so have Matt Taylor and Frank 'Fair59', who provided many important answers that I was not aware of.</p>
<p>I'll pick up two of Franks nice succinct answers here today.</p>
<p>The first is on retrieving the <a href="http://forums.autodesk.com/t5/revit-api-forum/component-of-a-truss/m-p/6845784">components of a truss</a>:</p>
<p><strong>Question:</strong> I would like to get the components of a truss. 
Using the API, I tried via the <code>GroupId</code> property, but it doesn't work.
And in general, the components of a family.</p>
<p><strong>Answer:</strong> Components of a truss:</p>
<pre class="code">
  Autodesk.Revit.DB.Structure.<span style="color:#2b91af;">Truss</span>&nbsp;_truss;
  List&lt;<span style="color:#2b91af;">ElementId</span>&gt;&nbsp;_members&nbsp;=&nbsp;_truss.Members.ToList&lt;<span style="color:#2b91af;">ElementId</span>&gt;();
</pre>

<p>In general, for user created families:</p>
<pre class="code">
  <span style="color:#2b91af;">FamilyInstance</span>&nbsp;_instance;
  List&lt;<span style="color:#2b91af;">ElementId</span>&gt;&nbsp;_members&nbsp;=&nbsp;_instance.GetSubComponentIds()
    .ToList&lt;<span style="color:#2b91af;">ElementId</span>&gt;();
</pre>

<h4><a name="5"></a>GeometryObject Layer Name</h4>
<p>The second nice succinct answer by Frank 'Fair59' is on
the <a href="http://forums.autodesk.com/t5/revit-api-forum/geometryobject-layer-name/m-p/6835165"><code>GeometryObject</code> Layer Name</a>:</p>
<p><strong>Question:</strong> I can loop the objects of a linked CAD file like this:</p>
<pre class="code">
  <span style="color:blue;">foreach</span>(&nbsp;<span style="color:#2b91af;">GeometryObject</span>&nbsp;geometryObj&nbsp;<span style="color:blue;">in</span>&nbsp;
  &nbsp;&nbsp;dwg.get_Geometry(&nbsp;<span style="color:blue;">new</span>&nbsp;<span style="color:#2b91af;">Options</span>()&nbsp;)&nbsp;)
  {
  }
</pre>

<p>How can I access the layer name of the object?</p>
<p><strong>Answer:</strong> The information is contained in the <code>GraphicalStyle</code> element:</p>
<pre class="code">
  <span style="color:#2b91af;">GraphicsStyle</span>&nbsp;gStyle&nbsp;=&nbsp;document.GetElement(
    geometryObj.GraphicsStyleId&nbsp;)&nbsp;<span style="color:blue;">as</span>&nbsp;<span style="color:#2b91af;">GraphicsStyle</span>;
</pre>

<p>The layer name is provided by <code>gStyle.GraphicsStyleCategory.Name</code>.</p>