<p><head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<link rel="stylesheet" type="text/css" href="bc.css">
<script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js" type="text/javascript"></script>
</head></p>
<!---

twitter:

 in the #RevitAPI @AutodeskForge @AutodeskRevit #bim #DynamoBim #ForgeDevCon 

Luk치코 Kohout brought up an interesting and important issue on changing material texture path with <code>EditScope</code>
&ndash; How to set the material texture path?
&ndash; Suggestions
&ndash; Solution and sample material
&ndash; <code>ChangeRenderingTexturePath</code> method
&ndash; Step by step guide
&ndash; Test run...

linkedin:

-->

<h3>Set Material Texture Path in EditScope</h3>
<p>Luk치코 <a href="https://forums.autodesk.com/t5/user/viewprofilepage/user-id/767846">kohoulu3</a> Kohout
brought up an interesting and important issue in 
the <a href="http://forums.autodesk.com/t5/revit-api-forum/bd-p/160">Revit API discussion forum</a> thread
on <a href="https://forums.autodesk.com/t5/revit-api-forum/changing-material-texture-path-with-editscope/m-p/8017578">changing material texture path with <code>EditScope</code></a> that
I wanted to highlight last year. Here it is, finally:</p>
<ul>
<li><a href="#2">How to set the material texture path?</a> </li>
<li><a href="#3">Suggestions</a> </li>
<li><a href="#4">Solution and sample material</a> </li>
<li><a href="#5"><code>ChangeRenderingTexturePath</code> method</a> </li>
<li><a href="#6">Step by step guide</a> </li>
<li><a href="#7">Test run</a> </li>
</ul>
<h4><a name="2"></a> How to Set the Material Texture Path?</h4>
<p>I am trying to set material texture path using following code (Revit 2018):</p>
<pre class="code">
&nbsp;&nbsp;<span style="color:blue;">public</span>&nbsp;<span style="color:blue;">void</span>&nbsp;ChangeRenderingTexturePath(&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#2b91af;">Material</span>&nbsp;mat,&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#2b91af;">Document</span>&nbsp;doc,
&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:blue;">string</span>&nbsp;texturePath&nbsp;)
&nbsp;&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#2b91af;">AppearanceAssetElement</span>&nbsp;appearanceAsset
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=&nbsp;(<span style="color:#2b91af;">AppearanceAssetElement</span>)&nbsp;doc.GetElement(
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;mat.AppearanceAssetId&nbsp;);

&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#2b91af;">Asset</span>&nbsp;renderingAsset&nbsp;=&nbsp;appearanceAsset
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.GetRenderingAsset();

&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:blue;">int</span>&nbsp;size&nbsp;=&nbsp;renderingAsset.Size;
&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:blue;">for</span>(&nbsp;<span style="color:blue;">int</span>&nbsp;assetIdx&nbsp;=&nbsp;0;&nbsp;assetIdx&nbsp;&lt;&nbsp;size;&nbsp;assetIdx++&nbsp;)
&nbsp;&nbsp;&nbsp;&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#2b91af;">AssetProperty</span>&nbsp;aProperty&nbsp;=&nbsp;renderingAsset[assetIdx];

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:blue;">if</span>(&nbsp;aProperty.NumberOfConnectedProperties&nbsp;&lt;&nbsp;1&nbsp;)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:blue;">continue</span>;

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#2b91af;">Asset</span>&nbsp;connectedAsset&nbsp;=&nbsp;aProperty.GetConnectedProperty(
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0&nbsp;)&nbsp;<span style="color:blue;">as</span>&nbsp;<span style="color:#2b91af;">Asset</span>;

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:blue;">if</span>(&nbsp;connectedAsset.Name&nbsp;==&nbsp;<span style="color:#a31515;">&quot;UnifiedBitmapSchema&quot;</span>&nbsp;)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#2b91af;">AssetPropertyString</span>&nbsp;path&nbsp;=&nbsp;connectedAsset.FindByName(&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#2b91af;">UnifiedBitmap</span>.UnifiedbitmapBitmap&nbsp;)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:blue;">as</span>&nbsp;<span style="color:#2b91af;">AssetPropertyString</span>;

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:blue;">using</span>(&nbsp;<span style="color:#2b91af;">AppearanceAssetEditScope</span>&nbsp;editScope&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=&nbsp;<span style="color:blue;">new</span>&nbsp;<span style="color:#2b91af;">AppearanceAssetEditScope</span>(&nbsp;doc&nbsp;)&nbsp;)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#2b91af;">Asset</span>&nbsp;editableAsset&nbsp;=&nbsp;editScope.Start(&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;mat.AppearanceAssetId&nbsp;);

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:green;">//&nbsp;Exception&nbsp;thrown,&nbsp;asset&nbsp;is&nbsp;read&nbsp;only,&nbsp;</span>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:green;">//&nbsp;need&nbsp;to&nbsp;use&nbsp;editScope</span>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;path.Value&nbsp;=&nbsp;texturePath;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;editScope.Commit(&nbsp;<span style="color:blue;">true</span>&nbsp;);
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;}
</pre>

<p>I know that editScope accepts only ElementId (specifically AppearanceElementAsset.Id), but with this I cannot get to edit the texture path that is saved in <code>RenderingAsset</code> of the <code>AppearanceAsset</code>.</p>
<p>Do anyone know any way to get around this?</p>
<p>Finally, we can create materials with API, but without textures? Does not make sense.</p>
<p>I am using the latest Revit 2018 API with the asset editing functionality included.</p>
<p>I am able to duplicate and edit <code>AppearanceAsset</code>.</p>
<p>I have searched The Building Coder and read both the relevant posts:</p>
<ul>
<li><a href="http://thebuildingcoder.typepad.com/blog/2017/11/modifying-material-visual-appearance.html">Modifying Material Visual Appearance</a></li>
<li><a href="http://thebuildingcoder.typepad.com/blog/2017/10/material-texture-path.html">Material Texture Path</a></li>
</ul>
<p>The way I obtain the current texture path is taken directly from the latter.</p>
<p>Problem with the texture path as I see it is, that it is not directly contained in the <code>AppearanceAsset</code> but in the connected <code>RenderingAsset</code>. And to that I cannot get through the <code>EditScope</code>. <code>RenderingAsset</code> has no <code>ElementId</code> and cannot be used in the <code>AppearanceAssetEditScope.Start</code> function.</p>
<p>Exception message:</p>
<pre>
  An exception of type 'Autodesk.Revit.Exceptions.InvalidOperationException' occurred in RevitAPI.dll but was not handled in user code.
  Additional information: The asset property is not editable. Asset can be edited only in an edit scope.
</pre>

<p>Problem is that the returned asset from <code>AppearanceAssetEditScope.Start</code> does not contain the desired <code>UnifiedBitmapSchema</code> property. That property is contained only in the <code>RenderingAsset</code>.</p>
<h4><a name="3"></a> Suggestions</h4>
<p>The only editable asset inside the edit scope is the one returned from <code>AppearanceAssetEditScope.Start</code>, and those connected assets which it directly returns.</p>
<p>I think if you reverse your code and get the <code>UnifiedBitmapSchema</code> from the returned asset from <code>Start</code>, you will be able to change it.</p>
<p>I'd recommend starting from the code snippet which shows how to do this, available from the <a href="Http://www.revitapidocs.com/2018.1/3a190829-9269-0e56-8b9b-a53b89de35a6.htm">help documentation on <code>GetSingleConnectedAsset</code></a>.</p>
<h4><a name="4"></a> Solution and Sample Material</h4>
<p>Thanks Jeremy. Finally, I got it to work. It was quite simple, actually, in the end.</p>
<p>There is just one small change from the code snippet I posted at first.</p>
<p>Here is the (MaterialTexturePath.zip archive)[zip/lk_MaterialTexturePath.zip] containing
the entire sample Visual Studio solution with detailed guide as well as a sample project and texture to demonstrate.</p>
<p>I hope that someone finds this useful.</p>
<h4><a name="5"></a> ChangeRenderingTexturePath Method</h4>
<p>Here is the final code:</p>
<pre class="code">
&nbsp;&nbsp;<span style="color:blue;">void</span>&nbsp;ChangeRenderingTexturePath(&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#2b91af;">Document</span>&nbsp;doc&nbsp;)
&nbsp;&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:green;">//&nbsp;As&nbsp;there&nbsp;is&nbsp;only&nbsp;one&nbsp;material&nbsp;in&nbsp;the&nbsp;sample&nbsp;</span>
&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:green;">//&nbsp;project,&nbsp;we&nbsp;can&nbsp;use&nbsp;FilteredElementCollector&nbsp;</span>
&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:green;">//&nbsp;and&nbsp;grab&nbsp;the&nbsp;first&nbsp;result</span>

&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#2b91af;">Material</span>&nbsp;mat&nbsp;=&nbsp;<span style="color:blue;">new</span>&nbsp;<span style="color:#2b91af;">FilteredElementCollector</span>(&nbsp;doc&nbsp;)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.OfClass(&nbsp;<span style="color:blue;">typeof</span>(&nbsp;<span style="color:#2b91af;">Material</span>&nbsp;)&nbsp;)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.FirstElement()&nbsp;<span style="color:blue;">as</span>&nbsp;<span style="color:#2b91af;">Material</span>;

&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:green;">//&nbsp;Fixed&nbsp;path&nbsp;for&nbsp;new&nbsp;texture</span>
&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:green;">//&nbsp;Texture&nbsp;included&nbsp;in&nbsp;sample&nbsp;files</span>

&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:blue;">string</span>&nbsp;texturePath&nbsp;=&nbsp;<span style="color:#2b91af;">Path</span>.Combine(&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#2b91af;">Environment</span>.GetFolderPath(&nbsp;<span style="color:#2b91af;">Environment</span>.<span style="color:#2b91af;">SpecialFolder</span>.Desktop&nbsp;),&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#a31515;">&quot;new_texture.png&quot;</span>&nbsp;);

&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:blue;">using</span>(&nbsp;<span style="color:#2b91af;">Transaction</span>&nbsp;t&nbsp;=&nbsp;<span style="color:blue;">new</span>&nbsp;<span style="color:#2b91af;">Transaction</span>(&nbsp;doc&nbsp;)&nbsp;)
&nbsp;&nbsp;&nbsp;&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;t.Start(&nbsp;<span style="color:#a31515;">&quot;Changing&nbsp;material&nbsp;texture&nbsp;path&quot;</span>&nbsp;);

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:blue;">using</span>(&nbsp;<span style="color:#2b91af;">AppearanceAssetEditScope</span>&nbsp;editScope&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=&nbsp;<span style="color:blue;">new</span>&nbsp;<span style="color:#2b91af;">AppearanceAssetEditScope</span>(&nbsp;doc&nbsp;)&nbsp;)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#2b91af;">Asset</span>&nbsp;editableAsset&nbsp;=&nbsp;editScope.Start(&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;mat.AppearanceAssetId&nbsp;);

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:green;">//&nbsp;Getting&nbsp;the&nbsp;correct&nbsp;AssetProperty</span>
<span style="color:blue;">#if</span>&nbsp;VERSION2018
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#2b91af;">AssetProperty</span>&nbsp;assetProperty&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=&nbsp;editableAsset[<span style="color:#a31515;">&quot;generic_diffuse&quot;</span>];
<span style="color:blue;">#elif</span>&nbsp;VERSION2019
<span style="color:gray;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;AssetProperty&nbsp;assetProperty&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=&nbsp;editableAsset.FindByName(&quot;generic_diffuse&quot;);
</span><span style="color:blue;">#endif</span>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#2b91af;">Asset</span>&nbsp;connectedAsset&nbsp;=&nbsp;assetProperty
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.GetConnectedProperty(&nbsp;0&nbsp;)&nbsp;<span style="color:blue;">as</span>&nbsp;<span style="color:#2b91af;">Asset</span>;

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:green;">//&nbsp;Getting&nbsp;the&nbsp;right&nbsp;connected&nbsp;Asset</span>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:blue;">if</span>(&nbsp;connectedAsset.Name&nbsp;==&nbsp;<span style="color:#a31515;">&quot;UnifiedBitmapSchema&quot;</span>&nbsp;)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#2b91af;">AssetPropertyString</span>&nbsp;path&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=&nbsp;connectedAsset.FindByName(&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#2b91af;">UnifiedBitmap</span>.UnifiedbitmapBitmap&nbsp;)&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:blue;">as</span>&nbsp;<span style="color:#2b91af;">AssetPropertyString</span>;

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:blue;">if</span>(&nbsp;path.IsValidValue(&nbsp;texturePath&nbsp;)&nbsp;)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;path.Value&nbsp;=&nbsp;texturePath;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;editScope.Commit(&nbsp;<span style="color:blue;">true</span>&nbsp;);
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#2b91af;">TaskDialog</span>.Show(&nbsp;<span style="color:#a31515;">&quot;Material&nbsp;texture&nbsp;path&quot;</span>,&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#a31515;">&quot;Material&nbsp;texture&nbsp;path&nbsp;changed&nbsp;to:\n&quot;</span>&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;+&nbsp;texturePath&nbsp;);

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;t.Commit();
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;t.Dispose();
&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;}
</pre>

<h4><a name="6"></a> Step by Step Guide</h4>
<p>Here are the steps to reproduce the solution:</p>
<p>Goal:</p>
<ul>
<li>I want to create materials in Revit programmatically, so would not have to create thousands of materials (NCS palette) by hand.</li>
</ul>
<p>That is quite simple with the new Revit 2018.1 API and the sample code provided.</p>
<p>Furthermore, for some materials, I want to change the texture as well, and that was bit of a problem.</p>
<p>Solution:</p>
<ul>
<li>Retrieve the "generic_diffuse" <code>AssetProperty</code> from the asset returned from <code>AppearanceAssetEditScope.Start</code>.</li>
<li>Retrieve the first <code>ConnectedProperty</code> as <code>Asset</code>.</li>
<li>From that, retrieve the <code>UnifiedBitmap.UnifiedbitmapBitmap</code> <code>AssetPropertyString</code>.</li>
<li>Set its value.</li>
</ul>
<p>Guide to reproduce the solution:</p>
<ol>
<li>Open MaterialTexturePath.sln in Visual Studio.</li>
<li>Reload references RevitAPI.dll, RevitAPIUI.dll and RevitAddinUtility.dll from your local folder (usually, where you have Revit installed).</li>
<li>Build the project for the Revit version you want; works only for Revit 2018 and Revit 2019.</li>
<li>Copy contents of the output folder to <em>C:\ProgramData\Autodesk\Revit\Addins\&lt;revit_version&gt;</em>.</li>
<li>Copy the sample texture (new_texture.png file) to your desktop.</li>
<li>Open the sample project.</li>
<li>Go to Manage/Materials and see the texture path in the only present material in the project.</li>
<li>Navigate to the Add-Ins ribbon tab and click the Change texture path button.</li>
<li>Go to Manage/Materials again and note that the texture path changed.</li>
</ol>
<h4><a name="7"></a> Test Run</h4>
<p>Here are screen snapshots illustrating some of the steps from my test run:</p>
<p>Store the sample texture file on desktop:</p>
<p><center>
<img src="img/material_texture_path_texture.png" alt="Sample texture file on desktop" width="88">
</center></p>
<p>Open the sample model and observe the instructions:</p>
<p><center>
<img src="img/material_texture_path_instruction.png" alt="Instructions" width="475">
</center></p>
<p>The sample model contains one single sample material:</p>
<p><center>
<img src="img/material_texture_path_sample.png" alt="Sample material" width="500">
</center></p>
<p>Click the sample command in its custom ribbon panel:</p>
<p><center>
<img src="img/material_texture_path_cmd.png" alt="Ribbon panel and command" width="245">
</center></p>
<p>The add-in displays a message on completion:</p>
<p><center>
<img src="img/material_texture_path_msg.png" alt="Result message" width="372">
</center></p>
<p>The sample material texture is updated:</p>
<p><center>
<img src="img/material_texture_path_sample_updated.png" alt="Updated sample material" width="500">
</center></p>
<p>Many thanks to Luk치코 for his research, putting together and documenting this sample so well!</p>