<p><head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<link rel="stylesheet" type="text/css" href="bc.css">
<script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js" type="text/javascript"></script>
</head></p>
<!---

twitter:

IFC update, access to family instance geometry, parameters, global data and Iranian civil engineering app using the #RevitAPI @AutodeskForge @AutodeskRevit #bim #DynamoBim #ForgeDevCon http://bit.ly/rvtifc201

I completed the move to my new computer, and happily all systems go now.
Here are some other topics that came up in the past few days
&ndash; Revit-IFC Release 20.1.0
&ndash; Community discussion on Revit
&ndash; Solid or instance, depending
&ndash; Exporting parameters to Access
&ndash; Store globals on custom <code>DataStorage</code>, not <code>ProjectInfo</code>
&ndash; Iranian civil engineering project video...

linkedin:

IFC update, access to family instance geometry, parameters, global data and Iranian civil engineering app using the #RevitAPI

http://bit.ly/rvtifc201

I completed the move to my new computer, and happily all systems go now.
Here are some other topics that came up in the past few days:

- Revit-IFC Release 20.1.0
- Community discussion on Revit
- Solid or instance, depending
- Exporting parameters to Access
- Store globals on custom <code>DataStorage</code>, not <code>ProjectInfo</code>
- Iranian civil engineering project video...

#bim #DynamoBim #ForgeDevCon #Revit #API #IFC #SDK #AI #VisualStudio #Autodesk #AEC #adsk

the [Revit API discussion forum](http://forums.autodesk.com/t5/revit-api-forum/bd-p/160) thread

-->

<h3>Changing Pipe Direction</h3>
<p><center>
<img src="img/.png" alt="" width="450">
<p style="font-size: 80%; font-style:italic"></p>
</center></p>
<h4><a name="2"></a> Changing Pipe Direction</h4>
<p>Neerav Mehta shared some important hints on determining precise directions for inserting pipe fittings in
the <a href="http://forums.autodesk.com/t5/revit-api-forum/bd-p/160">Revit API discussion forum</a> thread
on <a href="https://forums.autodesk.com/t5/revit-api-forum/changing-pipe-direction/m-p/8966993">changing pipe direction</a>:</p>
<p><strong>Question:</strong> I am trying to place a pipe precisely between two points: intersectionPoint and intersectionPoint + perpendicularDirection. I am using the following statement to move the pipe:</p>
<p><pre class="code">
Pipe dummyPipe = doc.GetElement(ElementTransformUtils.CopyElement(doc, branchPipe.Id, XYZ.Zero).First()) as Pipe;
(dummyPipe.Location as LocationCurve).Curve = Line.CreateBound(intersectionPoint, intersectionPoint + 1.0 * perpendicularDirection);
</pre></p>
<p>With the above placement, I would expect the pipe's curve's direction to be exactly equal to perpendicularDirection. But that's not the case.</p>
<p>As an example, if perpendicularDirection is set to {(-0.016831296, 0.968685013, -0.052781984)}, the direction of the pipe comes out to be {(-0.017347059, 0.998368562, -0.054399389)}. Note that there is a slight difference in the direction and as a result, I am not able to connect this pipe to a Tee fitting, as described in the thread
on <a href="https://forums.autodesk.com/t5/revit-api-forum/how-to-create-a-tee-fitting-of-not-90-degree-branch-angle-for/td-p/8433556">how to create a tee fitting with a non-90 degree branch angle for pipe</a>.</p>
<p>BTW, the same issue happens even if I create a new pipe between two points.</p>
<p>Any idea how to fix this issue?</p>
<p><strong>Suggestion:</strong> In some cases, you do not need to specify an exact pipe direction to create a pipe between fittings, nor an exact fitting location to insert a fitting between existing pipes.</p>
<p>Revit will automatically adjust the newly created element appropriately to connect with the existing elements.</p>
<p>Different variantions of this approach are explored and discussed in the research series
on <a href="http://thebuildingcoder.typepad.com/blog/2014/01/final-rolling-offset-using-pipecreate.html">creating a rolling offset</a>.</p>
<p><strong>Solution:</strong> The problem in this case, however, was due to inaccuracy in the cross product.</p>
<p>I was deriving the pipe direction by doing two cross-products of unit-norm vectors. In other words:</p>
<pre>
  pipeDirection = X.CrossProduct(Y).CrossProduct(X)
</pre>

<p>Since X and Y are of unit-norm, I was expecting <code>pipeDirection</code> to be unit-norm as well.</p>
<p>However, even if both X and Y are unit length, their cross product will still NOT be unit length unless they are exactly perpendicular, cf.
the <a href="https://en.wikipedia.org/wiki/Cross_product">detailed explanation of the cross product</a>.</p>
<p>Therefore, the length of <code>pipeDirection</code> was about 0.971 instead of 1.0.</p>
<p>Once I normalise <code>pipeDirection</code>, it works fine.</p>
<p>BTW, the rolling offset posts only deal with inserting elbows, which works pretty well.</p>
<p>In my case, I am inserting a T connection, and that API is a horrible mess. Here are the issues:</p>
<ul>
<li><code>CreateTeeFitting</code> works only when the connection is 90 degrees, so you have to use the workaround mentioned in <a href="https://forums.autodesk.com/t5/revit-api-forum/tee-fitting-with-no-right-angle/m-p/8954339">Tee Fitting with no right angle</a>.</li>
<li>The above workaround works only when the base pipe is placed in a way that's acceptable to Revit. As an example, adding a Tee connection works if the two pipes are placed along X axis and the branch pipe is along the Y-axis. But, if I rotate the three pipes slightly, for example by 0.1 degrees, the <code>CreateTeeFitting</code> function fails.</li>
<li>So now I have to use another workaround, creating dummy pipes in a position that Revit likes and a 90 degree T connection. Then delete all the dummy pipes and the fittings that were automatically created, except the T connection. Now rotate the T fitting to what I want, for e.g. by 0.1 degrees. Then change the angle of the branch connector to something other than 90 degrees.</li>
</ul>
<p>This issue along
with <a href="https://forums.autodesk.com/t5/revit-api-forum/tee-fitting-with-no-right-angle/m-p/8954339">line based family location don't update origin after change</a> has
taken me about a week to create a T connection at the right place and orientation instead of probably an hour if the API had worked more intuitively in the first place.</p>
<p>Congratulations and many thanks to Neerav Mehta for this research and solution.</p>
<p>Sorry to hear that the API is so hard to use in this situation. </p>
<h4><a name="3"></a></h4>
<h4><a name="4"></a></h4>
<h4><a name="5"></a></h4>