<p><head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<link rel="stylesheet" type="text/css" href="bc.css">
<script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js" type="text/javascript"></script>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
</head></p>
<!---

- https://thebuildingcoder.typepad.com/blog/2010/05/duplicate-legend-component.html#comment-4752201924

twitter:

 in the #RevitAPI #DynamoBim @AutodeskForge @AutodeskRevit #bim #ForgeDevCon 

&ndash; 
...

linkedin:


#bim #DynamoBim #ForgeDevCon #Revit #API #IFC #SDK #AI #VisualStudio #Autodesk #AEC #adsk

the [Revit API discussion forum](http://forums.autodesk.com/t5/revit-api-forum/bd-p/160) thread

<center>
<img src="img/" alt="" title="" width="100"/>
<p style="font-size: 80%; font-style:italic"></p>
</center>

-->

<h3>Duplicate Legend Component and Lat Long to Metres in Python</h3>
<h4><a name="2"></a>Duplicate Legend Component in Python</h4>
<p>https://thebuildingcoder.typepad.com/blog/2010/05/duplicate-legend-component.html#comment-4752201924</p>
<p>Oliwer Kulpa --&gt; jeremy tammik</p>
<p>Hi Jeremy,</p>
<p>Since it is a part of a Python Script in Dynamo, I'm attaching a code fragment which works on a legend view with one legend component.</p>
<p>I hope it is readable enough for everyone:</p>
<pre class="prettyprint">
  doc = DocumentManager.Instance.CurrentDBDocument
  current_view = doc.ActiveView

  # Get legend component in current view

  existing_legend_component = FilteredElementCollector(
    doc, doc.ActiveView.Id)
      .OfCategory(BuiltInCategory.OST_LegendComponents)
      .FirstElement()

  # Get door family type id

  door_family_type = FilteredElementCollector(doc)
    .OfCategory(BuiltInCategory.OST_Doors)
    .WhereElementIsElementType()
    .FirstElement()

  # Start Transaction
  TransactionManager.Instance.EnsureInTransaction(doc)

  # Copy legend and set new Id to represent new element
  new_legend_component = ElementTransformUtils
    .CopyElement(doc, existing_legend_component.Id,
      XYZ(10, 0,0))

  # Since result of CopyElement is a list of Ids,
  # I need to fetch first element from copied elements

  doc.GetElement(new_legend_component[0])
    .get_Parameter(BuiltInParameter.LEGEND_COMPONENT)
    .Set(door_family_type.Id)

  doc.Regenerate()

  # End Transaction

  TransactionManager.Instance.TransactionTaskDone()
</pre>

<p>Here is a picture with the result:</p>
<p><center>
<img src="img/duplicate_legend_component_window.png" alt="Duplicate legend component" title="Duplicate legend component" width="450"/> <!-- 900 -->
</center></p>
<pre class="code">
</pre>

<p><strong>Response:</strong> You must have misunderstood my question.  I don't have the ViewSheet in order to use the method to get its placed views.  I have a view, that I know is on a sheet (because its sheet number parameter is not null), but I want to get a direct reference to that sheet that it is placed on.  It seems to me that you are still suggesting that I must loop through all ViewSheets to get the View that I'm concerned with.  Thanks.</p>
<p><strong>Answer:</strong> Yes, indeed, that is exactly what I am suggesting.</p>
<h4><a name="3"></a>Convert Latitude and Longitude to Metres in Python</h4>