Find all "class Cmd.* \: IExternalCommand", Regular expressions, Subfolders, Find Results 1, "Entire Solution", "*.cs"
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdAzimuth.cs(25):  class CmdAzimuth : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdBoundingBox.cs(25):  class CmdBoundingBox : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdColumnRound.cs(27):  class CmdColumnRound : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdCoordsOfViewOnSheet.cs(22):  class CmdCoordsOfViewOnSheet : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdCreateSharedParams.cs(27):  class CmdCreateSharedParams : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdCropToRoom.cs(23):  class CmdCropToRoom : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdDetailCurves.cs(19):  class CmdDetailCurves : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdDisallowJoin.cs(24):  class CmdDisallowJoin : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdEditFloor.cs(24):  class CmdEditFloor : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdEllipticalArc.cs(18):  class CmdEllipticalArc : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdFamilyParamValue.cs(25):  class CmdFamilyParamValue : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdFilterPerformance.cs(28):  class CmdFilterPerformance : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdGetMaterials.cs(27):  class CmdGetMaterials : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdImportsInFamilies.cs(24):  class CmdImportsInFamilies : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdInstallLocation.cs(22):  class CmdInstallLocation : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdLandXml.cs(23):  class CmdLandXml : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdLibraryPaths.cs(20):  class CmdLibraryPaths : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdLinkedFileElements.cs(84):  class CmdLinkedFileElements : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdLinkedFiles.cs(24):  class CmdLinkedFiles : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdLinq.cs(23):  class CmdLinq : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdListMarks.cs(22):  class CmdListMarks : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdListRailingTypes.cs(29):  class CmdListRailingTypes : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdListSharedParams.cs(24):  class CmdListSharedParams : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdListViews.cs(24):  class CmdListViews : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdListWalls.cs(12):  public class CmdListWalls : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdMirror.cs(21):  class CmdMirror : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdMirror.cs(42):  class CmdMirrorListAdded : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdNestedFamilies.cs(429):  class CmdNestedFamilies : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdNestedInstanceGeo.cs(27):  class CmdNestedInstanceGeo : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdNewArea.cs(25):  class CmdNewArea : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdNewBeamTypeInstance.cs(27):  class CmdNewBeamTypeInstance : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdNewColumnTypeInstance.cs(26):  class CmdNewColumnTypeInstance : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdNewDimensionLabel.cs(22):  class CmdNewDimensionLabel : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdNewLightingFixture.cs(23):  class CmdNewLightingFixture : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdNewLineLoad.cs(32):  class CmdNewLineLoad : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdNewProjectDoc.cs(24):  class CmdNewProjectDoc : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdNewRailing.cs(35):  class CmdNewRailing : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdNewSpotElevation.cs(20):  class CmdNewSpotElevation : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdNewSprinkler.cs(26):  class CmdNewSprinkler : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdNewWallLayer.cs(24):  class CmdNewWallLayer : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdOmniClassParams.cs(27):  class CmdOmniClassParams : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdPlanTopology.cs(23):  class CmdPlanTopology : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdRectDuctCorners.cs(26):  class CmdRectDuctCorners : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdRelationshipInverter.cs(27):  public class CmdRelationshipInverter : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdRoomWallAdjacency.cs(28):  class CmdRoomWallAdjacency : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdRotatedBeamLocation.cs(32):  class CmdRotatedBeamLocation : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdSetRoomOccupancy.cs(24):  class CmdSetRoomOccupancy : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdSlabBoundary.cs(24):  class CmdSlabBoundary : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdSlabBoundaryArea.cs(24):  class CmdSlabBoundaryArea : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdSlabSides.cs(24):  class CmdSlabSides : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdSlopedWall.cs(23):  class CmdSlopedWall : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdSpaceAdjacency.cs(25):  public class CmdSpaceAdjacency : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdTransformedCoords.cs(29):  class CmdTransformedCoords : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdUnrotateNorth.cs(22):  class CmdUnrotateNorth : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdWallBottomFace.cs(22):  class CmdWallBottomFace : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdWallDimensions.cs(38):  public class CmdWallDimensions : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdWallFooting.cs(22):  class CmdWallFooting : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdWallLayers.cs(28):  class CmdWallLayers : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdWallLayerVolumes.cs(26):  class CmdWallLayerVolumes : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdWallNeighbours.cs(22):  class CmdWallNeighbours : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdWallProfile.cs(26):  class CmdWallProfile : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdWallProfileArea.cs(26):  class CmdWallProfileArea : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdWindowHandle.cs(47):  class CmdWindowHandle : IExternalCommand
  Matching lines: 63    Matching files: 62    Total files searched: 71

Find all "\::b+IExternalCommand", Regular expressions, Subfolders, Find Results 1, "Entire Solution", "*.cs"
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdAzimuth.cs(25):  class CmdAzimuth : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdBoundingBox.cs(25):  class CmdBoundingBox : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdColumnRound.cs(27):  class CmdColumnRound : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdCoordsOfViewOnSheet.cs(22):  class CmdCoordsOfViewOnSheet : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdCreateSharedParams.cs(27):  class CmdCreateSharedParams : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdCropToRoom.cs(23):  class CmdCropToRoom : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdDetailCurves.cs(19):  class CmdDetailCurves : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdDisallowJoin.cs(24):  class CmdDisallowJoin : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdEditFloor.cs(24):  class CmdEditFloor : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdEllipticalArc.cs(18):  class CmdEllipticalArc : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdFamilyParamValue.cs(25):  class CmdFamilyParamValue : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdFilterPerformance.cs(28):  class CmdFilterPerformance : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdGetMaterials.cs(27):  class CmdGetMaterials : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdImportsInFamilies.cs(24):  class CmdImportsInFamilies : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdInstallLocation.cs(22):  class CmdInstallLocation : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdLandXml.cs(23):  class CmdLandXml : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdLibraryPaths.cs(20):  class CmdLibraryPaths : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdLinkedFileElements.cs(84):  class CmdLinkedFileElements : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdLinkedFiles.cs(24):  class CmdLinkedFiles : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdLinq.cs(23):  class CmdLinq : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdListMarks.cs(22):  class CmdListMarks : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdListRailingTypes.cs(29):  class CmdListRailingTypes : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdListSharedParams.cs(24):  class CmdListSharedParams : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdListViews.cs(24):  class CmdListViews : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdListWalls.cs(12):  public class CmdListWalls : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdMirror.cs(21):  class CmdMirror : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdMirror.cs(42):  class CmdMirrorListAdded : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdNestedFamilies.cs(429):  class CmdNestedFamilies : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdNestedInstanceGeo.cs(27):  class CmdNestedInstanceGeo : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdNewArea.cs(25):  class CmdNewArea : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdNewBeamTypeInstance.cs(27):  class CmdNewBeamTypeInstance : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdNewColumnTypeInstance.cs(26):  class CmdNewColumnTypeInstance : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdNewDimensionLabel.cs(22):  class CmdNewDimensionLabel : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdNewLightingFixture.cs(23):  class CmdNewLightingFixture : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdNewLineLoad.cs(32):  class CmdNewLineLoad : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdNewProjectDoc.cs(24):  class CmdNewProjectDoc : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdNewRailing.cs(35):  class CmdNewRailing : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdNewSpotElevation.cs(20):  class CmdNewSpotElevation : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdNewSprinkler.cs(26):  class CmdNewSprinkler : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdNewWallLayer.cs(24):  class CmdNewWallLayer : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdOmniClassParams.cs(27):  class CmdOmniClassParams : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdPlanTopology.cs(23):  class CmdPlanTopology : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdRectDuctCorners.cs(26):  class CmdRectDuctCorners : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdRelationshipInverter.cs(27):  public class CmdRelationshipInverter : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdRoomWallAdjacency.cs(28):  class CmdRoomWallAdjacency : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdRotatedBeamLocation.cs(32):  class CmdRotatedBeamLocation : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdSetRoomOccupancy.cs(24):  class CmdSetRoomOccupancy : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdSlabBoundary.cs(24):  class CmdSlabBoundary : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdSlabBoundaryArea.cs(24):  class CmdSlabBoundaryArea : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdSlabSides.cs(24):  class CmdSlabSides : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdSlopedWall.cs(23):  class CmdSlopedWall : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdSpaceAdjacency.cs(25):  public class CmdSpaceAdjacency : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdTransformedCoords.cs(29):  class CmdTransformedCoords : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdUnrotateNorth.cs(22):  class CmdUnrotateNorth : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdWallBottomFace.cs(22):  class CmdWallBottomFace : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdWallDimensions.cs(38):  public class CmdWallDimensions : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdWallFooting.cs(22):  class CmdWallFooting : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdWallLayers.cs(28):  class CmdWallLayers : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdWallLayerVolumes.cs(26):  class CmdWallLayerVolumes : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdWallNeighbours.cs(22):  class CmdWallNeighbours : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdWallProfile.cs(26):  class CmdWallProfile : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdWallProfileArea.cs(26):  class CmdWallProfileArea : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdWindowHandle.cs(47):  class CmdWindowHandle : IExternalCommand
  Matching lines: 63    Matching files: 62    Total files searched: 71

Find all "IExternalCommand", Match case, Whole word, Subfolders, Find Results 1, "Entire Solution", "*.cs"
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdAzimuth.cs(19):  = Autodesk.Revit.IExternalCommand.Result;
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdAzimuth.cs(25):  class CmdAzimuth : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdBoundingBox.cs(17):  = Autodesk.Revit.IExternalCommand.Result;
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdBoundingBox.cs(25):  class CmdBoundingBox : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdColumnRound.cs(22):  = Autodesk.Revit.IExternalCommand.Result;
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdColumnRound.cs(27):  class CmdColumnRound : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdCoordsOfViewOnSheet.cs(17):  = Autodesk.Revit.IExternalCommand.Result;
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdCoordsOfViewOnSheet.cs(22):  class CmdCoordsOfViewOnSheet : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdCreateSharedParams.cs(22):  = Autodesk.Revit.IExternalCommand.Result;
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdCreateSharedParams.cs(27):  class CmdCreateSharedParams : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdCropToRoom.cs(16):using CmdResult = Autodesk.Revit.IExternalCommand.Result;
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdCropToRoom.cs(23):  class CmdCropToRoom : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdDetailCurves.cs(14):using CmdResult = Autodesk.Revit.IExternalCommand.Result;
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdDetailCurves.cs(19):  class CmdDetailCurves : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdDisallowJoin.cs(16):using CmdResult = Autodesk.Revit.IExternalCommand.Result;
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdDisallowJoin.cs(24):  class CmdDisallowJoin : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdEditFloor.cs(19):using CmdResult = Autodesk.Revit.IExternalCommand.Result;
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdEditFloor.cs(24):  class CmdEditFloor : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdEllipticalArc.cs(13):using CmdResult = Autodesk.Revit.IExternalCommand.Result;
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdEllipticalArc.cs(18):  class CmdEllipticalArc : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdFamilyParamValue.cs(20):  = Autodesk.Revit.IExternalCommand.Result;
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdFamilyParamValue.cs(25):  class CmdFamilyParamValue : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdFamilyParamValue.cs(61):    public IExternalCommand.Result Execute(
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdFamilyParamValue.cs(170):      return IExternalCommand.Result.Failed;
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdFilterPerformance.cs(23):  = Autodesk.Revit.IExternalCommand.Result;
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdFilterPerformance.cs(28):  class CmdFilterPerformance : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdGetMaterials.cs(19):using CmdResult = Autodesk.Revit.IExternalCommand.Result;
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdGetMaterials.cs(27):  class CmdGetMaterials : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdImportsInFamilies.cs(19):  = Autodesk.Revit.IExternalCommand.Result;
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdImportsInFamilies.cs(24):  class CmdImportsInFamilies : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdInstallLocation.cs(17):using CmdResult = Autodesk.Revit.IExternalCommand.Result;
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdInstallLocation.cs(22):  class CmdInstallLocation : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdLandXml.cs(17):using CmdResult = Autodesk.Revit.IExternalCommand.Result;
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdLandXml.cs(23):  class CmdLandXml : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdLibraryPaths.cs(15):using CmdResult = Autodesk.Revit.IExternalCommand.Result;
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdLibraryPaths.cs(20):  class CmdLibraryPaths : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdLinkedFileElements.cs(19):  = Autodesk.Revit.IExternalCommand.Result;
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdLinkedFileElements.cs(84):  class CmdLinkedFileElements : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdLinkedFiles.cs(19):  = Autodesk.Revit.IExternalCommand.Result;
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdLinkedFiles.cs(24):  class CmdLinkedFiles : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdLinq.cs(16):using CmdResult = Autodesk.Revit.IExternalCommand.Result;
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdLinq.cs(23):  class CmdLinq : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdListMarks.cs(17):using CmdResult = Autodesk.Revit.IExternalCommand.Result;
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdListMarks.cs(22):  class CmdListMarks : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdListRailingTypes.cs(22):  = Autodesk.Revit.IExternalCommand.Result;
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdListRailingTypes.cs(29):  class CmdListRailingTypes : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdListRailingTypes.cs(32):    public IExternalCommand.Result Execute2(
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdListRailingTypes.cs(56):      return IExternalCommand.Result.Succeeded;
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdListSharedParams.cs(19):  = Autodesk.Revit.IExternalCommand.Result;
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdListSharedParams.cs(24):  class CmdListSharedParams : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdListViews.cs(19):  = Autodesk.Revit.IExternalCommand.Result;
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdListViews.cs(24):  class CmdListViews : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdListWalls.cs(7):using CmdResult = Autodesk.Revit.IExternalCommand.Result;
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdListWalls.cs(12):  public class CmdListWalls : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdMirror.cs(16):using CmdResult = Autodesk.Revit.IExternalCommand.Result;
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdMirror.cs(21):  class CmdMirror : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdMirror.cs(42):  class CmdMirrorListAdded : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdNestedFamilies.cs(16):using CmdResult = Autodesk.Revit.IExternalCommand.Result;
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdNestedFamilies.cs(429):  class CmdNestedFamilies : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdNestedInstanceGeo.cs(19):  = Autodesk.Revit.IExternalCommand.Result;
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdNestedInstanceGeo.cs(27):  class CmdNestedInstanceGeo : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdNewArea.cs(18):  = Autodesk.Revit.IExternalCommand.Result;
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdNewArea.cs(25):  class CmdNewArea : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdNewBeamTypeInstance.cs(20):  = Autodesk.Revit.IExternalCommand.Result;
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdNewBeamTypeInstance.cs(27):  class CmdNewBeamTypeInstance : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdNewColumnTypeInstance.cs(20):  = Autodesk.Revit.IExternalCommand.Result;
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdNewColumnTypeInstance.cs(26):  class CmdNewColumnTypeInstance : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdNewDimensionLabel.cs(16):using CmdResult = Autodesk.Revit.IExternalCommand.Result;
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdNewDimensionLabel.cs(22):  class CmdNewDimensionLabel : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdNewLightingFixture.cs(17):using CmdResult = Autodesk.Revit.IExternalCommand.Result;
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdNewLightingFixture.cs(23):  class CmdNewLightingFixture : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdNewLineLoad.cs(24):using CmdResult = Autodesk.Revit.IExternalCommand.Result;
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdNewLineLoad.cs(32):  class CmdNewLineLoad : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdNewProjectDoc.cs(19):  = Autodesk.Revit.IExternalCommand.Result;
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdNewProjectDoc.cs(24):  class CmdNewProjectDoc : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdNewProjectDoc.cs(31):    public IExternalCommand.Result Execute(
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdNewRailing.cs(21):  = Autodesk.Revit.IExternalCommand.Result;
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdNewRailing.cs(35):  class CmdNewRailing : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdNewSpotElevation.cs(14):using CmdResult = Autodesk.Revit.IExternalCommand.Result;
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdNewSpotElevation.cs(20):  class CmdNewSpotElevation : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdNewSprinkler.cs(19):using CmdResult = Autodesk.Revit.IExternalCommand.Result;
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdNewSprinkler.cs(26):  class CmdNewSprinkler : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdNewSweptBlend.cs(14):using CmdResult = Autodesk.Revit.IExternalCommand.Result;
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdNewWallLayer.cs(19):  = Autodesk.Revit.IExternalCommand.Result;
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdNewWallLayer.cs(24):  class CmdNewWallLayer : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdOmniClassParams.cs(21):  = Autodesk.Revit.IExternalCommand.Result;
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdOmniClassParams.cs(27):  class CmdOmniClassParams : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdOmniClassParams.cs(67):      return IExternalCommand.Result.Failed;
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdPlanTopology.cs(18):  = Autodesk.Revit.IExternalCommand.Result;
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdPlanTopology.cs(23):  class CmdPlanTopology : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdRectDuctCorners.cs(20):using CmdResult = Autodesk.Revit.IExternalCommand.Result;
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdRectDuctCorners.cs(26):  class CmdRectDuctCorners : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdRelationshipInverter.cs(22):  = Autodesk.Revit.IExternalCommand.Result;
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdRelationshipInverter.cs(27):  public class CmdRelationshipInverter : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdRoomWallAdjacency.cs(19):using CmdResult = Autodesk.Revit.IExternalCommand.Result;
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdRoomWallAdjacency.cs(28):  class CmdRoomWallAdjacency : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdRotatedBeamLocation.cs(24):using CmdResult = Autodesk.Revit.IExternalCommand.Result;
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdRotatedBeamLocation.cs(32):  class CmdRotatedBeamLocation : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdSetRoomOccupancy.cs(19):  = Autodesk.Revit.IExternalCommand.Result;
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdSetRoomOccupancy.cs(24):  class CmdSetRoomOccupancy : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdSlabBoundary.cs(19):using CmdResult = Autodesk.Revit.IExternalCommand.Result;
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdSlabBoundary.cs(24):  class CmdSlabBoundary : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdSlabBoundaryArea.cs(17):using CmdResult = Autodesk.Revit.IExternalCommand.Result;
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdSlabBoundaryArea.cs(24):  class CmdSlabBoundaryArea : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdSlabSides.cs(19):using CmdResult = Autodesk.Revit.IExternalCommand.Result;
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdSlabSides.cs(24):  class CmdSlabSides : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdSlopedWall.cs(18):  = Autodesk.Revit.IExternalCommand.Result;
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdSlopedWall.cs(23):  class CmdSlopedWall : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdSpaceAdjacency.cs(17):using CmdResult = Autodesk.Revit.IExternalCommand.Result;
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdSpaceAdjacency.cs(25):  public class CmdSpaceAdjacency : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdTransformedCoords.cs(24):  = Autodesk.Revit.IExternalCommand.Result;
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdTransformedCoords.cs(29):  class CmdTransformedCoords : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdUnrotateNorth.cs(22):  class CmdUnrotateNorth : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdUnrotateNorth.cs(62):    public IExternalCommand.Result Execute(
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdUnrotateNorth.cs(132):      return IExternalCommand.Result.Failed;
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdWallBottomFace.cs(17):using CmdResult = Autodesk.Revit.IExternalCommand.Result;
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdWallBottomFace.cs(22):  class CmdWallBottomFace : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdWallDimensions.cs(18):using CmdResult = Autodesk.Revit.IExternalCommand.Result;
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdWallDimensions.cs(38):  public class CmdWallDimensions : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdWallFooting.cs(17):  = Autodesk.Revit.IExternalCommand.Result;
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdWallFooting.cs(22):  class CmdWallFooting : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdWallLayers.cs(23):  = Autodesk.Revit.IExternalCommand.Result;
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdWallLayers.cs(28):  class CmdWallLayers : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdWallLayerVolumes.cs(21):  = Autodesk.Revit.IExternalCommand.Result;
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdWallLayerVolumes.cs(26):  class CmdWallLayerVolumes : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdWallNeighbours.cs(17):  = Autodesk.Revit.IExternalCommand.Result;
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdWallNeighbours.cs(22):  class CmdWallNeighbours : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdWallProfile.cs(21):  = Autodesk.Revit.IExternalCommand.Result;
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdWallProfile.cs(26):  class CmdWallProfile : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdWallProfileArea.cs(21):  = Autodesk.Revit.IExternalCommand.Result;
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdWallProfileArea.cs(26):  class CmdWallProfileArea : IExternalCommand
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdWindowHandle.cs(16):  = Autodesk.Revit.IExternalCommand.Result;
  C:\a\j\adn\train\revit\2010\src\bc\BuildingCoder\BuildingCoder\CmdWindowHandle.cs(47):  class CmdWindowHandle : IExternalCommand
  Matching lines: 133    Matching files: 63    Total files searched: 71
