------ Rebuild All started: Project: IntroCs, Configuration: Debug Any CPU ------
Z:\a\lib\revit\2014\adn\src\lab\1_Revit_API_Intro\SourceCS\2_DbElement.cs(368,59): warning CS0618: 'Autodesk.Revit.DB.Curve.get_EndPoint(int)' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'
Z:\a\lib\revit\2014\adn\src\lab\1_Revit_API_Intro\SourceCS\2_DbElement.cs(369,57): warning CS0618: 'Autodesk.Revit.DB.Curve.get_EndPoint(int)' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'
Z:\a\lib\revit\2014\adn\src\lab\1_Revit_API_Intro\SourceCS\4_ElementModification.cs(172,17): warning CS0618: 'Autodesk.Revit.DB.Curve.get_EndPoint(int)' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'
Z:\a\lib\revit\2014\adn\src\lab\1_Revit_API_Intro\SourceCS\4_ElementModification.cs(173,17): warning CS0618: 'Autodesk.Revit.DB.Curve.get_EndPoint(int)' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'
Z:\a\lib\revit\2014\adn\src\lab\1_Revit_API_Intro\SourceCS\4_ElementModification.cs(181,26): warning CS0618: 'Autodesk.Revit.Creation.Application.NewLineBound(Autodesk.Revit.DB.XYZ, Autodesk.Revit.DB.XYZ)' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() instead.'
Z:\a\lib\revit\2014\adn\src\lab\1_Revit_API_Intro\SourceCS\4_ElementModification.cs(259,19): warning CS0618: 'Autodesk.Revit.Creation.Application.NewLineBound(Autodesk.Revit.DB.XYZ, Autodesk.Revit.DB.XYZ)' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() instead.'
Z:\a\lib\revit\2014\adn\src\lab\1_Revit_API_Intro\SourceCS\5_ModelCreation.cs(147,26): warning CS0618: 'Autodesk.Revit.Creation.Application.NewLineBound(Autodesk.Revit.DB.XYZ, Autodesk.Revit.DB.XYZ)' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() instead.'
Z:\a\lib\revit\2014\adn\src\lab\1_Revit_API_Intro\SourceCS\5_ModelCreation.cs(194,17): warning CS0618: 'Autodesk.Revit.DB.Curve.get_EndPoint(int)' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'
Z:\a\lib\revit\2014\adn\src\lab\1_Revit_API_Intro\SourceCS\5_ModelCreation.cs(195,17): warning CS0618: 'Autodesk.Revit.DB.Curve.get_EndPoint(int)' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'
Z:\a\lib\revit\2014\adn\src\lab\1_Revit_API_Intro\SourceCS\5_ModelCreation.cs(244,17): warning CS0618: 'Autodesk.Revit.DB.Curve.get_EndPoint(int)' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'
Z:\a\lib\revit\2014\adn\src\lab\1_Revit_API_Intro\SourceCS\5_ModelCreation.cs(245,17): warning CS0618: 'Autodesk.Revit.DB.Curve.get_EndPoint(int)' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'
Z:\a\lib\revit\2014\adn\src\lab\1_Revit_API_Intro\SourceCS\5_ModelCreation.cs(309,19): warning CS0618: 'Autodesk.Revit.DB.Curve.get_EndPoint(int)' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'
Z:\a\lib\revit\2014\adn\src\lab\1_Revit_API_Intro\SourceCS\5_ModelCreation.cs(310,19): warning CS0618: 'Autodesk.Revit.DB.Curve.get_EndPoint(int)' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'
Z:\a\lib\revit\2014\adn\src\lab\1_Revit_API_Intro\SourceCS\5_ModelCreation.cs(311,21): warning CS0618: 'Autodesk.Revit.Creation.Application.NewLineBound(Autodesk.Revit.DB.XYZ, Autodesk.Revit.DB.XYZ)' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() instead.'
Z:\a\lib\revit\2014\adn\src\lab\1_Revit_API_Intro\SourceCS\3_ElementFiltering.cs(109,31): warning CS0618: 'Autodesk.Revit.DB.Document.WallTypes' is obsolete: 'This method is obsolete in Revit 2014. Use FilteredElementCollector with an appropriate class filter instead.'
Z:\a\lib\revit\2014\adn\src\lab\1_Revit_API_Intro\SourceCS\3_ElementFiltering.cs(123,33): warning CS0618: 'Autodesk.Revit.DB.Document.FloorTypes' is obsolete: 'This method is obsolete in Revit 2014. Use FilteredElementCollector with an appropriate class filter instead.'
Z:\a\lib\revit\2014\adn\src\lab\1_Revit_API_Intro\SourceCS\5_ModelCreationExport.cs(166,26): warning CS0618: 'Autodesk.Revit.Creation.Application.NewLineBound(Autodesk.Revit.DB.XYZ, Autodesk.Revit.DB.XYZ)' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() instead.'
Z:\a\lib\revit\2014\adn\src\lab\1_Revit_API_Intro\SourceCS\5_ModelCreationExport.cs(260,26): warning CS0618: 'Autodesk.Revit.Creation.Application.NewLineBound(Autodesk.Revit.DB.XYZ, Autodesk.Revit.DB.XYZ)' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() instead.'
Z:\a\lib\revit\2014\adn\src\lab\1_Revit_API_Intro\SourceCS\5_ModelCreationExport.cs(305,17): warning CS0618: 'Autodesk.Revit.DB.Curve.get_EndPoint(int)' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'
Z:\a\lib\revit\2014\adn\src\lab\1_Revit_API_Intro\SourceCS\5_ModelCreationExport.cs(306,17): warning CS0618: 'Autodesk.Revit.DB.Curve.get_EndPoint(int)' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'
Z:\a\lib\revit\2014\adn\src\lab\1_Revit_API_Intro\SourceCS\5_ModelCreationExport.cs(349,17): warning CS0618: 'Autodesk.Revit.DB.Curve.get_EndPoint(int)' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'
Z:\a\lib\revit\2014\adn\src\lab\1_Revit_API_Intro\SourceCS\5_ModelCreationExport.cs(350,17): warning CS0618: 'Autodesk.Revit.DB.Curve.get_EndPoint(int)' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'
Z:\a\lib\revit\2014\adn\src\lab\1_Revit_API_Intro\SourceCS\5_ModelCreationExport.cs(412,19): warning CS0618: 'Autodesk.Revit.DB.Curve.get_EndPoint(int)' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'
Z:\a\lib\revit\2014\adn\src\lab\1_Revit_API_Intro\SourceCS\5_ModelCreationExport.cs(413,19): warning CS0618: 'Autodesk.Revit.DB.Curve.get_EndPoint(int)' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'
Z:\a\lib\revit\2014\adn\src\lab\1_Revit_API_Intro\SourceCS\5_ModelCreationExport.cs(414,21): warning CS0618: 'Autodesk.Revit.Creation.Application.NewLineBound(Autodesk.Revit.DB.XYZ, Autodesk.Revit.DB.XYZ)' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() instead.'

Compile complete -- 0 errors, 25 warnings
C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(1578,5): warning MSB3270: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "RevitAPI, Version=2012.0.0.0, Culture=neutral, processorArchitecture=x86", "AMD64". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.
C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(1578,5): warning MSB3270: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "RevitAPIUI, Version=2012.0.0.0, Culture=neutral, processorArchitecture=x86", "AMD64". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.
  IntroCs -> Z:\a\lib\revit\2014\adn\src\lab\1_Revit_API_Intro\SourceCS\bin\Debug\IntroCs.dll
------ Rebuild All started: Project: IntroVb, Configuration: Debug Any CPU ------
Z:\a\lib\revit\2014\adn\src\lab\1_Revit_API_Intro\SourceVB\2_DbElement.vb(350) : warning BC40000: 'Public ReadOnly Property EndPoint(index As Integer) As Autodesk.Revit.DB.XYZ' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'.
Z:\a\lib\revit\2014\adn\src\lab\1_Revit_API_Intro\SourceVB\2_DbElement.vb(351) : warning BC40000: 'Public ReadOnly Property EndPoint(index As Integer) As Autodesk.Revit.DB.XYZ' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'.
Z:\a\lib\revit\2014\adn\src\lab\1_Revit_API_Intro\SourceVB\3_ElementFiltering.vb(104) : warning BC40000: 'Public ReadOnly Property WallTypes As Autodesk.Revit.DB.WallTypeSet' is obsolete: 'This method is obsolete in Revit 2014. Use FilteredElementCollector with an appropriate class filter instead.'.
Z:\a\lib\revit\2014\adn\src\lab\1_Revit_API_Intro\SourceVB\3_ElementFiltering.vb(116) : warning BC40000: 'Public ReadOnly Property FloorTypes As Autodesk.Revit.DB.FloorTypeSet' is obsolete: 'This method is obsolete in Revit 2014. Use FilteredElementCollector with an appropriate class filter instead.'.
Z:\a\lib\revit\2014\adn\src\lab\1_Revit_API_Intro\SourceVB\4_ElementModification.vb(177) : warning BC40000: 'Public ReadOnly Property EndPoint(index As Integer) As Autodesk.Revit.DB.XYZ' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'.
Z:\a\lib\revit\2014\adn\src\lab\1_Revit_API_Intro\SourceVB\4_ElementModification.vb(178) : warning BC40000: 'Public ReadOnly Property EndPoint(index As Integer) As Autodesk.Revit.DB.XYZ' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'.
Z:\a\lib\revit\2014\adn\src\lab\1_Revit_API_Intro\SourceVB\4_ElementModification.vb(186) : warning BC40000: 'Public Function NewLineBound(start As Autodesk.Revit.DB.XYZ, end As Autodesk.Revit.DB.XYZ) As Autodesk.Revit.DB.Line' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() instead.'.
Z:\a\lib\revit\2014\adn\src\lab\1_Revit_API_Intro\SourceVB\4_ElementModification.vb(262) : warning BC40000: 'Public Function NewLineBound(start As Autodesk.Revit.DB.XYZ, end As Autodesk.Revit.DB.XYZ) As Autodesk.Revit.DB.Line' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() instead.'.
Z:\a\lib\revit\2014\adn\src\lab\1_Revit_API_Intro\SourceVB\5_ModelCreation.vb(148) : warning BC40000: 'Public Function NewLineBound(start As Autodesk.Revit.DB.XYZ, end As Autodesk.Revit.DB.XYZ) As Autodesk.Revit.DB.Line' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() instead.'.
Z:\a\lib\revit\2014\adn\src\lab\1_Revit_API_Intro\SourceVB\5_ModelCreation.vb(194) : warning BC40000: 'Public ReadOnly Property EndPoint(index As Integer) As Autodesk.Revit.DB.XYZ' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'.
Z:\a\lib\revit\2014\adn\src\lab\1_Revit_API_Intro\SourceVB\5_ModelCreation.vb(195) : warning BC40000: 'Public ReadOnly Property EndPoint(index As Integer) As Autodesk.Revit.DB.XYZ' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'.
Z:\a\lib\revit\2014\adn\src\lab\1_Revit_API_Intro\SourceVB\5_ModelCreation.vb(246) : warning BC40000: 'Public ReadOnly Property EndPoint(index As Integer) As Autodesk.Revit.DB.XYZ' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'.
Z:\a\lib\revit\2014\adn\src\lab\1_Revit_API_Intro\SourceVB\5_ModelCreation.vb(247) : warning BC40000: 'Public ReadOnly Property EndPoint(index As Integer) As Autodesk.Revit.DB.XYZ' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'.
Z:\a\lib\revit\2014\adn\src\lab\1_Revit_API_Intro\SourceVB\5_ModelCreation.vb(314) : warning BC40000: 'Public ReadOnly Property EndPoint(index As Integer) As Autodesk.Revit.DB.XYZ' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'.
Z:\a\lib\revit\2014\adn\src\lab\1_Revit_API_Intro\SourceVB\5_ModelCreation.vb(315) : warning BC40000: 'Public ReadOnly Property EndPoint(index As Integer) As Autodesk.Revit.DB.XYZ' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'.
Z:\a\lib\revit\2014\adn\src\lab\1_Revit_API_Intro\SourceVB\5_ModelCreation.vb(316) : warning BC40000: 'Public Function NewLineBound(start As Autodesk.Revit.DB.XYZ, end As Autodesk.Revit.DB.XYZ) As Autodesk.Revit.DB.Line' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() instead.'.
Z:\a\lib\revit\2014\adn\src\lab\1_Revit_API_Intro\SourceVB\5_ModelCreationExport.vb(171) : warning BC40000: 'Public Function NewLineBound(start As Autodesk.Revit.DB.XYZ, end As Autodesk.Revit.DB.XYZ) As Autodesk.Revit.DB.Line' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() instead.'.
Z:\a\lib\revit\2014\adn\src\lab\1_Revit_API_Intro\SourceVB\5_ModelCreationExport.vb(254) : warning BC40000: 'Public Function NewLineBound(start As Autodesk.Revit.DB.XYZ, end As Autodesk.Revit.DB.XYZ) As Autodesk.Revit.DB.Line' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() instead.'.
Z:\a\lib\revit\2014\adn\src\lab\1_Revit_API_Intro\SourceVB\5_ModelCreationExport.vb(293) : warning BC40000: 'Public ReadOnly Property EndPoint(index As Integer) As Autodesk.Revit.DB.XYZ' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'.
Z:\a\lib\revit\2014\adn\src\lab\1_Revit_API_Intro\SourceVB\5_ModelCreationExport.vb(294) : warning BC40000: 'Public ReadOnly Property EndPoint(index As Integer) As Autodesk.Revit.DB.XYZ' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'.
Z:\a\lib\revit\2014\adn\src\lab\1_Revit_API_Intro\SourceVB\5_ModelCreationExport.vb(333) : warning BC40000: 'Public ReadOnly Property EndPoint(index As Integer) As Autodesk.Revit.DB.XYZ' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'.
Z:\a\lib\revit\2014\adn\src\lab\1_Revit_API_Intro\SourceVB\5_ModelCreationExport.vb(334) : warning BC40000: 'Public ReadOnly Property EndPoint(index As Integer) As Autodesk.Revit.DB.XYZ' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'.
Z:\a\lib\revit\2014\adn\src\lab\1_Revit_API_Intro\SourceVB\5_ModelCreationExport.vb(391) : warning BC40000: 'Public ReadOnly Property EndPoint(index As Integer) As Autodesk.Revit.DB.XYZ' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'.
Z:\a\lib\revit\2014\adn\src\lab\1_Revit_API_Intro\SourceVB\5_ModelCreationExport.vb(392) : warning BC40000: 'Public ReadOnly Property EndPoint(index As Integer) As Autodesk.Revit.DB.XYZ' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'.
Z:\a\lib\revit\2014\adn\src\lab\1_Revit_API_Intro\SourceVB\5_ModelCreationExport.vb(393) : warning BC40000: 'Public Function NewLineBound(start As Autodesk.Revit.DB.XYZ, end As Autodesk.Revit.DB.XYZ) As Autodesk.Revit.DB.Line' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() instead.'.
C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(1578,5): warning MSB3270: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "RevitAPI, Version=2012.0.0.0, Culture=neutral, processorArchitecture=x86", "AMD64". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.
C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(1578,5): warning MSB3270: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "RevitAPIUI, Version=2012.0.0.0, Culture=neutral, processorArchitecture=x86", "AMD64". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.
  IntroVb -> Z:\a\lib\revit\2014\adn\src\lab\1_Revit_API_Intro\SourceVB\bin\Debug\IntroVb.dll
------ Rebuild All started: Project: UiCs, Configuration: Debug Any CPU ------
C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(1578,5): warning MSB3270: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "RevitAPI, Version=2012.0.0.0, Culture=neutral, processorArchitecture=x86", "AMD64". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.
C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(1578,5): warning MSB3270: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "RevitAPIUI, Version=2012.0.0.0, Culture=neutral, processorArchitecture=x86", "AMD64". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.
  UiCs -> Z:\a\lib\revit\2014\adn\src\lab\2_Revit_UI_API\SourceCS\bin\Debug\UiCs.dll
------ Rebuild All started: Project: FamilyVb, Configuration: Debug Any CPU ------
Z:\a\lib\revit\2014\adn\src\lab\3_Revit_Family_API\SourceVB\1_ColumnRectangle.vb(245) : warning BC40000: 'Public Function NewLineBound(start As Autodesk.Revit.DB.XYZ, end As Autodesk.Revit.DB.XYZ) As Autodesk.Revit.DB.Line' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() instead.'.
Z:\a\lib\revit\2014\adn\src\lab\3_Revit_Family_API\SourceVB\2_ColumnLshape.vb(261) : warning BC40000: 'Public Function NewSketchPlane(geometryPlane As Autodesk.Revit.DB.Plane) As Autodesk.Revit.DB.SketchPlane' is obsolete: 'This method is obsolete in Revit 2014. Use SketchPlane.Create() instead. To create a reference relationship between the sketch plane and geometry, use the overload with a Reference input.'.
Z:\a\lib\revit\2014\adn\src\lab\3_Revit_Family_API\SourceVB\2_ColumnLshape.vb(319) : warning BC40000: 'Public Function NewLineBound(start As Autodesk.Revit.DB.XYZ, end As Autodesk.Revit.DB.XYZ) As Autodesk.Revit.DB.Line' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() instead.'.
Z:\a\lib\revit\2014\adn\src\lab\3_Revit_Family_API\SourceVB\2_ColumnLshape.vb(366) : warning BC40000: 'Public Function NewLineBound(start As Autodesk.Revit.DB.XYZ, end As Autodesk.Revit.DB.XYZ) As Autodesk.Revit.DB.Line' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() instead.'.
Z:\a\lib\revit\2014\adn\src\lab\3_Revit_Family_API\SourceVB\2_ColumnLshape.vb(511) : warning BC40000: 'Public Function NewLineBound(start As Autodesk.Revit.DB.XYZ, end As Autodesk.Revit.DB.XYZ) As Autodesk.Revit.DB.Line' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() instead.'.
Z:\a\lib\revit\2014\adn\src\lab\3_Revit_Family_API\SourceVB\2_ColumnLshape.vb(526) : warning BC40000: 'Public Property Label As Autodesk.Revit.DB.FamilyParameter' is obsolete: 'This property is obsolete in Autodesk Revit 2014.  Please use FamilyLabel instead.'.
Z:\a\lib\revit\2014\adn\src\lab\3_Revit_Family_API\SourceVB\2_ColumnLshape.vb(536) : warning BC40000: 'Public Function NewLineBound(start As Autodesk.Revit.DB.XYZ, end As Autodesk.Revit.DB.XYZ) As Autodesk.Revit.DB.Line' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() instead.'.
Z:\a\lib\revit\2014\adn\src\lab\3_Revit_Family_API\SourceVB\2_ColumnLshape.vb(551) : warning BC40000: 'Public Property Label As Autodesk.Revit.DB.FamilyParameter' is obsolete: 'This property is obsolete in Autodesk Revit 2014.  Please use FamilyLabel instead.'.
Z:\a\lib\revit\2014\adn\src\lab\3_Revit_Family_API\SourceVB\2_ColumnLshape.vb(689) : warning BC40000: 'Public Function NewLineBound(start As Autodesk.Revit.DB.XYZ, end As Autodesk.Revit.DB.XYZ) As Autodesk.Revit.DB.Line' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() instead.'.
Z:\a\lib\revit\2014\adn\src\lab\3_Revit_Family_API\SourceVB\3_ColumnFormulaMaterial.vb(273) : warning BC40000: 'Public Function NewSketchPlane(geometryPlane As Autodesk.Revit.DB.Plane) As Autodesk.Revit.DB.SketchPlane' is obsolete: 'This method is obsolete in Revit 2014. Use SketchPlane.Create() instead. To create a reference relationship between the sketch plane and geometry, use the overload with a Reference input.'.
Z:\a\lib\revit\2014\adn\src\lab\3_Revit_Family_API\SourceVB\3_ColumnFormulaMaterial.vb(330) : warning BC40000: 'Public Function NewLineBound(start As Autodesk.Revit.DB.XYZ, end As Autodesk.Revit.DB.XYZ) As Autodesk.Revit.DB.Line' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() instead.'.
Z:\a\lib\revit\2014\adn\src\lab\3_Revit_Family_API\SourceVB\3_ColumnFormulaMaterial.vb(377) : warning BC40000: 'Public Function NewLineBound(start As Autodesk.Revit.DB.XYZ, end As Autodesk.Revit.DB.XYZ) As Autodesk.Revit.DB.Line' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() instead.'.
Z:\a\lib\revit\2014\adn\src\lab\3_Revit_Family_API\SourceVB\3_ColumnFormulaMaterial.vb(527) : warning BC40000: 'Public Function NewLineBound(start As Autodesk.Revit.DB.XYZ, end As Autodesk.Revit.DB.XYZ) As Autodesk.Revit.DB.Line' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() instead.'.
Z:\a\lib\revit\2014\adn\src\lab\3_Revit_Family_API\SourceVB\3_ColumnFormulaMaterial.vb(542) : warning BC40000: 'Public Property Label As Autodesk.Revit.DB.FamilyParameter' is obsolete: 'This property is obsolete in Autodesk Revit 2014.  Please use FamilyLabel instead.'.
Z:\a\lib\revit\2014\adn\src\lab\3_Revit_Family_API\SourceVB\3_ColumnFormulaMaterial.vb(552) : warning BC40000: 'Public Function NewLineBound(start As Autodesk.Revit.DB.XYZ, end As Autodesk.Revit.DB.XYZ) As Autodesk.Revit.DB.Line' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() instead.'.
Z:\a\lib\revit\2014\adn\src\lab\3_Revit_Family_API\SourceVB\3_ColumnFormulaMaterial.vb(567) : warning BC40000: 'Public Property Label As Autodesk.Revit.DB.FamilyParameter' is obsolete: 'This property is obsolete in Autodesk Revit 2014.  Please use FamilyLabel instead.'.
Z:\a\lib\revit\2014\adn\src\lab\3_Revit_Family_API\SourceVB\3_ColumnFormulaMaterial.vb(793) : warning BC40000: 'Public Function NewLineBound(start As Autodesk.Revit.DB.XYZ, end As Autodesk.Revit.DB.XYZ) As Autodesk.Revit.DB.Line' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() instead.'.
Z:\a\lib\revit\2014\adn\src\lab\3_Revit_Family_API\SourceVB\4_ColumnVisibility.vb(283) : warning BC40000: 'Public Function NewSketchPlane(geometryPlane As Autodesk.Revit.DB.Plane) As Autodesk.Revit.DB.SketchPlane' is obsolete: 'This method is obsolete in Revit 2014. Use SketchPlane.Create() instead. To create a reference relationship between the sketch plane and geometry, use the overload with a Reference input.'.
Z:\a\lib\revit\2014\adn\src\lab\3_Revit_Family_API\SourceVB\4_ColumnVisibility.vb(340) : warning BC40000: 'Public Function NewLineBound(start As Autodesk.Revit.DB.XYZ, end As Autodesk.Revit.DB.XYZ) As Autodesk.Revit.DB.Line' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() instead.'.
Z:\a\lib\revit\2014\adn\src\lab\3_Revit_Family_API\SourceVB\4_ColumnVisibility.vb(387) : warning BC40000: 'Public Function NewLineBound(start As Autodesk.Revit.DB.XYZ, end As Autodesk.Revit.DB.XYZ) As Autodesk.Revit.DB.Line' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() instead.'.
Z:\a\lib\revit\2014\adn\src\lab\3_Revit_Family_API\SourceVB\4_ColumnVisibility.vb(537) : warning BC40000: 'Public Function NewLineBound(start As Autodesk.Revit.DB.XYZ, end As Autodesk.Revit.DB.XYZ) As Autodesk.Revit.DB.Line' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() instead.'.
Z:\a\lib\revit\2014\adn\src\lab\3_Revit_Family_API\SourceVB\4_ColumnVisibility.vb(552) : warning BC40000: 'Public Property Label As Autodesk.Revit.DB.FamilyParameter' is obsolete: 'This property is obsolete in Autodesk Revit 2014.  Please use FamilyLabel instead.'.
Z:\a\lib\revit\2014\adn\src\lab\3_Revit_Family_API\SourceVB\4_ColumnVisibility.vb(562) : warning BC40000: 'Public Function NewLineBound(start As Autodesk.Revit.DB.XYZ, end As Autodesk.Revit.DB.XYZ) As Autodesk.Revit.DB.Line' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() instead.'.
Z:\a\lib\revit\2014\adn\src\lab\3_Revit_Family_API\SourceVB\4_ColumnVisibility.vb(577) : warning BC40000: 'Public Property Label As Autodesk.Revit.DB.FamilyParameter' is obsolete: 'This property is obsolete in Autodesk Revit 2014.  Please use FamilyLabel instead.'.
Z:\a\lib\revit\2014\adn\src\lab\3_Revit_Family_API\SourceVB\4_ColumnVisibility.vb(800) : warning BC40000: 'Public Function NewSketchPlane(geometryPlane As Autodesk.Revit.DB.Plane) As Autodesk.Revit.DB.SketchPlane' is obsolete: 'This method is obsolete in Revit 2014. Use SketchPlane.Create() instead. To create a reference relationship between the sketch plane and geometry, use the overload with a Reference input.'.
Z:\a\lib\revit\2014\adn\src\lab\3_Revit_Family_API\SourceVB\4_ColumnVisibility.vb(805) : warning BC40000: 'Public Function NewSketchPlane(geometryPlane As Autodesk.Revit.DB.Plane) As Autodesk.Revit.DB.SketchPlane' is obsolete: 'This method is obsolete in Revit 2014. Use SketchPlane.Create() instead. To create a reference relationship between the sketch plane and geometry, use the overload with a Reference input.'.
Z:\a\lib\revit\2014\adn\src\lab\3_Revit_Family_API\SourceVB\4_ColumnVisibility.vb(809) : warning BC40000: 'Public Function NewLine(point As Autodesk.Revit.DB.XYZ, endOrDirection As Autodesk.Revit.DB.XYZ, bound As Boolean) As Autodesk.Revit.DB.Line' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() or Line.CreateUnbound() instead.'.
Z:\a\lib\revit\2014\adn\src\lab\3_Revit_Family_API\SourceVB\4_ColumnVisibility.vb(810) : warning BC40000: 'Public Function NewLine(point As Autodesk.Revit.DB.XYZ, endOrDirection As Autodesk.Revit.DB.XYZ, bound As Boolean) As Autodesk.Revit.DB.Line' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() or Line.CreateUnbound() instead.'.
Z:\a\lib\revit\2014\adn\src\lab\3_Revit_Family_API\SourceVB\4_ColumnVisibility.vb(811) : warning BC40000: 'Public Function NewLine(point As Autodesk.Revit.DB.XYZ, endOrDirection As Autodesk.Revit.DB.XYZ, bound As Boolean) As Autodesk.Revit.DB.Line' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() or Line.CreateUnbound() instead.'.
Z:\a\lib\revit\2014\adn\src\lab\3_Revit_Family_API\SourceVB\4_ColumnVisibility.vb(886) : warning BC40000: 'Public Function NewLineBound(start As Autodesk.Revit.DB.XYZ, end As Autodesk.Revit.DB.XYZ) As Autodesk.Revit.DB.Line' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() instead.'.
C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(1578,5): warning MSB3270: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "RevitAPI", "AMD64". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.
C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(1578,5): warning MSB3270: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "RevitAPIUI", "AMD64". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.
  FamilyVb -> Z:\a\lib\revit\2014\adn\src\lab\3_Revit_Family_API\SourceVB\bin\Debug\FamilyVb.dll
------ Rebuild All started: Project: UiVb, Configuration: Debug Any CPU ------
C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(1578,5): warning MSB3270: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "RevitAPI, Version=2012.0.0.0, Culture=neutral, processorArchitecture=x86", "AMD64". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.
C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(1578,5): warning MSB3270: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "RevitAPIUI, Version=2012.0.0.0, Culture=neutral, processorArchitecture=x86", "AMD64". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.
  UiVb -> Z:\a\lib\revit\2014\adn\src\lab\2_Revit_UI_API\SourceVB\bin\Debug\UiVb.dll
------ Rebuild All started: Project: FamilyCs, Configuration: Debug Any CPU ------
Z:\a\lib\revit\2014\adn\src\lab\3_Revit_Family_API\SourceCS\3_ColumnFormulaMaterial.cs(275,34): warning CS0618: 'Autodesk.Revit.Creation.ItemFactoryBase.NewSketchPlane(Autodesk.Revit.DB.Plane)' is obsolete: 'This method is obsolete in Revit 2014. Use SketchPlane.Create() instead. To create a reference relationship between the sketch plane and geometry, use the overload with a Reference input.'
Z:\a\lib\revit\2014\adn\src\lab\3_Revit_Family_API\SourceCS\3_ColumnFormulaMaterial.cs(336,21): warning CS0618: 'Autodesk.Revit.Creation.Application.NewLineBound(Autodesk.Revit.DB.XYZ, Autodesk.Revit.DB.XYZ)' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() instead.'
Z:\a\lib\revit\2014\adn\src\lab\3_Revit_Family_API\SourceCS\3_ColumnFormulaMaterial.cs(388,21): warning CS0618: 'Autodesk.Revit.Creation.Application.NewLineBound(Autodesk.Revit.DB.XYZ, Autodesk.Revit.DB.XYZ)' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() instead.'
Z:\a\lib\revit\2014\adn\src\lab\3_Revit_Family_API\SourceCS\3_ColumnFormulaMaterial.cs(538,20): warning CS0618: 'Autodesk.Revit.Creation.Application.NewLineBound(Autodesk.Revit.DB.XYZ, Autodesk.Revit.DB.XYZ)' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() instead.'
Z:\a\lib\revit\2014\adn\src\lab\3_Revit_Family_API\SourceCS\3_ColumnFormulaMaterial.cs(563,15): warning CS0618: 'Autodesk.Revit.Creation.Application.NewLineBound(Autodesk.Revit.DB.XYZ, Autodesk.Revit.DB.XYZ)' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() instead.'
Z:\a\lib\revit\2014\adn\src\lab\3_Revit_Family_API\SourceCS\3_ColumnFormulaMaterial.cs(553,7): warning CS0618: 'Autodesk.Revit.DB.Dimension.Label' is obsolete: 'This property is obsolete in Autodesk Revit 2014.  Please use FamilyLabel instead.'
Z:\a\lib\revit\2014\adn\src\lab\3_Revit_Family_API\SourceCS\3_ColumnFormulaMaterial.cs(578,7): warning CS0618: 'Autodesk.Revit.DB.Dimension.Label' is obsolete: 'This property is obsolete in Autodesk Revit 2014.  Please use FamilyLabel instead.'
Z:\a\lib\revit\2014\adn\src\lab\3_Revit_Family_API\SourceCS\3_ColumnFormulaMaterial.cs(797,29): warning CS0618: 'Autodesk.Revit.Creation.Application.NewLineBound(Autodesk.Revit.DB.XYZ, Autodesk.Revit.DB.XYZ)' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() instead.'
Z:\a\lib\revit\2014\adn\src\lab\3_Revit_Family_API\SourceCS\4_ColumnVisibility.cs(278,34): warning CS0618: 'Autodesk.Revit.Creation.ItemFactoryBase.NewSketchPlane(Autodesk.Revit.DB.Plane)' is obsolete: 'This method is obsolete in Revit 2014. Use SketchPlane.Create() instead. To create a reference relationship between the sketch plane and geometry, use the overload with a Reference input.'
Z:\a\lib\revit\2014\adn\src\lab\3_Revit_Family_API\SourceCS\4_ColumnVisibility.cs(339,21): warning CS0618: 'Autodesk.Revit.Creation.Application.NewLineBound(Autodesk.Revit.DB.XYZ, Autodesk.Revit.DB.XYZ)' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() instead.'
Z:\a\lib\revit\2014\adn\src\lab\3_Revit_Family_API\SourceCS\4_ColumnVisibility.cs(391,21): warning CS0618: 'Autodesk.Revit.Creation.Application.NewLineBound(Autodesk.Revit.DB.XYZ, Autodesk.Revit.DB.XYZ)' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() instead.'
Z:\a\lib\revit\2014\adn\src\lab\3_Revit_Family_API\SourceCS\4_ColumnVisibility.cs(541,20): warning CS0618: 'Autodesk.Revit.Creation.Application.NewLineBound(Autodesk.Revit.DB.XYZ, Autodesk.Revit.DB.XYZ)' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() instead.'
Z:\a\lib\revit\2014\adn\src\lab\3_Revit_Family_API\SourceCS\4_ColumnVisibility.cs(566,15): warning CS0618: 'Autodesk.Revit.Creation.Application.NewLineBound(Autodesk.Revit.DB.XYZ, Autodesk.Revit.DB.XYZ)' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() instead.'
Z:\a\lib\revit\2014\adn\src\lab\3_Revit_Family_API\SourceCS\4_ColumnVisibility.cs(556,7): warning CS0618: 'Autodesk.Revit.DB.Dimension.Label' is obsolete: 'This property is obsolete in Autodesk Revit 2014.  Please use FamilyLabel instead.'
Z:\a\lib\revit\2014\adn\src\lab\3_Revit_Family_API\SourceCS\4_ColumnVisibility.cs(581,7): warning CS0618: 'Autodesk.Revit.DB.Dimension.Label' is obsolete: 'This property is obsolete in Autodesk Revit 2014.  Please use FamilyLabel instead.'
Z:\a\lib\revit\2014\adn\src\lab\3_Revit_Family_API\SourceCS\4_ColumnVisibility.cs(805,34): warning CS0618: 'Autodesk.Revit.Creation.ItemFactoryBase.NewSketchPlane(Autodesk.Revit.DB.Plane)' is obsolete: 'This method is obsolete in Revit 2014. Use SketchPlane.Create() instead. To create a reference relationship between the sketch plane and geometry, use the overload with a Reference input.'
Z:\a\lib\revit\2014\adn\src\lab\3_Revit_Family_API\SourceCS\4_ColumnVisibility.cs(810,35): warning CS0618: 'Autodesk.Revit.Creation.ItemFactoryBase.NewSketchPlane(Autodesk.Revit.DB.Plane)' is obsolete: 'This method is obsolete in Revit 2014. Use SketchPlane.Create() instead. To create a reference relationship between the sketch plane and geometry, use the overload with a Reference input.'
Z:\a\lib\revit\2014\adn\src\lab\3_Revit_Family_API\SourceCS\4_ColumnVisibility.cs(814,24): warning CS0618: 'Autodesk.Revit.Creation.Application.NewLine(Autodesk.Revit.DB.XYZ, Autodesk.Revit.DB.XYZ, bool)' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() or Line.CreateUnbound() instead.'
Z:\a\lib\revit\2014\adn\src\lab\3_Revit_Family_API\SourceCS\4_ColumnVisibility.cs(815,24): warning CS0618: 'Autodesk.Revit.Creation.Application.NewLine(Autodesk.Revit.DB.XYZ, Autodesk.Revit.DB.XYZ, bool)' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() or Line.CreateUnbound() instead.'
Z:\a\lib\revit\2014\adn\src\lab\3_Revit_Family_API\SourceCS\4_ColumnVisibility.cs(816,24): warning CS0618: 'Autodesk.Revit.Creation.Application.NewLine(Autodesk.Revit.DB.XYZ, Autodesk.Revit.DB.XYZ, bool)' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() or Line.CreateUnbound() instead.'
Z:\a\lib\revit\2014\adn\src\lab\3_Revit_Family_API\SourceCS\4_ColumnVisibility.cs(884,29): warning CS0618: 'Autodesk.Revit.Creation.Application.NewLineBound(Autodesk.Revit.DB.XYZ, Autodesk.Revit.DB.XYZ)' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() instead.'
Z:\a\lib\revit\2014\adn\src\lab\3_Revit_Family_API\SourceCS\2_ColumnLshape.cs(264,34): warning CS0618: 'Autodesk.Revit.Creation.ItemFactoryBase.NewSketchPlane(Autodesk.Revit.DB.Plane)' is obsolete: 'This method is obsolete in Revit 2014. Use SketchPlane.Create() instead. To create a reference relationship between the sketch plane and geometry, use the overload with a Reference input.'
Z:\a\lib\revit\2014\adn\src\lab\3_Revit_Family_API\SourceCS\2_ColumnLshape.cs(325,21): warning CS0618: 'Autodesk.Revit.Creation.Application.NewLineBound(Autodesk.Revit.DB.XYZ, Autodesk.Revit.DB.XYZ)' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() instead.'
Z:\a\lib\revit\2014\adn\src\lab\3_Revit_Family_API\SourceCS\2_ColumnLshape.cs(377,21): warning CS0618: 'Autodesk.Revit.Creation.Application.NewLineBound(Autodesk.Revit.DB.XYZ, Autodesk.Revit.DB.XYZ)' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() instead.'
Z:\a\lib\revit\2014\adn\src\lab\3_Revit_Family_API\SourceCS\2_ColumnLshape.cs(522,20): warning CS0618: 'Autodesk.Revit.Creation.Application.NewLineBound(Autodesk.Revit.DB.XYZ, Autodesk.Revit.DB.XYZ)' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() instead.'
Z:\a\lib\revit\2014\adn\src\lab\3_Revit_Family_API\SourceCS\2_ColumnLshape.cs(547,15): warning CS0618: 'Autodesk.Revit.Creation.Application.NewLineBound(Autodesk.Revit.DB.XYZ, Autodesk.Revit.DB.XYZ)' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() instead.'
Z:\a\lib\revit\2014\adn\src\lab\3_Revit_Family_API\SourceCS\2_ColumnLshape.cs(537,7): warning CS0618: 'Autodesk.Revit.DB.Dimension.Label' is obsolete: 'This property is obsolete in Autodesk Revit 2014.  Please use FamilyLabel instead.'
Z:\a\lib\revit\2014\adn\src\lab\3_Revit_Family_API\SourceCS\2_ColumnLshape.cs(562,7): warning CS0618: 'Autodesk.Revit.DB.Dimension.Label' is obsolete: 'This property is obsolete in Autodesk Revit 2014.  Please use FamilyLabel instead.'
Z:\a\lib\revit\2014\adn\src\lab\3_Revit_Family_API\SourceCS\2_ColumnLshape.cs(721,29): warning CS0618: 'Autodesk.Revit.Creation.Application.NewLineBound(Autodesk.Revit.DB.XYZ, Autodesk.Revit.DB.XYZ)' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() instead.'

Compile complete -- 0 errors, 29 warnings
C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(1578,5): warning MSB3270: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "RevitAPI", "AMD64". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.
C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(1578,5): warning MSB3270: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "RevitAPIUI", "AMD64". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.
  FamilyCs -> Z:\a\lib\revit\2014\adn\src\lab\3_Revit_Family_API\SourceCS\bin\Debug\FamilyCs.dll
------ Rebuild All started: Project: XtraVb, Configuration: Debug Any CPU ------
Z:\a\lib\revit\2014\adn\src\lab\XtraVb\Labs2.vb(96) : warning BC40000: 'Public Function NewLineBound(start As Autodesk.Revit.DB.XYZ, end As Autodesk.Revit.DB.XYZ) As Autodesk.Revit.DB.Line' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() instead.'.
Z:\a\lib\revit\2014\adn\src\lab\XtraVb\Labs2.vb(150) : warning BC40000: 'Public Function NewLineBound(start As Autodesk.Revit.DB.XYZ, end As Autodesk.Revit.DB.XYZ) As Autodesk.Revit.DB.Line' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() instead.'.
Z:\a\lib\revit\2014\adn\src\lab\XtraVb\Labs2.vb(181) : warning BC40000: 'Public Function NewRoomTag(room As Autodesk.Revit.DB.Architecture.Room, point As Autodesk.Revit.DB.UV, view As Autodesk.Revit.DB.View) As Autodesk.Revit.DB.Architecture.RoomTag' is obsolete: 'This method is deprecated in Revit 2014.  Use the NewRoomTag(LinkElementId, UV, ElementId) overload instead.'.
Z:\a\lib\revit\2014\adn\src\lab\XtraVb\Labs2.vb(648) : warning BC40000: 'Public ReadOnly Property EndPoint(index As Integer) As Autodesk.Revit.DB.XYZ' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'.
Z:\a\lib\revit\2014\adn\src\lab\XtraVb\Labs2.vb(649) : warning BC40000: 'Public ReadOnly Property EndPoint(index As Integer) As Autodesk.Revit.DB.XYZ' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'.
Z:\a\lib\revit\2014\adn\src\lab\XtraVb\Labs3.vb(402) : warning BC40000: 'Public ReadOnly Property WallTypes As Autodesk.Revit.DB.WallTypeSet' is obsolete: 'This method is obsolete in Revit 2014. Use FilteredElementCollector with an appropriate class filter instead.'.
Z:\a\lib\revit\2014\adn\src\lab\XtraVb\Labs3.vb(418) : warning BC40000: 'Public ReadOnly Property FloorTypes As Autodesk.Revit.DB.FloorTypeSet' is obsolete: 'This method is obsolete in Revit 2014. Use FilteredElementCollector with an appropriate class filter instead.'.
Z:\a\lib\revit\2014\adn\src\lab\XtraVb\Labs3.vb(574) : warning BC40000: 'Public Function Delete(element As Autodesk.Revit.DB.Element) As System.Collections.Generic.ICollection(Of Autodesk.Revit.DB.ElementId)' is obsolete: 'This method is obsolete in Revit 2014. Use Delete(ElementId) instead.'.
Z:\a\lib\revit\2014\adn\src\lab\XtraVb\Labs4.vb(468) : warning BC40000: 'Public Overridable ReadOnly Property Level As Autodesk.Revit.DB.Level' is obsolete: 'This property is obsolete in Revit 2014. Call Element.LevelId instead.'.
Z:\a\lib\revit\2014\adn\src\lab\XtraVb\Labs5.vb(252) : warning BC40000: 'Public ReadOnly Property EndPoint(index As Integer) As Autodesk.Revit.DB.XYZ' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'.
Z:\a\lib\revit\2014\adn\src\lab\XtraVb\Labs5.vb(253) : warning BC40000: 'Public ReadOnly Property EndPoint(index As Integer) As Autodesk.Revit.DB.XYZ' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'.
Z:\a\lib\revit\2014\adn\src\lab\XtraVb\Labs5.vb(259) : warning BC40000: 'Public ReadOnly Property EndPoint(index As Integer) As Autodesk.Revit.DB.XYZ' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'.
Z:\a\lib\revit\2014\adn\src\lab\XtraVb\Labs5.vb(260) : warning BC40000: 'Public ReadOnly Property EndPoint(index As Integer) As Autodesk.Revit.DB.XYZ' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'.
Z:\a\lib\revit\2014\adn\src\lab\XtraVb\Labs7.vb(163) : warning BC40000: 'Public Function NewDividedSurface(hostReference As Autodesk.Revit.DB.Reference) As Autodesk.Revit.DB.DividedSurface' is obsolete: 'This method is deprecated in Revit 2014.  Use DividedSurface.Create() instead'.
Z:\a\lib\revit\2014\adn\src\lab\XtraVb\Labs7.vb(207) : warning BC40000: 'Autodesk.Revit.DB.DividedSurfaceData' is obsolete: 'This class is obsolete in Revit 2014.  Use 'DividedSurface::GetReferencesWithDividedSurfaces' and 'DividedSurface::GetDividedSurfaceForReference' instead.'.
Z:\a\lib\revit\2014\adn\src\lab\XtraVb\Labs7.vb(207) : warning BC40000: 'Public Function GetDividedSurfaceData() As Autodesk.Revit.DB.DividedSurfaceData' is obsolete: 'This method is obsolete in Revit 2014.  Use 'DividedSurface::Create' instead.'.
C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(1578,5): warning MSB3270: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "RevitAPI", "AMD64". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.
C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(1578,5): warning MSB3270: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "RevitAPIUI", "AMD64". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.
  XtraVb -> Z:\a\lib\revit\2014\adn\src\lab\XtraVb\bin\Debug\XtraVb.dll
------ Rebuild All started: Project: XtraCs, Configuration: Debug Any CPU ------
Z:\a\lib\revit\2014\adn\src\lab\XtraCs\Labs7.cs(165,47): warning CS0618: 'Autodesk.Revit.Creation.FamilyItemFactory.NewDividedSurface(Autodesk.Revit.DB.Reference)' is obsolete: 'This method is deprecated in Revit 2014.  Use DividedSurface.Create() instead'
Z:\a\lib\revit\2014\adn\src\lab\XtraCs\Labs7.cs(208,11): warning CS0618: 'Autodesk.Revit.DB.DividedSurfaceData' is obsolete: 'This class is obsolete in Revit 2014.  Use 'DividedSurface::GetReferencesWithDividedSurfaces' and 'DividedSurface::GetDividedSurfaceForReference' instead.'
Z:\a\lib\revit\2014\adn\src\lab\XtraCs\Labs7.cs(208,39): warning CS0618: 'Autodesk.Revit.DB.Element.GetDividedSurfaceData()' is obsolete: 'This method is obsolete in Revit 2014.  Use 'DividedSurface::Create' instead.'
Z:\a\lib\revit\2014\adn\src\lab\XtraCs\Labs5.cs(324,29): warning CS0618: 'Autodesk.Revit.DB.Curve.get_EndPoint(int)' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'
Z:\a\lib\revit\2014\adn\src\lab\XtraCs\Labs5.cs(325,29): warning CS0618: 'Autodesk.Revit.DB.Curve.get_EndPoint(int)' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'
Z:\a\lib\revit\2014\adn\src\lab\XtraCs\Labs5.cs(333,29): warning CS0618: 'Autodesk.Revit.DB.Curve.get_EndPoint(int)' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'
Z:\a\lib\revit\2014\adn\src\lab\XtraCs\Labs5.cs(334,29): warning CS0618: 'Autodesk.Revit.DB.Curve.get_EndPoint(int)' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'
Z:\a\lib\revit\2014\adn\src\lab\XtraCs\Labs4.cs(697,35): warning CS0618: 'Autodesk.Revit.DB.Element.Level' is obsolete: 'This property is obsolete in Revit 2014. Call Element.LevelId instead.'
Z:\a\lib\revit\2014\adn\src\lab\XtraCs\Labs3.cs(435,31): warning CS0618: 'Autodesk.Revit.DB.Document.WallTypes' is obsolete: 'This method is obsolete in Revit 2014. Use FilteredElementCollector with an appropriate class filter instead.'
Z:\a\lib\revit\2014\adn\src\lab\XtraCs\Labs3.cs(454,32): warning CS0618: 'Autodesk.Revit.DB.Document.FloorTypes' is obsolete: 'This method is obsolete in Revit 2014. Use FilteredElementCollector with an appropriate class filter instead.'
Z:\a\lib\revit\2014\adn\src\lab\XtraCs\Labs3.cs(653,7): warning CS0618: 'Autodesk.Revit.DB.Document.Delete(Autodesk.Revit.DB.Element)' is obsolete: 'This method is obsolete in Revit 2014. Use Delete(ElementId) instead.'
Z:\a\lib\revit\2014\adn\src\lab\XtraCs\Labs2.cs(196,23): warning CS0618: 'Autodesk.Revit.Creation.Application.NewLineBound(Autodesk.Revit.DB.XYZ, Autodesk.Revit.DB.XYZ)' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() instead.'
Z:\a\lib\revit\2014\adn\src\lab\XtraCs\Labs2.cs(260,23): warning CS0618: 'Autodesk.Revit.Creation.Application.NewLineBound(Autodesk.Revit.DB.XYZ, Autodesk.Revit.DB.XYZ)' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() instead.'
Z:\a\lib\revit\2014\adn\src\lab\XtraCs\Labs2.cs(333,27): warning CS0618: 'Autodesk.Revit.Creation.Document.NewRoomTag(Autodesk.Revit.DB.Architecture.Room, Autodesk.Revit.DB.UV, Autodesk.Revit.DB.View)' is obsolete: 'This method is deprecated in Revit 2014.  Use the NewRoomTag(LinkElementId, UV, ElementId) overload instead.'
Z:\a\lib\revit\2014\adn\src\lab\XtraCs\Labs2.cs(936,21): warning CS0618: 'Autodesk.Revit.DB.Curve.get_EndPoint(int)' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'
Z:\a\lib\revit\2014\adn\src\lab\XtraCs\Labs2.cs(937,19): warning CS0618: 'Autodesk.Revit.DB.Curve.get_EndPoint(int)' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'

Compile complete -- 0 errors, 16 warnings
C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(1578,5): warning MSB3270: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "RevitAPI", "AMD64". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.
C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(1578,5): warning MSB3270: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "RevitAPIUI", "AMD64". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.
  XtraCs -> Z:\a\lib\revit\2014\adn\src\lab\XtraCs\bin\Debug\XtraCs.dll
========== Rebuild All: 8 succeeded, 0 failed, 0 skipped ==========
