Warning	1	'Autodesk.Revit.Creation.Document.NewWall(Autodesk.Revit.DB.CurveArray, bool)' is obsolete: 'This method is obsolete in Revit 2013. Please call a static creation method of Wall class instead.'	C:\a\lib\revit\2013\bc\BuildingCoder\BuildingCoder\CmdSlopedWall.cs	65	19	BuildingCoder
Warning	2	'Autodesk.Revit.Creation.Document.NewWall(Autodesk.Revit.DB.CurveArray, Autodesk.Revit.DB.WallType, Autodesk.Revit.DB.Level, bool, Autodesk.Revit.DB.XYZ)' is obsolete: 'This method is obsolete in Revit 2013. Please call a static creation method of Wall class instead.'	C:\a\lib\revit\2013\bc\BuildingCoder\BuildingCoder\CmdCreateGableWall.cs	89	19	BuildingCoder
Warning	3	'Autodesk.Revit.Creation.Document.NewWall(Autodesk.Revit.DB.CurveArray, Autodesk.Revit.DB.WallType, Autodesk.Revit.DB.Level, bool, Autodesk.Revit.DB.XYZ)' is obsolete: 'This method is obsolete in Revit 2013. Please call a static creation method of Wall class instead.'	C:\a\lib\revit\2013\bc\BuildingCoder\BuildingCoder\CmdSlopedWall.cs	140	19	BuildingCoder
Warning	4	'Autodesk.Revit.Creation.Document.NewWall(Autodesk.Revit.DB.Curve, Autodesk.Revit.DB.WallType, Autodesk.Revit.DB.Level, double, double, bool, bool)' is obsolete: 'This method is obsolete in Revit 2013. Please call a static creation method of Wall class instead.'	C:\a\lib\revit\2013\bc\BuildingCoder\BuildingCoder\CmdPressKeys.cs	222	19	BuildingCoder
Warning	5	'Autodesk.Revit.Creation.ItemFactoryBase.NewView3D(Autodesk.Revit.DB.XYZ)' is obsolete: '"This method is obsolete in Revit 2013. Call View3D.CreateIsometric() instead."'	C:\a\lib\revit\2013\bc\BuildingCoder\BuildingCoder\CmdNewSpotElevation.cs	53	23	BuildingCoder
Warning	6	'Autodesk.Revit.DB.GeometryElement.Objects' is obsolete: '"This property will be obsolete from 2013; Call GetEnumerator() instead."'	C:\a\lib\revit\2013\bc\BuildingCoder\BuildingCoder\CmdTransformedCoords.cs	67	41	BuildingCoder
Warning	7	'Autodesk.Revit.DB.GeometryElement.Objects' is obsolete: '"This property will be obsolete from 2013; Call GetEnumerator() instead."'	C:\a\lib\revit\2013\bc\BuildingCoder\BuildingCoder\CmdLinkedFiles.cs	103	41	BuildingCoder
Warning	8	'Autodesk.Revit.Creation.Document.NewWall(Autodesk.Revit.DB.Curve, Autodesk.Revit.DB.Level, bool)' is obsolete: '"This method is obsolete in Revit 2013. Please call a static creation method of Wall class instead."'	C:\a\lib\revit\2013\bc\BuildingCoder\BuildingCoder\CmdSetTagType.cs	171	19	BuildingCoder
Warning	9	'Autodesk.Revit.DB.PlanTopology.Rooms' is obsolete: '"This property is obsolete in Revit 2013.  Call GetRoomIds() instead."'	C:\a\lib\revit\2013\bc\BuildingCoder\BuildingCoder\CmdPlanTopology.cs	48	26	BuildingCoder
Warning	10	'Autodesk.Revit.Creation.ItemFactoryBase.NewGroup(Autodesk.Revit.DB.ElementSet)' is obsolete: '"This method is obsolete in Revit 2013.  Call NewGroup(System.Collections.Generic.ICollection<Autodesk.Revit.DB.ElementId> elementIds) instead."'	C:\a\lib\revit\2013\bc\BuildingCoder\BuildingCoder\CmdDuplicateElements.cs	36	21	BuildingCoder
Warning	11	'Autodesk.Revit.DB.Group.Ungroup()' is obsolete: '"This method is Obsolete in Revit 2013.  Call UngroupMembers() instead."'	C:\a\lib\revit\2013\bc\BuildingCoder\BuildingCoder\CmdDuplicateElements.cs	48	7	BuildingCoder
Warning	12	'Autodesk.Revit.DB.Group.Ungroup()' is obsolete: '"This method is Obsolete in Revit 2013.  Call UngroupMembers() instead."'	C:\a\lib\revit\2013\bc\BuildingCoder\BuildingCoder\CmdDuplicateElements.cs	50	25	BuildingCoder
Warning	13	'Autodesk.Revit.DB.GeometryElement.Objects' is obsolete: '"This property will be obsolete from 2013; Call GetEnumerator() instead."'	C:\a\lib\revit\2013\bc\BuildingCoder\BuildingCoder\CmdNestedInstanceGeo.cs	119	32	BuildingCoder
