2015-05-20 zero errors and 30 warnings after renaming ExternalDefinitonCreationOptions to ExternalDefinitionCreationOptions and ContFooting to WallFoundation

------ Rebuild All started: Project: BuildingCoder, Configuration: Debug Any CPU ------
C:\a\lib\revit\2015\bc\BuildingCoder\BuildingCoder\CmdCollectorPerformance.cs(1252,21,1252,54): warning CS0618: 'Autodesk.Revit.Creation.ItemFactoryBase.NewLevel(double)' is obsolete: 'This method is deprecated in Revit 2016. Use Level.Create() instead.'
C:\a\lib\revit\2015\bc\BuildingCoder\BuildingCoder\CmdDimensionWallsIterateFaces.cs(191,43,191,52): warning CS0618: 'Autodesk.Revit.DB.PlanarFace.Normal' is obsolete: 'This property is obsolete in Revit 2016.  Use the FaceNormal property or Face.ComputeNormal() instead.'
C:\a\lib\revit\2015\bc\BuildingCoder\BuildingCoder\CmdDimensionWallsIterateFaces.cs(197,41,197,50): warning CS0618: 'Autodesk.Revit.DB.PlanarFace.Normal' is obsolete: 'This property is obsolete in Revit 2016.  Use the FaceNormal property or Face.ComputeNormal() instead.'
C:\a\lib\revit\2015\bc\BuildingCoder\BuildingCoder\CmdFaceWall.cs(195,23,195,32): warning CS0618: 'Autodesk.Revit.DB.PlanarFace.Normal' is obsolete: 'This property is obsolete in Revit 2016.  Use the FaceNormal property or Face.ComputeNormal() instead.'
C:\a\lib\revit\2015\bc\BuildingCoder\BuildingCoder\CmdMirror.cs(53,7,53,44): warning CS0618: 'Autodesk.Revit.DB.ElementTransformUtils.MirrorElements(Autodesk.Revit.DB.Document, System.Collections.Generic.ICollection<Autodesk.Revit.DB.ElementId>, Autodesk.Revit.DB.Plane)' is obsolete: 'This method will be obsolete from 2016. Use MirrorElements(Document, ICollection<ElementId>, Plane, bool) instead.'
C:\a\lib\revit\2015\bc\BuildingCoder\BuildingCoder\CmdMirror.cs(207,9,207,46): warning CS0618: 'Autodesk.Revit.DB.ElementTransformUtils.MirrorElements(Autodesk.Revit.DB.Document, System.Collections.Generic.ICollection<Autodesk.Revit.DB.ElementId>, Autodesk.Revit.DB.Plane)' is obsolete: 'This method will be obsolete from 2016. Use MirrorElements(Document, ICollection<ElementId>, Plane, bool) instead.'
C:\a\lib\revit\2015\bc\BuildingCoder\BuildingCoder\CmdMirror.cs(230,9,230,46): warning CS0618: 'Autodesk.Revit.DB.ElementTransformUtils.MirrorElements(Autodesk.Revit.DB.Document, System.Collections.Generic.ICollection<Autodesk.Revit.DB.ElementId>, Autodesk.Revit.DB.Plane)' is obsolete: 'This method will be obsolete from 2016. Use MirrorElements(Document, ICollection<ElementId>, Plane, bool) instead.'
C:\a\lib\revit\2015\bc\BuildingCoder\BuildingCoder\CmdMirror.cs(257,9,257,46): warning CS0618: 'Autodesk.Revit.DB.ElementTransformUtils.MirrorElements(Autodesk.Revit.DB.Document, System.Collections.Generic.ICollection<Autodesk.Revit.DB.ElementId>, Autodesk.Revit.DB.Plane)' is obsolete: 'This method will be obsolete from 2016. Use MirrorElements(Document, ICollection<ElementId>, Plane, bool) instead.'
C:\a\lib\revit\2015\bc\BuildingCoder\BuildingCoder\CmdMirror.cs(292,9,292,46): warning CS0618: 'Autodesk.Revit.DB.ElementTransformUtils.MirrorElements(Autodesk.Revit.DB.Document, System.Collections.Generic.ICollection<Autodesk.Revit.DB.ElementId>, Autodesk.Revit.DB.Plane)' is obsolete: 'This method will be obsolete from 2016. Use MirrorElements(Document, ICollection<ElementId>, Plane, bool) instead.'
C:\a\lib\revit\2015\bc\BuildingCoder\BuildingCoder\CmdNewTextNote.cs(136,27,136,50): warning CS0618: 'Autodesk.Revit.Creation.ItemFactoryBase.NewTextNote(Autodesk.Revit.DB.View, Autodesk.Revit.DB.XYZ, Autodesk.Revit.DB.XYZ, Autodesk.Revit.DB.XYZ, double, Autodesk.Revit.DB.TextAlignFlags, string)' is obsolete: 'This method is deprecated in Revit 2016. Please use one of the TextNote.Create methods instead.'
C:\a\lib\revit\2015\bc\BuildingCoder\BuildingCoder\CmdNewTextNote.cs(341,33,341,58): warning CS0618: 'Autodesk.Revit.Creation.ItemFactoryBase.NewTextNote(Autodesk.Revit.DB.View, Autodesk.Revit.DB.XYZ, Autodesk.Revit.DB.XYZ, Autodesk.Revit.DB.XYZ, double, Autodesk.Revit.DB.TextAlignFlags, string)' is obsolete: 'This method is deprecated in Revit 2016. Please use one of the TextNote.Create methods instead.'
C:\a\lib\revit\2015\bc\BuildingCoder\BuildingCoder\CmdRoomNeighbours.cs(39,16,39,26): warning CS0618: 'Autodesk.Revit.DB.BoundarySegment.Element' is obsolete: 'This property is deprecated in Revit 2016. Use ElementId instead.'
C:\a\lib\revit\2015\bc\BuildingCoder\BuildingCoder\CmdRoomNeighbours.cs(46,31,46,39): warning CS0618: 'Autodesk.Revit.DB.BoundarySegment.Curve' is obsolete: 'This property is deprecated in Revit 2016. Use GetCurve() instead.'
C:\a\lib\revit\2015\bc\BuildingCoder\BuildingCoder\CmdRoomNeighbours.cs(53,11,53,19): warning CS0618: 'Autodesk.Revit.DB.BoundarySegment.Curve' is obsolete: 'This property is deprecated in Revit 2016. Use GetCurve() instead.'
C:\a\lib\revit\2015\bc\BuildingCoder\BuildingCoder\CmdNewLineLoad.cs(88,33,88,48): warning CS0618: 'Autodesk.Revit.Creation.Document.NewLineLoad(System.Collections.Generic.IList<Autodesk.Revit.DB.XYZ>, System.Collections.Generic.IList<Autodesk.Revit.DB.XYZ>, System.Collections.Generic.IList<Autodesk.Revit.DB.XYZ>, bool, bool, bool, Autodesk.Revit.DB.Structure.LineLoadType, Autodesk.Revit.DB.SketchPlane)' is obsolete: 'This method is obsolete in Revit 2016. Use LineLoad.Create() method instead.'
C:\a\lib\revit\2015\bc\BuildingCoder\BuildingCoder\CmdNewLineLoad.cs(101,31,101,46): warning CS0618: 'Autodesk.Revit.Creation.Document.NewLineLoad(Autodesk.Revit.DB.Element, System.Collections.Generic.IList<Autodesk.Revit.DB.XYZ>, System.Collections.Generic.IList<Autodesk.Revit.DB.XYZ>, bool, bool, bool, Autodesk.Revit.DB.Structure.LineLoadType, Autodesk.Revit.DB.SketchPlane)' is obsolete: 'This method is obsolete in Revit 2016. Use LineLoad.Create() instead.'
C:\a\lib\revit\2015\bc\BuildingCoder\BuildingCoder\CmdNewLineLoad.cs(123,33,123,48): warning CS0618: 'Autodesk.Revit.Creation.Document.NewLineLoad(Autodesk.Revit.DB.Reference, System.Collections.Generic.IList<Autodesk.Revit.DB.XYZ>, System.Collections.Generic.IList<Autodesk.Revit.DB.XYZ>, bool, bool, bool, Autodesk.Revit.DB.Structure.LineLoadType, Autodesk.Revit.DB.SketchPlane)' is obsolete: 'This method is obsolete in Revit 2016. Use LineLoad.Create() method instead.'
C:\a\lib\revit\2015\bc\BuildingCoder\BuildingCoder\CmdNewSprinkler.cs(157,30,157,39): warning CS0618: 'Autodesk.Revit.DB.PlanarFace.Normal' is obsolete: 'This property is obsolete in Revit 2016.  Use the FaceNormal property or Face.ComputeNormal() instead.'
C:\a\lib\revit\2015\bc\BuildingCoder\BuildingCoder\CmdPickPoint3d.cs(166,15,166,26): warning CS0618: 'Autodesk.Revit.DB.PlanarFace.Normal' is obsolete: 'This property is obsolete in Revit 2016.  Use the FaceNormal property or Face.ComputeNormal() instead.'
C:\a\lib\revit\2015\bc\BuildingCoder\BuildingCoder\CmdRoomWallAdjacency.cs(78,33,78,42): warning CS0618: 'Autodesk.Revit.DB.BoundarySegment.Element' is obsolete: 'This property is deprecated in Revit 2016. Use ElementId instead.'
C:\a\lib\revit\2015\bc\BuildingCoder\BuildingCoder\CmdRoomWallAdjacency.cs(79,27,79,34): warning CS0618: 'Autodesk.Revit.DB.BoundarySegment.Curve' is obsolete: 'This property is deprecated in Revit 2016. Use GetCurve() instead.'
C:\a\lib\revit\2015\bc\BuildingCoder\BuildingCoder\CmdCreateSlopedSlab.cs(81,19,81,48): warning CS0618: 'Autodesk.Revit.Creation.ItemFactoryBase.NewLevel(double)' is obsolete: 'This method is deprecated in Revit 2016. Use Level.Create() instead.'
C:\a\lib\revit\2015\bc\BuildingCoder\BuildingCoder\CmdSpaceAdjacency.cs(145,25,145,32): warning CS0618: 'Autodesk.Revit.DB.BoundarySegment.Curve' is obsolete: 'This property is deprecated in Revit 2016. Use GetCurve() instead.'
C:\a\lib\revit\2015\bc\BuildingCoder\BuildingCoder\CmdWallBottomFace.cs(62,38,62,47): warning CS0618: 'Autodesk.Revit.DB.PlanarFace.Normal' is obsolete: 'This property is obsolete in Revit 2016.  Use the FaceNormal property or Face.ComputeNormal() instead.'
C:\a\lib\revit\2015\bc\BuildingCoder\BuildingCoder\CmdWallBottomFace.cs(63,22,63,31): warning CS0618: 'Autodesk.Revit.DB.PlanarFace.Normal' is obsolete: 'This property is obsolete in Revit 2016.  Use the FaceNormal property or Face.ComputeNormal() instead.'
C:\a\lib\revit\2015\bc\BuildingCoder\BuildingCoder\CmdWallDimensions.cs(81,24,81,41): warning CS0618: 'Autodesk.Revit.DB.PlanarFace.Normal' is obsolete: 'This property is obsolete in Revit 2016.  Use the FaceNormal property or Face.ComputeNormal() instead.'
C:\a\lib\revit\2015\bc\BuildingCoder\BuildingCoder\CmdWallProfile.cs(65,41,65,50): warning CS0618: 'Autodesk.Revit.DB.PlanarFace.Normal' is obsolete: 'This property is obsolete in Revit 2016.  Use the FaceNormal property or Face.ComputeNormal() instead.'
C:\a\lib\revit\2015\bc\BuildingCoder\BuildingCoder\CmdWallTopFaces.cs(40,32,40,57): warning CS0618: 'Autodesk.Revit.DB.PlanarFace.Normal' is obsolete: 'This property is obsolete in Revit 2016.  Use the FaceNormal property or Face.ComputeNormal() instead.'
C:\a\lib\revit\2015\bc\BuildingCoder\BuildingCoder\Util.cs(174,26,174,34): warning CS0618: 'Autodesk.Revit.DB.PlanarFace.Normal' is obsolete: 'This property is obsolete in Revit 2016.  Use the FaceNormal property or Face.ComputeNormal() instead.'
C:\a\lib\revit\2015\bc\BuildingCoder\BuildingCoder\Util.cs(179,28,179,36): warning CS0618: 'Autodesk.Revit.DB.PlanarFace.Normal' is obsolete: 'This property is obsolete in Revit 2016.  Use the FaceNormal property or Face.ComputeNormal() instead.'
  BuildingCoder -> C:\a\lib\revit\2015\bc\BuildingCoder\BuildingCoder\bin\Debug\BuildingCoder.dll
========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========
