------ Build started: Project: BuildingCoder, Configuration: Debug Any CPU ------
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdDimensionWallsIterateFaces.cs(66,19): warning CS0618: 'Autodesk.Revit.Creation.Application.NewLine(Autodesk.Revit.DB.XYZ, Autodesk.Revit.DB.XYZ, bool)' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() or Line.CreateUnbound() instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdDimensionWallsIterateFaces.cs(71,9): warning CS0618: 'Autodesk.Revit.Creation.ItemFactoryBase.NewSketchPlane(Autodesk.Revit.DB.Plane)' is obsolete: 'This method is obsolete in Revit 2014. Use SketchPlane.Create() instead. To create a reference relationship between the sketch plane and geometry, use the overload with a Reference input.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdDimensionWallsIterateFaces.cs(78,14): warning CS0618: 'Autodesk.Revit.Creation.Application.NewLine(Autodesk.Revit.DB.XYZ, Autodesk.Revit.DB.XYZ, bool)' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() or Line.CreateUnbound() instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdDimensionWallsIterateFaces.cs(83,9): warning CS0618: 'Autodesk.Revit.Creation.ItemFactoryBase.NewSketchPlane(Autodesk.Revit.DB.Plane)' is obsolete: 'This method is obsolete in Revit 2014. Use SketchPlane.Create() instead. To create a reference relationship between the sketch plane and geometry, use the overload with a Reference input.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdDimensionWallsIterateFaces.cs(96,14): warning CS0618: 'Autodesk.Revit.Creation.Application.NewLine(Autodesk.Revit.DB.XYZ, Autodesk.Revit.DB.XYZ, bool)' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() or Line.CreateUnbound() instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdDimensionWallsIterateFaces.cs(107,7): warning CS0618: 'Autodesk.Revit.DB.Dimension.Label' is obsolete: 'This property is obsolete in Autodesk Revit 2014.  Please use FamilyLabel instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdDimensionWallsIterateFaces.cs(163,19): warning CS0618: 'Autodesk.Revit.Creation.Application.NewLineBound(Autodesk.Revit.DB.XYZ, Autodesk.Revit.DB.XYZ)' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdSlopedWall.cs(48,20): warning CS0618: 'Autodesk.Revit.Creation.Application.NewLineBound(Autodesk.Revit.DB.XYZ, Autodesk.Revit.DB.XYZ)' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdSlopedWall.cs(54,20): warning CS0618: 'Autodesk.Revit.Creation.Application.NewLineBound(Autodesk.Revit.DB.XYZ, Autodesk.Revit.DB.XYZ)' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdSlopedWall.cs(60,20): warning CS0618: 'Autodesk.Revit.Creation.Application.NewLineBound(Autodesk.Revit.DB.XYZ, Autodesk.Revit.DB.XYZ)' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdSlopedWall.cs(66,20): warning CS0618: 'Autodesk.Revit.Creation.Application.NewLineBound(Autodesk.Revit.DB.XYZ, Autodesk.Revit.DB.XYZ)' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdSlopedWall.cs(171,14): warning CS0618: 'Autodesk.Revit.Creation.Application.NewLine(Autodesk.Revit.DB.XYZ, Autodesk.Revit.DB.XYZ, bool)' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() or Line.CreateUnbound() instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdSlopedWall.cs(189,14): warning CS0618: 'Autodesk.Revit.Creation.ItemFactoryBase.NewSketchPlane(Autodesk.Revit.DB.Plane)' is obsolete: 'This method is obsolete in Revit 2014. Use SketchPlane.Create() instead. To create a reference relationship between the sketch plane and geometry, use the overload with a Reference input.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdNewWallLayer.cs(84,37): warning CS0618: 'Autodesk.Revit.DB.Document.WallTypes' is obsolete: 'This method is obsolete in Revit 2014. Use FilteredElementCollector with an appropriate class filter instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdNewDimensionLabel.cs(54,51): warning CS0618: 'Autodesk.Revit.DB.SketchPlane.Plane' is obsolete: 'This method is obsolete in Revit 2014. Use SketchPlane.GetPlane() instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdNewDimensionLabel.cs(83,19): warning CS0618: 'Autodesk.Revit.Creation.ItemFactoryBase.NewSketchPlane(Autodesk.Revit.DB.Plane)' is obsolete: 'This method is obsolete in Revit 2014. Use SketchPlane.Create() instead. To create a reference relationship between the sketch plane and geometry, use the overload with a Reference input.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdNewDimensionLabel.cs(92,19): warning CS0618: 'Autodesk.Revit.Creation.Application.NewLine(Autodesk.Revit.DB.XYZ, Autodesk.Revit.DB.XYZ, bool)' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() or Line.CreateUnbound() instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdNewDimensionLabel.cs(106,14): warning CS0618: 'Autodesk.Revit.Creation.Application.NewLine(Autodesk.Revit.DB.XYZ, Autodesk.Revit.DB.XYZ, bool)' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() or Line.CreateUnbound() instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdNewDimensionLabel.cs(116,14): warning CS0618: 'Autodesk.Revit.Creation.Application.NewLine(Autodesk.Revit.DB.XYZ, Autodesk.Revit.DB.XYZ, bool)' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() or Line.CreateUnbound() instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdNewDimensionLabel.cs(128,7): warning CS0618: 'Autodesk.Revit.DB.Dimension.Label' is obsolete: 'This property is obsolete in Autodesk Revit 2014.  Please use FamilyLabel instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdEditFloor.cs(247,27): warning CS0618: 'Autodesk.Revit.Creation.Application.NewLineBound(Autodesk.Revit.DB.XYZ, Autodesk.Revit.DB.XYZ)' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdEditFloor.cs(251,62): warning CS0618: 'Autodesk.Revit.DB.Element.Level' is obsolete: 'This property is obsolete in Revit 2014. Call Element.LevelId instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdCopyWallType.cs(53,31): warning CS0618: 'Autodesk.Revit.DB.Document.WallTypes' is obsolete: 'This method is obsolete in Revit 2014. Use FilteredElementCollector with an appropriate class filter instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdCopyWallType.cs(81,31): warning CS0618: 'Autodesk.Revit.DB.Document.WallTypes' is obsolete: 'This method is obsolete in Revit 2014. Use FilteredElementCollector with an appropriate class filter instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdUnrotateNorth.cs(56,15): warning CS0618: 'Autodesk.Revit.DB.Curve.get_EndPoint(int)' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdUnrotateNorth.cs(117,28): warning CS0618: 'Autodesk.Revit.DB.Transform.get_Rotation(Autodesk.Revit.DB.XYZ, Autodesk.Revit.DB.XYZ, double)' is obsolete: 'This property is obsolete in Revit 2014. Use Transform.CreateRotationAtPoint() instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdUnrotateNorth.cs(120,28): warning CS0618: 'Autodesk.Revit.DB.Transform.get_Translation(Autodesk.Revit.DB.XYZ)' is obsolete: 'This property is obsolete in Revit 2014. Use Transform.CreateTranslation() instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdSteelStairBeams.cs(73,19): warning CS0618: 'Autodesk.Revit.Creation.Application.NewLineBound(Autodesk.Revit.DB.XYZ, Autodesk.Revit.DB.XYZ)' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdPlanTopology.cs(47,20): warning CS0618: 'Autodesk.Revit.Creation.Application.NewLine(Autodesk.Revit.DB.XYZ, Autodesk.Revit.DB.XYZ, bool)' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() or Line.CreateUnbound() instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdPlanTopology.cs(48,20): warning CS0618: 'Autodesk.Revit.Creation.Application.NewLine(Autodesk.Revit.DB.XYZ, Autodesk.Revit.DB.XYZ, bool)' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() or Line.CreateUnbound() instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdPlanTopology.cs(49,20): warning CS0618: 'Autodesk.Revit.Creation.Application.NewLine(Autodesk.Revit.DB.XYZ, Autodesk.Revit.DB.XYZ, bool)' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() or Line.CreateUnbound() instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdPlanTopology.cs(50,20): warning CS0618: 'Autodesk.Revit.Creation.Application.NewLine(Autodesk.Revit.DB.XYZ, Autodesk.Revit.DB.XYZ, bool)' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() or Line.CreateUnbound() instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdPlanTopology.cs(78,21): warning CS0618: 'Autodesk.Revit.Creation.Document.NewRoomTag(Autodesk.Revit.DB.Architecture.Room, Autodesk.Revit.DB.UV, Autodesk.Revit.DB.View)' is obsolete: 'This method is deprecated in Revit 2014.  Use the NewRoomTag(LinkElementId, UV, ElementId) overload instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdDetailCurves.cs(59,23): warning CS0618: 'Autodesk.Revit.Creation.Application.NewLine(Autodesk.Revit.DB.XYZ, Autodesk.Revit.DB.XYZ, bool)' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() or Line.CreateUnbound() instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdDetailCurves.cs(68,21): warning CS0618: 'Autodesk.Revit.Creation.Application.NewArc(Autodesk.Revit.DB.XYZ, Autodesk.Revit.DB.XYZ, Autodesk.Revit.DB.XYZ)' is obsolete: 'This method is obsolete in Release 2014.  Use Arc.Create() instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdNewSweptBlend.cs(45,9): warning CS0618: 'Autodesk.Revit.Creation.ItemFactoryBase.NewSketchPlane(Autodesk.Revit.DB.Plane)' is obsolete: 'This method is obsolete in Revit 2014. Use SketchPlane.Create() instead. To create a reference relationship between the sketch plane and geometry, use the overload with a Reference input.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdNewSweptBlend.cs(81,23): warning CS0618: 'Autodesk.Revit.Creation.Application.NewLineBound(Autodesk.Revit.DB.XYZ, Autodesk.Revit.DB.XYZ)' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdNewSweptBlend.cs(82,23): warning CS0618: 'Autodesk.Revit.Creation.Application.NewLineBound(Autodesk.Revit.DB.XYZ, Autodesk.Revit.DB.XYZ)' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdNewSweptBlend.cs(83,23): warning CS0618: 'Autodesk.Revit.Creation.Application.NewLineBound(Autodesk.Revit.DB.XYZ, Autodesk.Revit.DB.XYZ)' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdNewSweptBlend.cs(96,23): warning CS0618: 'Autodesk.Revit.Creation.Application.NewLineBound(Autodesk.Revit.DB.XYZ, Autodesk.Revit.DB.XYZ)' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdNewSweptBlend.cs(97,23): warning CS0618: 'Autodesk.Revit.Creation.Application.NewLineBound(Autodesk.Revit.DB.XYZ, Autodesk.Revit.DB.XYZ)' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdNewSweptBlend.cs(98,23): warning CS0618: 'Autodesk.Revit.Creation.Application.NewLineBound(Autodesk.Revit.DB.XYZ, Autodesk.Revit.DB.XYZ)' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdNewSweptBlend.cs(109,21): warning CS0618: 'Autodesk.Revit.Creation.Application.NewLineBound(Autodesk.Revit.DB.XYZ, Autodesk.Revit.DB.XYZ)' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdNewBlend.cs(47,18): warning CS0618: 'Autodesk.Revit.Creation.Application.NewArc(Autodesk.Revit.DB.XYZ, double, double, double, Autodesk.Revit.DB.XYZ, Autodesk.Revit.DB.XYZ)' is obsolete: 'This method is obsolete in Release 2014.  Use Arc.Create() instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdNewBlend.cs(50,18): warning CS0618: 'Autodesk.Revit.Creation.Application.NewArc(Autodesk.Revit.DB.XYZ, double, double, double, Autodesk.Revit.DB.XYZ, Autodesk.Revit.DB.XYZ)' is obsolete: 'This method is obsolete in Release 2014.  Use Arc.Create() instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdNewBlend.cs(70,20): warning CS0618: 'Autodesk.Revit.Creation.Application.NewArc(Autodesk.Revit.DB.XYZ, double, double, double, Autodesk.Revit.DB.XYZ, Autodesk.Revit.DB.XYZ)' is obsolete: 'This method is obsolete in Release 2014.  Use Arc.Create() instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdNewBlend.cs(73,20): warning CS0618: 'Autodesk.Revit.Creation.Application.NewArc(Autodesk.Revit.DB.XYZ, double, double, double, Autodesk.Revit.DB.XYZ, Autodesk.Revit.DB.XYZ)' is obsolete: 'This method is obsolete in Release 2014.  Use Arc.Create() instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdNewBlend.cs(92,30): warning CS0618: 'Autodesk.Revit.Creation.Application.NewLineBound(Autodesk.Revit.DB.XYZ, Autodesk.Revit.DB.XYZ)' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdNewBlend.cs(100,28): warning CS0618: 'Autodesk.Revit.Creation.ItemFactoryBase.NewSketchPlane(Autodesk.Revit.DB.Plane)' is obsolete: 'This method is obsolete in Revit 2014. Use SketchPlane.Create() instead. To create a reference relationship between the sketch plane and geometry, use the overload with a Reference input.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\Creator.cs(151,33): warning CS0618: 'Autodesk.Revit.Creation.ItemFactoryBase.NewSketchPlane(Autodesk.Revit.DB.Plane)' is obsolete: 'This method is obsolete in Revit 2014. Use SketchPlane.Create() instead. To create a reference relationship between the sketch plane and geometry, use the overload with a Reference input.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\Creator.cs(154,9): warning CS0618: 'Autodesk.Revit.Creation.Application.NewLine(Autodesk.Revit.DB.XYZ, Autodesk.Revit.DB.XYZ, bool)' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() or Line.CreateUnbound() instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\Creator.cs(161,15): warning CS0618: 'Autodesk.Revit.DB.Curve.get_EndPoint(int)' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\Creator.cs(162,15): warning CS0618: 'Autodesk.Revit.DB.Curve.get_EndPoint(int)' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\Creator.cs(179,14): warning CS0618: 'Autodesk.Revit.Creation.ItemFactoryBase.NewSketchPlane(Autodesk.Revit.DB.Plane)' is obsolete: 'This method is obsolete in Revit 2014. Use SketchPlane.Create() instead. To create a reference relationship between the sketch plane and geometry, use the overload with a Reference input.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\Creator.cs(189,19): warning CS0618: 'Autodesk.Revit.Creation.Application.NewLine(Autodesk.Revit.DB.XYZ, Autodesk.Revit.DB.XYZ, bool)' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() or Line.CreateUnbound() instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\Creator.cs(208,15): warning CS0618: 'Autodesk.Revit.DB.Curve.get_EndPoint(int)' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\Creator.cs(227,14): warning CS0618: 'Autodesk.Revit.Creation.ItemFactoryBase.NewSketchPlane(Autodesk.Revit.DB.Plane)' is obsolete: 'This method is obsolete in Revit 2014. Use SketchPlane.Create() instead. To create a reference relationship between the sketch plane and geometry, use the overload with a Reference input.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdAnalyticalModelGeom.cs(97,15): warning CS0618: 'Autodesk.Revit.DB.Curve.get_Transformed(Autodesk.Revit.DB.Transform)' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.CreateTransformed() instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdAnalyticalModelGeom.cs(50,9): warning CS0618: 'Autodesk.Revit.DB.Transform.get_Translation(Autodesk.Revit.DB.XYZ)' is obsolete: 'This property is obsolete in Revit 2014. Use Transform.CreateTranslation() instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\Util.cs(208,24): warning CS0618: 'Autodesk.Revit.DB.Curve.get_EndPoint(int)' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\Util.cs(209,9): warning CS0618: 'Autodesk.Revit.DB.Curve.get_EndPoint(int)' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\Util.cs(217,15): warning CS0618: 'Autodesk.Revit.DB.Curve.get_EndPoint(int)' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\Util.cs(218,15): warning CS0618: 'Autodesk.Revit.DB.Curve.get_EndPoint(int)' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\Util.cs(445,15): warning CS0618: 'Autodesk.Revit.DB.Curve.get_EndPoint(int)' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\Util.cs(446,15): warning CS0618: 'Autodesk.Revit.DB.Curve.get_EndPoint(int)' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdWallProfile.cs(141,13): warning CS0618: 'Autodesk.Revit.DB.Curve.get_EndPoint(int)' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdWallProfile.cs(142,13): warning CS0618: 'Autodesk.Revit.DB.Curve.get_EndPoint(int)' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdWallLayers.cs(71,19): warning CS0618: 'Autodesk.Revit.DB.Curve.get_EndPoint(int)' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdWallLayers.cs(72,17): warning CS0618: 'Autodesk.Revit.DB.Curve.get_EndPoint(int)' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdRotatedBeamLocation.cs(60,17): warning CS0618: 'Autodesk.Revit.DB.Curve.get_EndPoint(int)' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdRotatedBeamLocation.cs(61,17): warning CS0618: 'Autodesk.Revit.DB.Curve.get_EndPoint(int)' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdPickPoint3d.cs(60,28): warning CS0618: 'Autodesk.Revit.Creation.ItemFactoryBase.NewSketchPlane(Autodesk.Revit.DB.Plane)' is obsolete: 'This method is obsolete in Revit 2014. Use SketchPlane.Create() instead. To create a reference relationship between the sketch plane and geometry, use the overload with a Reference input.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdCreateGableWall.cs(70,22): warning CS0618: 'Autodesk.Revit.Creation.Application.NewLineBound(Autodesk.Revit.DB.XYZ, Autodesk.Revit.DB.XYZ)' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdPressKeys.cs(214,25): warning CS0618: 'Autodesk.Revit.Creation.Application.NewLineBound(Autodesk.Revit.DB.XYZ, Autodesk.Revit.DB.XYZ)' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdNewRailing.cs(99,19): warning CS0618: 'Autodesk.Revit.Creation.Application.NewLineBound(Autodesk.Revit.DB.XYZ, Autodesk.Revit.DB.XYZ)' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdEllipticalArc.cs(39,19): warning CS0618: 'Autodesk.Revit.Creation.Application.NewEllipse(Autodesk.Revit.DB.XYZ, double, double, Autodesk.Revit.DB.XYZ, Autodesk.Revit.DB.XYZ, double, double)' is obsolete: 'This method is obsolete in Release 2014.  Use Ellipse.Create() instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdEllipticalArc.cs(52,19): warning CS0618: 'Autodesk.Revit.Creation.Application.NewLineUnbound(Autodesk.Revit.DB.XYZ, Autodesk.Revit.DB.XYZ)' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateUnbound() instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdCurtainWallGeom.cs(113,17): warning CS0618: 'Autodesk.Revit.DB.Curve.get_EndPoint(int)' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdCurtainWallGeom.cs(114,17): warning CS0618: 'Autodesk.Revit.DB.Curve.get_EndPoint(int)' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdCurtainWallGeom.cs(117,24): warning CS0618: 'Autodesk.Revit.DB.Transform.get_Translation(Autodesk.Revit.DB.XYZ)' is obsolete: 'This property is obsolete in Revit 2014. Use Transform.CreateTranslation() instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdCurtainWallGeom.cs(119,17): warning CS0618: 'Autodesk.Revit.DB.Curve.get_Transformed(Autodesk.Revit.DB.Transform)' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.CreateTransformed() instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdCurtainWallGeom.cs(135,21): warning CS0618: 'Autodesk.Revit.DB.Curve.get_Transformed(Autodesk.Revit.DB.Transform)' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.CreateTransformed() instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdWallTopFaces.cs(281,23): warning CS0618: 'Autodesk.Revit.DB.Curve.get_Transformed(Autodesk.Revit.DB.Transform)' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.CreateTransformed() instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdWallTopFaces.cs(103,9): warning CS0618: 'Autodesk.Revit.DB.Transform.get_Translation(Autodesk.Revit.DB.XYZ)' is obsolete: 'This property is obsolete in Revit 2014. Use Transform.CreateTranslation() instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdNewBeamTypeInstance.cs(146,21): warning CS0618: 'Autodesk.Revit.Creation.Application.NewLineBound(Autodesk.Revit.DB.XYZ, Autodesk.Revit.DB.XYZ)' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdSetTagType.cs(168,19): warning CS0618: 'Autodesk.Revit.Creation.Application.NewLineBound(Autodesk.Revit.DB.XYZ, Autodesk.Revit.DB.XYZ)' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdWallFooting.cs(55,20): warning CS0618: 'Autodesk.Revit.DB.Document.Delete(Autodesk.Revit.DB.Element)' is obsolete: 'This method is obsolete in Revit 2014. Use Delete(ElementId) instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdSheetSize.cs(78,15): warning CS0618: 'Autodesk.Revit.DB.Document.TitleBlocks' is obsolete: 'This method is obsolete in Revit 2014. Use FilteredElementCollector with a FamilySymbol class filter and an appropriate category filter instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdSheetSize.cs(87,35): warning CS0618: 'Autodesk.Revit.DB.Document.TitleBlocks' is obsolete: 'This method is obsolete in Revit 2014. Use FilteredElementCollector with a FamilySymbol class filter and an appropriate category filter instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdLandXml.cs(95,7): error CS0246: The type or namespace name 'TopographySurface' could not be found (are you missing a using directive or an assembly reference?)
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdLandXml.cs(96,11): warning CS0618: 'Autodesk.Revit.Creation.Document.NewTopographySurface(System.Collections.Generic.IList<Autodesk.Revit.DB.XYZ>)' is obsolete: 'This method is obsolete in Revit 2014. Use TopographySurface.Create() instead'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdDimensionWallsFindRefs.cs(201,29): warning CS0618: 'Autodesk.Revit.DB.Curve.get_EndPoint(int)' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdDimensionWallsFindRefs.cs(202,29): warning CS0618: 'Autodesk.Revit.DB.Curve.get_EndPoint(int)' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdDimensionWallsFindRefs.cs(243,11): warning CS0618: 'Autodesk.Revit.DB.Document.FindReferencesWithContextByDirection(Autodesk.Revit.DB.XYZ, Autodesk.Revit.DB.XYZ, Autodesk.Revit.DB.View3D)' is obsolete: 'This method is deprecated in Revit 2014.  Use the ReferenceIntersector class instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdDimensionWallsFindRefs.cs(297,35): warning CS0618: 'Autodesk.Revit.DB.Curve.get_EndPoint(int)' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdDimensionWallsFindRefs.cs(298,35): warning CS0618: 'Autodesk.Revit.DB.Curve.get_EndPoint(int)' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdWallProfileArea.cs(202,13): warning CS0618: 'Autodesk.Revit.DB.Transform.get_Rotation(Autodesk.Revit.DB.XYZ, Autodesk.Revit.DB.XYZ, double)' is obsolete: 'This property is obsolete in Revit 2014. Use Transform.CreateRotationAtPoint() instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdFilledRegionCoords.cs(43,26): warning CS0618: 'Autodesk.Revit.DB.Curve.get_EndPoint(int)' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdAzimuth.cs(56,17): warning CS0618: 'Autodesk.Revit.DB.Curve.get_EndPoint(int)' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdAzimuth.cs(57,17): warning CS0618: 'Autodesk.Revit.DB.Curve.get_EndPoint(int)' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdNewLineLoad.cs(57,29): warning CS0618: 'Autodesk.Revit.Creation.ItemFactoryBase.NewSketchPlane(Autodesk.Revit.DB.Plane)' is obsolete: 'This method is obsolete in Revit 2014. Use SketchPlane.Create() instead. To create a reference relationship between the sketch plane and geometry, use the overload with a Reference input.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdGetSketchElements.cs(54,36): warning CS0618: 'Autodesk.Revit.DB.Document.Delete(Autodesk.Revit.DB.Element)' is obsolete: 'This method is obsolete in Revit 2014. Use Delete(ElementId) instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\ParameterUnitConverter.cs(43,35): error CS1061: 'Autodesk.Revit.DB.Document' does not contain a definition for 'ProjectUnit' and no extension method 'ProjectUnit' accepting a first argument of type 'Autodesk.Revit.DB.Document' could be found (are you missing a using directive or an assembly reference?)
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\ParameterUnitConverter.cs(46,32): error CS1061: 'Autodesk.Revit.DB.FormatOptions' does not contain a definition for 'Units' and no extension method 'Units' accepting a first argument of type 'Autodesk.Revit.DB.FormatOptions' could be found (are you missing a using directive or an assembly reference?)
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdListWalls.cs(54,17): warning CS0618: 'Autodesk.Revit.DB.Curve.get_EndPoint(int)' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdListWalls.cs(55,17): warning CS0618: 'Autodesk.Revit.DB.Curve.get_EndPoint(int)' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdRoomWallAdjacency.cs(101,35): warning CS0618: 'Autodesk.Revit.DB.Element.Level' is obsolete: 'This property is obsolete in Revit 2014. Call Element.LevelId instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdCollectorPerformance.cs(717,15): warning CS0618: 'Autodesk.Revit.DB.Element.Level' is obsolete: 'This property is obsolete in Revit 2014. Call Element.LevelId instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdCollectorPerformance.cs(754,13): warning CS0618: 'Autodesk.Revit.DB.Element.Level' is obsolete: 'This property is obsolete in Revit 2014. Call Element.LevelId instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdCollectorPerformance.cs(764,15): warning CS0618: 'Autodesk.Revit.DB.Element.Level' is obsolete: 'This property is obsolete in Revit 2014. Call Element.LevelId instead.'
C:\a\lib\revit\2014\bc\BuildingCoder\BuildingCoder\CmdCollectorPerformance.cs(771,14): warning CS0618: 'Autodesk.Revit.DB.Element.Level' is obsolete: 'This property is obsolete in Revit 2014. Call Element.LevelId instead.'

Compile complete -- 3 errors, 108 warnings
C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(1578,5): warning MSB3270: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "RevitAPI", "AMD64". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.
C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(1578,5): warning MSB3270: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "RevitAPIUI", "AMD64". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.
C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(1578,5): warning MSB3270: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "UIFrameworkServices", "AMD64". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.
========== Build: 0 succeeded or up-to-date, 1 failed, 0 skipped ==========
