Build started.
Warning MSB3270: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll", "AMD64". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.
Warning MSB3270: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "..\..\..\..\..\..\RevitAPI.dll", "AMD64". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.
Warning MSB3270: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "..\..\..\..\..\..\RevitAPIUI.dll", "AMD64". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.
Warning MSB3270: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "System.Data", "AMD64". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.
Compiling MacroCSharpSamples
C:\Users\brandan\AppData\Local\temp\{2ABD6A90-A427-47C8-9DC0-4335C25F9398}\Revit\DocHookups13268\1433213760\MacroCSharpSamples\Source\MacroCSharpSamples\CreateBeamsColumnsBraces\CreateBeamsColumnsBraces.cs(274,53) : Error CS1061: 'Autodesk.Revit.DB.Family' does not contain a definition for 'Symbols' and no extension method 'Symbols' accepting a first argument of type 'Autodesk.Revit.DB.Family' could be found (are you missing a using directive or an assembly reference?)
C:\Users\brandan\AppData\Local\temp\{2ABD6A90-A427-47C8-9DC0-4335C25F9398}\Revit\DocHookups13268\1433213760\MacroCSharpSamples\Source\MacroCSharpSamples\CreateBeamsColumnsBraces\CreateBeamsColumnsBraces.cs(385,63) : Error CS1061: 'Autodesk.Revit.Creation.Application' does not contain a definition for 'NewLineBound' and no extension method 'NewLineBound' accepting a first argument of type 'Autodesk.Revit.Creation.Application' could be found (are you missing a using directive or an assembly reference?)
C:\Users\brandan\AppData\Local\temp\{2ABD6A90-A427-47C8-9DC0-4335C25F9398}\Revit\DocHookups13268\1433213760\MacroCSharpSamples\Source\MacroCSharpSamples\CreateBeamsColumnsBraces\CreateBeamsColumnsBraces.cs(430,63) : Error CS1061: 'Autodesk.Revit.Creation.Application' does not contain a definition for 'NewLineBound' and no extension method 'NewLineBound' accepting a first argument of type 'Autodesk.Revit.Creation.Application' could be found (are you missing a using directive or an assembly reference?)
C:\Users\brandan\AppData\Local\temp\{2ABD6A90-A427-47C8-9DC0-4335C25F9398}\Revit\DocHookups13268\1433213760\MacroCSharpSamples\Source\MacroCSharpSamples\CreateBeamsColumnsBraces\CreateBeamsColumnsBraces.cs(444,63) : Error CS1061: 'Autodesk.Revit.Creation.Application' does not contain a definition for 'NewLineBound' and no extension method 'NewLineBound' accepting a first argument of type 'Autodesk.Revit.Creation.Application' could be found (are you missing a using directive or an assembly reference?)
C:\Users\brandan\AppData\Local\temp\{2ABD6A90-A427-47C8-9DC0-4335C25F9398}\Revit\DocHookups13268\1433213760\MacroCSharpSamples\Source\MacroCSharpSamples\DeleteObject\DeleteObject.cs(63,53) : Error CS1061: 'Autodesk.Revit.UI.Selection.Selection' does not contain a definition for 'Elements' and no extension method 'Elements' accepting a first argument of type 'Autodesk.Revit.UI.Selection.Selection' could be found (are you missing a using directive or an assembly reference?)
C:\Users\brandan\AppData\Local\temp\{2ABD6A90-A427-47C8-9DC0-4335C25F9398}\Revit\DocHookups13268\1433213760\MacroCSharpSamples\Source\MacroCSharpSamples\DeleteObject\DeleteObject.cs(82,21) : Error CS1502: The best overloaded method match for 'Autodesk.Revit.DB.Document.Delete(System.Collections.Generic.ICollection<Autodesk.Revit.DB.ElementId>)' has some invalid arguments
C:\Users\brandan\AppData\Local\temp\{2ABD6A90-A427-47C8-9DC0-4335C25F9398}\Revit\DocHookups13268\1433213760\MacroCSharpSamples\Source\MacroCSharpSamples\DeleteObject\DeleteObject.cs(82,43) : Error CS1503: Argument 1: cannot convert from 'Autodesk.Revit.DB.Element' to 'System.Collections.Generic.ICollection<Autodesk.Revit.DB.ElementId>'
C:\Users\brandan\AppData\Local\temp\{2ABD6A90-A427-47C8-9DC0-4335C25F9398}\Revit\DocHookups13268\1433213760\MacroCSharpSamples\Source\MacroCSharpSamples\DeleteObject\DeleteObject.cs(93,37) : Error CS1061: 'Autodesk.Revit.UI.Selection.Selection' does not contain a definition for 'Elements' and no extension method 'Elements' accepting a first argument of type 'Autodesk.Revit.UI.Selection.Selection' could be found (are you missing a using directive or an assembly reference?)
C:\Users\brandan\AppData\Local\temp\{2ABD6A90-A427-47C8-9DC0-4335C25F9398}\Revit\DocHookups13268\1433213760\MacroCSharpSamples\Source\MacroCSharpSamples\GridCreation\CreateOrthogonalGridsData.cs(325,74) : Error CS1061: 'Autodesk.Revit.Creation.Application' does not contain a definition for 'NewLineBound' and no extension method 'NewLineBound' accepting a first argument of type 'Autodesk.Revit.Creation.Application' could be found (are you missing a using directive or an assembly reference?)
C:\Users\brandan\AppData\Local\temp\{2ABD6A90-A427-47C8-9DC0-4335C25F9398}\Revit\DocHookups13268\1433213760\MacroCSharpSamples\Source\MacroCSharpSamples\GridCreation\CreateOrthogonalGridsData.cs(329,74) : Error CS1061: 'Autodesk.Revit.Creation.Application' does not contain a definition for 'NewLineBound' and no extension method 'NewLineBound' accepting a first argument of type 'Autodesk.Revit.Creation.Application' could be found (are you missing a using directive or an assembly reference?)
C:\Users\brandan\AppData\Local\temp\{2ABD6A90-A427-47C8-9DC0-4335C25F9398}\Revit\DocHookups13268\1433213760\MacroCSharpSamples\Source\MacroCSharpSamples\GridCreation\CreateOrthogonalGridsData.cs(344,28) : Warning CS0618: 'Autodesk.Revit.Creation.Document.NewGrid(Autodesk.Revit.DB.Line)' is obsolete: 'This method is deprecated in Revit 2016. Use Grid.Create() instead.'
C:\Users\brandan\AppData\Local\temp\{2ABD6A90-A427-47C8-9DC0-4335C25F9398}\Revit\DocHookups13268\1433213760\MacroCSharpSamples\Source\MacroCSharpSamples\GridCreation\CreateOrthogonalGridsData.cs(406,74) : Error CS1061: 'Autodesk.Revit.Creation.Application' does not contain a definition for 'NewLineBound' and no extension method 'NewLineBound' accepting a first argument of type 'Autodesk.Revit.Creation.Application' could be found (are you missing a using directive or an assembly reference?)
C:\Users\brandan\AppData\Local\temp\{2ABD6A90-A427-47C8-9DC0-4335C25F9398}\Revit\DocHookups13268\1433213760\MacroCSharpSamples\Source\MacroCSharpSamples\GridCreation\CreateOrthogonalGridsData.cs(410,74) : Error CS1061: 'Autodesk.Revit.Creation.Application' does not contain a definition for 'NewLineBound' and no extension method 'NewLineBound' accepting a first argument of type 'Autodesk.Revit.Creation.Application' could be found (are you missing a using directive or an assembly reference?)
C:\Users\brandan\AppData\Local\temp\{2ABD6A90-A427-47C8-9DC0-4335C25F9398}\Revit\DocHookups13268\1433213760\MacroCSharpSamples\Source\MacroCSharpSamples\GridCreation\CreateOrthogonalGridsData.cs(425,28) : Warning CS0618: 'Autodesk.Revit.Creation.Document.NewGrid(Autodesk.Revit.DB.Line)' is obsolete: 'This method is deprecated in Revit 2016. Use Grid.Create() instead.'
C:\Users\brandan\AppData\Local\temp\{2ABD6A90-A427-47C8-9DC0-4335C25F9398}\Revit\DocHookups13268\1433213760\MacroCSharpSamples\Source\MacroCSharpSamples\GridCreation\CreateRadialAndArcGridsData.cs(404,66) : Error CS1061: 'Autodesk.Revit.Creation.Application' does not contain a definition for 'NewLineBound' and no extension method 'NewLineBound' accepting a first argument of type 'Autodesk.Revit.Creation.Application' could be found (are you missing a using directive or an assembly reference?)
C:\Users\brandan\AppData\Local\temp\{2ABD6A90-A427-47C8-9DC0-4335C25F9398}\Revit\DocHookups13268\1433213760\MacroCSharpSamples\Source\MacroCSharpSamples\GridCreation\CreateRadialAndArcGridsData.cs(408,66) : Error CS1061: 'Autodesk.Revit.Creation.Application' does not contain a definition for 'NewLineBound' and no extension method 'NewLineBound' accepting a first argument of type 'Autodesk.Revit.Creation.Application' could be found (are you missing a using directive or an assembly reference?)
C:\Users\brandan\AppData\Local\temp\{2ABD6A90-A427-47C8-9DC0-4335C25F9398}\Revit\DocHookups13268\1433213760\MacroCSharpSamples\Source\MacroCSharpSamples\GridCreation\CreateRadialAndArcGridsData.cs(412,33) : Warning CS0618: 'Autodesk.Revit.Creation.Document.NewGrid(Autodesk.Revit.DB.Line)' is obsolete: 'This method is deprecated in Revit 2016. Use Grid.Create() instead.'
C:\Users\brandan\AppData\Local\temp\{2ABD6A90-A427-47C8-9DC0-4335C25F9398}\Revit\DocHookups13268\1433213760\MacroCSharpSamples\Source\MacroCSharpSamples\GridCreation\CreateRadialAndArcGridsData.cs(584,57) : Error CS1061: 'Autodesk.Revit.Creation.Application' does not contain a definition for 'NewArc' and no extension method 'NewArc' accepting a first argument of type 'Autodesk.Revit.Creation.Application' could be found (are you missing a using directive or an assembly reference?)
C:\Users\brandan\AppData\Local\temp\{2ABD6A90-A427-47C8-9DC0-4335C25F9398}\Revit\DocHookups13268\1433213760\MacroCSharpSamples\Source\MacroCSharpSamples\GridCreation\CreateRadialAndArcGridsData.cs(588,57) : Error CS1061: 'Autodesk.Revit.Creation.Application' does not contain a definition for 'NewArc' and no extension method 'NewArc' accepting a first argument of type 'Autodesk.Revit.Creation.Application' could be found (are you missing a using directive or an assembly reference?)
C:\Users\brandan\AppData\Local\temp\{2ABD6A90-A427-47C8-9DC0-4335C25F9398}\Revit\DocHookups13268\1433213760\MacroCSharpSamples\Source\MacroCSharpSamples\GridCreation\CreateRadialAndArcGridsData.cs(591,20) : Warning CS0618: 'Autodesk.Revit.Creation.Document.NewGrid(Autodesk.Revit.DB.Arc)' is obsolete: 'This method is deprecated in Revit 2016. Use Grid.Create() instead.'
C:\Users\brandan\AppData\Local\temp\{2ABD6A90-A427-47C8-9DC0-4335C25F9398}\Revit\DocHookups13268\1433213760\MacroCSharpSamples\Source\MacroCSharpSamples\GridCreation\CreateWithSeletedCurvesData.cs(267,43) : Error CS1061: 'Autodesk.Revit.Creation.Application' does not contain a definition for 'NewArc' and no extension method 'NewArc' accepting a first argument of type 'Autodesk.Revit.Creation.Application' could be found (are you missing a using directive or an assembly reference?)
C:\Users\brandan\AppData\Local\temp\{2ABD6A90-A427-47C8-9DC0-4335C25F9398}\Revit\DocHookups13268\1433213760\MacroCSharpSamples\Source\MacroCSharpSamples\GridCreation\CreateWithSeletedCurvesData.cs(268,43) : Error CS1061: 'Autodesk.Revit.Creation.Application' does not contain a definition for 'NewArc' and no extension method 'NewArc' accepting a first argument of type 'Autodesk.Revit.Creation.Application' could be found (are you missing a using directive or an assembly reference?)
C:\Users\brandan\AppData\Local\temp\{2ABD6A90-A427-47C8-9DC0-4335C25F9398}\Revit\DocHookups13268\1433213760\MacroCSharpSamples\Source\MacroCSharpSamples\GridCreation\CreateWithSeletedCurvesData.cs(272,43) : Error CS1061: 'Autodesk.Revit.Creation.Application' does not contain a definition for 'NewArc' and no extension method 'NewArc' accepting a first argument of type 'Autodesk.Revit.Creation.Application' could be found (are you missing a using directive or an assembly reference?)
C:\Users\brandan\AppData\Local\temp\{2ABD6A90-A427-47C8-9DC0-4335C25F9398}\Revit\DocHookups13268\1433213760\MacroCSharpSamples\Source\MacroCSharpSamples\GridCreation\CreateWithSeletedCurvesData.cs(273,43) : Error CS1061: 'Autodesk.Revit.Creation.Application' does not contain a definition for 'NewArc' and no extension method 'NewArc' accepting a first argument of type 'Autodesk.Revit.Creation.Application' could be found (are you missing a using directive or an assembly reference?)
C:\Users\brandan\AppData\Local\temp\{2ABD6A90-A427-47C8-9DC0-4335C25F9398}\Revit\DocHookups13268\1433213760\MacroCSharpSamples\Source\MacroCSharpSamples\GridCreation\CreateWithSeletedCurvesData.cs(277,25) : Warning CS0618: 'Autodesk.Revit.Creation.Document.NewGrid(Autodesk.Revit.DB.Arc)' is obsolete: 'This method is deprecated in Revit 2016. Use Grid.Create() instead.'
C:\Users\brandan\AppData\Local\temp\{2ABD6A90-A427-47C8-9DC0-4335C25F9398}\Revit\DocHookups13268\1433213760\MacroCSharpSamples\Source\MacroCSharpSamples\GridCreation\CreateWithSeletedCurvesData.cs(278,25) : Warning CS0618: 'Autodesk.Revit.Creation.Document.NewGrid(Autodesk.Revit.DB.Arc)' is obsolete: 'This method is deprecated in Revit 2016. Use Grid.Create() instead.'
C:\Users\brandan\AppData\Local\temp\{2ABD6A90-A427-47C8-9DC0-4335C25F9398}\Revit\DocHookups13268\1433213760\MacroCSharpSamples\Source\MacroCSharpSamples\GridCreation\CreateWithSeletedCurvesData.cs(307,24) : Warning CS0618: 'Autodesk.Revit.Creation.Document.NewGrid(Autodesk.Revit.DB.Arc)' is obsolete: 'This method is deprecated in Revit 2016. Use Grid.Create() instead.'
C:\Users\brandan\AppData\Local\temp\{2ABD6A90-A427-47C8-9DC0-4335C25F9398}\Revit\DocHookups13268\1433213760\MacroCSharpSamples\Source\MacroCSharpSamples\GridCreation\CreateWithSeletedCurvesData.cs(312,38) : Error CS1061: 'Autodesk.Revit.DB.Arc' does not contain a definition for 'get_EndPoint' and no extension method 'get_EndPoint' accepting a first argument of type 'Autodesk.Revit.DB.Arc' could be found (are you missing a using directive or an assembly reference?)
C:\Users\brandan\AppData\Local\temp\{2ABD6A90-A427-47C8-9DC0-4335C25F9398}\Revit\DocHookups13268\1433213760\MacroCSharpSamples\Source\MacroCSharpSamples\GridCreation\CreateWithSeletedCurvesData.cs(313,36) : Error CS1061: 'Autodesk.Revit.DB.Arc' does not contain a definition for 'get_EndPoint' and no extension method 'get_EndPoint' accepting a first argument of type 'Autodesk.Revit.DB.Arc' could be found (are you missing a using directive or an assembly reference?)
C:\Users\brandan\AppData\Local\temp\{2ABD6A90-A427-47C8-9DC0-4335C25F9398}\Revit\DocHookups13268\1433213760\MacroCSharpSamples\Source\MacroCSharpSamples\GridCreation\CreateWithSeletedCurvesData.cs(317,42) : Error CS1061: 'Autodesk.Revit.DB.Arc' does not contain a definition for 'get_EndParameter' and no extension method 'get_EndParameter' accepting a first argument of type 'Autodesk.Revit.DB.Arc' could be found (are you missing a using directive or an assembly reference?)
C:\Users\brandan\AppData\Local\temp\{2ABD6A90-A427-47C8-9DC0-4335C25F9398}\Revit\DocHookups13268\1433213760\MacroCSharpSamples\Source\MacroCSharpSamples\GridCreation\CreateWithSeletedCurvesData.cs(318,40) : Error CS1061: 'Autodesk.Revit.DB.Arc' does not contain a definition for 'get_EndParameter' and no extension method 'get_EndParameter' accepting a first argument of type 'Autodesk.Revit.DB.Arc' could be found (are you missing a using directive or an assembly reference?)
C:\Users\brandan\AppData\Local\temp\{2ABD6A90-A427-47C8-9DC0-4335C25F9398}\Revit\DocHookups13268\1433213760\MacroCSharpSamples\Source\MacroCSharpSamples\GridCreation\CreateWithSeletedCurvesData.cs(346,50) : Error CS1061: 'Autodesk.Revit.Creation.Application' does not contain a definition for 'NewArc' and no extension method 'NewArc' accepting a first argument of type 'Autodesk.Revit.Creation.Application' could be found (are you missing a using directive or an assembly reference?)
C:\Users\brandan\AppData\Local\temp\{2ABD6A90-A427-47C8-9DC0-4335C25F9398}\Revit\DocHookups13268\1433213760\MacroCSharpSamples\Source\MacroCSharpSamples\GridCreation\CreateWithSeletedCurvesData.cs(349,24) : Warning CS0618: 'Autodesk.Revit.Creation.Document.NewGrid(Autodesk.Revit.DB.Arc)' is obsolete: 'This method is deprecated in Revit 2016. Use Grid.Create() instead.'
C:\Users\brandan\AppData\Local\temp\{2ABD6A90-A427-47C8-9DC0-4335C25F9398}\Revit\DocHookups13268\1433213760\MacroCSharpSamples\Source\MacroCSharpSamples\GridCreation\CreateWithSeletedCurvesData.cs(367,24) : Warning CS0618: 'Autodesk.Revit.Creation.Document.NewGrid(Autodesk.Revit.DB.Line)' is obsolete: 'This method is deprecated in Revit 2016. Use Grid.Create() instead.'
C:\Users\brandan\AppData\Local\temp\{2ABD6A90-A427-47C8-9DC0-4335C25F9398}\Revit\DocHookups13268\1433213760\MacroCSharpSamples\Source\MacroCSharpSamples\GridCreation\CreateWithSeletedCurvesData.cs(371,39) : Error CS1061: 'Autodesk.Revit.DB.Line' does not contain a definition for 'get_EndPoint' and no extension method 'get_EndPoint' accepting a first argument of type 'Autodesk.Revit.DB.Line' could be found (are you missing a using directive or an assembly reference?)
C:\Users\brandan\AppData\Local\temp\{2ABD6A90-A427-47C8-9DC0-4335C25F9398}\Revit\DocHookups13268\1433213760\MacroCSharpSamples\Source\MacroCSharpSamples\GridCreation\CreateWithSeletedCurvesData.cs(372,37) : Error CS1061: 'Autodesk.Revit.DB.Line' does not contain a definition for 'get_EndPoint' and no extension method 'get_EndPoint' accepting a first argument of type 'Autodesk.Revit.DB.Line' could be found (are you missing a using directive or an assembly reference?)
C:\Users\brandan\AppData\Local\temp\{2ABD6A90-A427-47C8-9DC0-4335C25F9398}\Revit\DocHookups13268\1433213760\MacroCSharpSamples\Source\MacroCSharpSamples\GridCreation\CreateWithSeletedCurvesData.cs(373,52) : Error CS1061: 'Autodesk.Revit.Creation.Application' does not contain a definition for 'NewLineBound' and no extension method 'NewLineBound' accepting a first argument of type 'Autodesk.Revit.Creation.Application' could be found (are you missing a using directive or an assembly reference?)
C:\Users\brandan\AppData\Local\temp\{2ABD6A90-A427-47C8-9DC0-4335C25F9398}\Revit\DocHookups13268\1433213760\MacroCSharpSamples\Source\MacroCSharpSamples\GridCreation\CreateWithSeletedCurvesData.cs(374,24) : Warning CS0618: 'Autodesk.Revit.Creation.Document.NewGrid(Autodesk.Revit.DB.Line)' is obsolete: 'This method is deprecated in Revit 2016. Use Grid.Create() instead.'
C:\Users\brandan\AppData\Local\temp\{2ABD6A90-A427-47C8-9DC0-4335C25F9398}\Revit\DocHookups13268\1433213760\MacroCSharpSamples\Source\MacroCSharpSamples\GridCreation\GridCreation.cs(147,54) : Error CS1061: 'Autodesk.Revit.UI.Selection.Selection' does not contain a definition for 'Elements' and no extension method 'Elements' accepting a first argument of type 'Autodesk.Revit.UI.Selection.Selection' could be found (are you missing a using directive or an assembly reference?)
C:\Users\brandan\AppData\Local\temp\{2ABD6A90-A427-47C8-9DC0-4335C25F9398}\Revit\DocHookups13268\1433213760\MacroCSharpSamples\Source\MacroCSharpSamples\GridCreation\GridCreation.cs(181,58) : Error CS1061: 'Autodesk.Revit.UI.Selection.Selection' does not contain a definition for 'Elements' and no extension method 'Elements' accepting a first argument of type 'Autodesk.Revit.UI.Selection.Selection' could be found (are you missing a using directive or an assembly reference?)
C:\Users\brandan\AppData\Local\temp\{2ABD6A90-A427-47C8-9DC0-4335C25F9398}\Revit\DocHookups13268\1433213760\MacroCSharpSamples\Source\MacroCSharpSamples\GridCreation\GridCreation.cs(201,13) : Error CS0246: The type or namespace name 'ProjectUnit' could not be found (are you missing a using directive or an assembly reference?)
C:\Users\brandan\AppData\Local\temp\{2ABD6A90-A427-47C8-9DC0-4335C25F9398}\Revit\DocHookups13268\1433213760\MacroCSharpSamples\Source\MacroCSharpSamples\GridCreation\GridCreation.cs(201,48) : Error CS1061: 'Autodesk.Revit.DB.Document' does not contain a definition for 'ProjectUnit' and no extension method 'ProjectUnit' accepting a first argument of type 'Autodesk.Revit.DB.Document' could be found (are you missing a using directive or an assembly reference?)
C:\Users\brandan\AppData\Local\temp\{2ABD6A90-A427-47C8-9DC0-4335C25F9398}\Revit\DocHookups13268\1433213760\MacroCSharpSamples\Source\MacroCSharpSamples\GridCreation\GridCreation.cs(205,37) : Error CS1061: 'Autodesk.Revit.DB.FormatOptions' does not contain a definition for 'Units' and no extension method 'Units' accepting a first argument of type 'Autodesk.Revit.DB.FormatOptions' could be found (are you missing a using directive or an assembly reference?)
C:\Users\brandan\AppData\Local\temp\{2ABD6A90-A427-47C8-9DC0-4335C25F9398}\Revit\DocHookups13268\1433213760\MacroCSharpSamples\Source\MacroCSharpSamples\InplaceFamilyAnalyticalModel3D\InplaceFamilyAnalyticalModel3D.cs(73,17) : Error CS0246: The type or namespace name 'SelElementSet' could not be found (are you missing a using directive or an assembly reference?)
C:\Users\brandan\AppData\Local\temp\{2ABD6A90-A427-47C8-9DC0-4335C25F9398}\Revit\DocHookups13268\1433213760\MacroCSharpSamples\Source\MacroCSharpSamples\InplaceFamilyAnalyticalModel3D\InplaceFamilyAnalyticalModel3D.cs(73,61) : Error CS1061: 'Autodesk.Revit.UI.Selection.Selection' does not contain a definition for 'Elements' and no extension method 'Elements' accepting a first argument of type 'Autodesk.Revit.UI.Selection.Selection' could be found (are you missing a using directive or an assembly reference?)
C:\Users\brandan\AppData\Local\temp\{2ABD6A90-A427-47C8-9DC0-4335C25F9398}\Revit\DocHookups13268\1433213760\MacroCSharpSamples\Source\MacroCSharpSamples\Rooms\RoomsData.cs(221,17) : Error CS1502: The best overloaded method match for 'Autodesk.Revit.Creation.Document.NewRoomTag(Autodesk.Revit.DB.LinkElementId, Autodesk.Revit.DB.UV, Autodesk.Revit.DB.ElementId)' has some invalid arguments
C:\Users\brandan\AppData\Local\temp\{2ABD6A90-A427-47C8-9DC0-4335C25F9398}\Revit\DocHookups13268\1433213760\MacroCSharpSamples\Source\MacroCSharpSamples\Rooms\RoomsData.cs(221,59) : Error CS1503: Argument 1: cannot convert from 'Autodesk.Revit.DB.Architecture.Room' to 'Autodesk.Revit.DB.LinkElementId'
C:\Users\brandan\AppData\Local\temp\{2ABD6A90-A427-47C8-9DC0-4335C25F9398}\Revit\DocHookups13268\1433213760\MacroCSharpSamples\Source\MacroCSharpSamples\RotateFramingObjects\RotateFramingObjects.cs(97,52) : Error CS1061: 'Autodesk.Revit.UI.Selection.Selection' does not contain a definition for 'Elements' and no extension method 'Elements' accepting a first argument of type 'Autodesk.Revit.UI.Selection.Selection' could be found (are you missing a using directive or an assembly reference?)
C:\Users\brandan\AppData\Local\temp\{2ABD6A90-A427-47C8-9DC0-4335C25F9398}\Revit\DocHookups13268\1433213760\MacroCSharpSamples\Source\MacroCSharpSamples\RotateFramingObjects\RotateFramingObjects.cs(154,24) : Error CS1061: 'Autodesk.Revit.UI.Selection.Selection' does not contain a definition for 'Elements' and no extension method 'Elements' accepting a first argument of type 'Autodesk.Revit.UI.Selection.Selection' could be found (are you missing a using directive or an assembly reference?)
C:\Users\brandan\AppData\Local\temp\{2ABD6A90-A427-47C8-9DC0-4335C25F9398}\Revit\DocHookups13268\1433213760\MacroCSharpSamples\Source\MacroCSharpSamples\RotateFramingObjects\RotateFramingObjects.cs(163,24) : Error CS1061: 'Autodesk.Revit.UI.Selection.Selection' does not contain a definition for 'Elements' and no extension method 'Elements' accepting a first argument of type 'Autodesk.Revit.UI.Selection.Selection' could be found (are you missing a using directive or an assembly reference?)
C:\Users\brandan\AppData\Local\temp\{2ABD6A90-A427-47C8-9DC0-4335C25F9398}\Revit\DocHookups13268\1433213760\MacroCSharpSamples\Source\MacroCSharpSamples\RotateFramingObjects\RotateFramingObjects.cs(168,23) : Error CS1061: 'Autodesk.Revit.UI.Selection.Selection' does not contain a definition for 'Elements' and no extension method 'Elements' accepting a first argument of type 'Autodesk.Revit.UI.Selection.Selection' could be found (are you missing a using directive or an assembly reference?)
C:\Users\brandan\AppData\Local\temp\{2ABD6A90-A427-47C8-9DC0-4335C25F9398}\Revit\DocHookups13268\1433213760\MacroCSharpSamples\Source\MacroCSharpSamples\RotateFramingObjects\RotateFramingObjects.cs(206,43) : Error CS1061: 'Autodesk.Revit.UI.Selection.Selection' does not contain a definition for 'Elements' and no extension method 'Elements' accepting a first argument of type 'Autodesk.Revit.UI.Selection.Selection' could be found (are you missing a using directive or an assembly reference?)
C:\Users\brandan\AppData\Local\temp\{2ABD6A90-A427-47C8-9DC0-4335C25F9398}\Revit\DocHookups13268\1433213760\MacroCSharpSamples\Source\MacroCSharpSamples\RotateFramingObjects\RotateFramingObjects.cs(258,91) : Error CS1061: 'Autodesk.Revit.Creation.Application' does not contain a definition for 'NewLineUnbound' and no extension method 'NewLineUnbound' accepting a first argument of type 'Autodesk.Revit.Creation.Application' could be found (are you missing a using directive or an assembly reference?)
C:\Users\brandan\AppData\Local\temp\{2ABD6A90-A427-47C8-9DC0-4335C25F9398}\Revit\DocHookups13268\1433213760\MacroCSharpSamples\Source\MacroCSharpSamples\SlabProperties\Command.cs(304,45) : Error CS1061: 'Autodesk.Revit.UI.Selection.Selection' does not contain a definition for 'Elements' and no extension method 'Elements' accepting a first argument of type 'Autodesk.Revit.UI.Selection.Selection' could be found (are you missing a using directive or an assembly reference?)
C:\Users\brandan\AppData\Local\temp\{2ABD6A90-A427-47C8-9DC0-4335C25F9398}\Revit\DocHookups13268\1433213760\MacroCSharpSamples\Source\MacroCSharpSamples\SlabProperties\Command.cs(339,39) : Error CS1061: 'Autodesk.Revit.DB.Floor' does not contain a definition for 'Level' and no extension method 'Level' accepting a first argument of type 'Autodesk.Revit.DB.Floor' could be found (are you missing a using directive or an assembly reference?)
C:\Users\brandan\AppData\Local\temp\{2ABD6A90-A427-47C8-9DC0-4335C25F9398}\Revit\DocHookups13268\1433213760\MacroCSharpSamples\Source\MacroCSharpSamples\StructuralLayerFunction\Command.cs(95,45) : Error CS1061: 'Autodesk.Revit.UI.Selection.Selection' does not contain a definition for 'Elements' and no extension method 'Elements' accepting a first argument of type 'Autodesk.Revit.UI.Selection.Selection' could be found (are you missing a using directive or an assembly reference?)
Build failed. (00:00:00.9100910)
