------ Rebuild All started: Project: NewRstLab, Configuration: Debug Any CPU ------
Z:\a\lib\revit\2014\adn\src\rst\NewRstLab\RstUtils.cs(340,49): warning CS0618: 'Autodesk.Revit.DB.Curve.get_EndPoint(int)' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'
Z:\a\lib\revit\2014\adn\src\rst\NewRstLab\RstUtils.cs(341,43): warning CS0618: 'Autodesk.Revit.DB.Curve.get_EndPoint(int)' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'
Z:\a\lib\revit\2014\adn\src\rst\NewRstLab\RstUtils.cs(346,48): warning CS0618: 'Autodesk.Revit.DB.Curve.get_EndPoint(int)' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'
Z:\a\lib\revit\2014\adn\src\rst\NewRstLab\RstUtils.cs(347,43): warning CS0618: 'Autodesk.Revit.DB.Curve.get_EndPoint(int)' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'
Z:\a\lib\revit\2014\adn\src\rst\NewRstLab\2_ElementFilter.cs(193,41): warning CS0618: 'Autodesk.Revit.DB.Curve.get_EndPoint(int)' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'
Z:\a\lib\revit\2014\adn\src\rst\NewRstLab\2_ElementFilter.cs(196,43): warning CS0618: 'Autodesk.Revit.DB.Curve.get_EndPoint(int)' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'
Z:\a\lib\revit\2014\adn\src\rst\NewRstLab\2_ElementFilter.cs(207,41): warning CS0618: 'Autodesk.Revit.DB.Curve.get_EndPoint(int)' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'
Z:\a\lib\revit\2014\adn\src\rst\NewRstLab\2_ElementFilter.cs(210,41): warning CS0618: 'Autodesk.Revit.DB.Curve.get_EndPoint(int)' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'
Z:\a\lib\revit\2014\adn\src\rst\NewRstLab\4_Rebar.cs(132,7): warning CS0618: 'Autodesk.Revit.DB.Structure.RebarShapeDefinitionBySegments.AddBendDefaultRadius(int, int, Autodesk.Revit.DB.Structure.RebarShapeBendAngle)' is obsolete: 'This method is obsolete in Autodesk Revit 2014.  Please use the addBendDefaultRadius with parameter turn type RebarShapeVertexTurn::Enum instead.'
Z:\a\lib\revit\2014\adn\src\rst\NewRstLab\4_Rebar.cs(133,7): warning CS0618: 'Autodesk.Revit.DB.Structure.RebarShapeDefinitionBySegments.AddBendDefaultRadius(int, int, Autodesk.Revit.DB.Structure.RebarShapeBendAngle)' is obsolete: 'This method is obsolete in Autodesk Revit 2014.  Please use the addBendDefaultRadius with parameter turn type RebarShapeVertexTurn::Enum instead.'
Z:\a\lib\revit\2014\adn\src\rst\NewRstLab\4_Rebar.cs(134,7): warning CS0618: 'Autodesk.Revit.DB.Structure.RebarShapeDefinitionBySegments.AddBendDefaultRadius(int, int, Autodesk.Revit.DB.Structure.RebarShapeBendAngle)' is obsolete: 'This method is obsolete in Autodesk Revit 2014.  Please use the addBendDefaultRadius with parameter turn type RebarShapeVertexTurn::Enum instead.'
Z:\a\lib\revit\2014\adn\src\rst\NewRstLab\4_Rebar.cs(135,7): warning CS0618: 'Autodesk.Revit.DB.Structure.RebarShapeDefinitionBySegments.AddBendDefaultRadius(int, int, Autodesk.Revit.DB.Structure.RebarShapeBendAngle)' is obsolete: 'This method is obsolete in Autodesk Revit 2014.  Please use the addBendDefaultRadius with parameter turn type RebarShapeVertexTurn::Enum instead.'
Z:\a\lib\revit\2014\adn\src\rst\NewRstLab\GeomUtil.cs(120,29): warning CS0618: 'Autodesk.Revit.DB.Curve.get_EndPoint(int)' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'
Z:\a\lib\revit\2014\adn\src\rst\NewRstLab\GeomUtil.cs(120,52): warning CS0618: 'Autodesk.Revit.DB.Curve.get_EndPoint(int)' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'
Z:\a\lib\revit\2014\adn\src\rst\NewRstLab\GeomUtil.cs(328,29): warning CS0618: 'Autodesk.Revit.DB.Curve.get_EndPoint(int)' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'
Z:\a\lib\revit\2014\adn\src\rst\NewRstLab\GeomUtil.cs(330,32): warning CS0618: 'Autodesk.Revit.DB.Curve.get_EndPoint(int)' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'
Z:\a\lib\revit\2014\adn\src\rst\NewRstLab\GeomUtil.cs(330,56): warning CS0618: 'Autodesk.Revit.DB.Curve.get_EndPoint(int)' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'
Z:\a\lib\revit\2014\adn\src\rst\NewRstLab\GeomUtil.cs(333,29): warning CS0618: 'Autodesk.Revit.DB.Curve.get_EndPoint(int)' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'
Z:\a\lib\revit\2014\adn\src\rst\NewRstLab\GeomUtil.cs(335,32): warning CS0618: 'Autodesk.Revit.DB.Curve.get_EndPoint(int)' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'
Z:\a\lib\revit\2014\adn\src\rst\NewRstLab\GeomUtil.cs(335,56): warning CS0618: 'Autodesk.Revit.DB.Curve.get_EndPoint(int)' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'
Z:\a\lib\revit\2014\adn\src\rst\NewRstLab\GeomUtil.cs(466,23): warning CS0618: 'Autodesk.Revit.DB.Curve.get_EndPoint(int)' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'
Z:\a\lib\revit\2014\adn\src\rst\NewRstLab\GeomUtil.cs(467,21): warning CS0618: 'Autodesk.Revit.DB.Curve.get_EndPoint(int)' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'
Z:\a\lib\revit\2014\adn\src\rst\NewRstLab\GeomUtil.cs(612,24): warning CS0618: 'Autodesk.Revit.DB.Line.get_Bound(Autodesk.Revit.DB.XYZ, Autodesk.Revit.DB.XYZ)' is obsolete: 'This property is obsolete in Release 2014.  Use Line.CreateBound() instead.'
Z:\a\lib\revit\2014\adn\src\rst\NewRstLab\3_AnalyticalModel.cs(237,19): error CS1061: 'Autodesk.Revit.DB.Structure.AnalyticalModel' does not contain a definition for 'CanSetAnalyticalOffset' and no extension method 'CanSetAnalyticalOffset' accepting a first argument of type 'Autodesk.Revit.DB.Structure.AnalyticalModel' could be found (are you missing a using directive or an assembly reference?)

Compile complete -- 1 errors, 23 warnings
c:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(1605,5): warning MSB3270: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "RevitAPI", "AMD64". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.
c:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(1605,5): warning MSB3270: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "RevitAPIUI", "AMD64". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========
