------ Rebuild All started: Project: RoomEditorApp, Configuration: Debug Any CPU ------
C:\a\vs\RoomEditorApp\RoomEditorApp\CmdUpload.cs(100,15): warning CS0618: 'Autodesk.Revit.DB.Curve.get_EndPoint(int)' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'
C:\a\vs\RoomEditorApp\RoomEditorApp\CmdUpload.cs(107,15): warning CS0618: 'Autodesk.Revit.DB.Curve.get_EndPoint(int)' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'
C:\a\vs\RoomEditorApp\RoomEditorApp\CmdUpload.cs(279,19): warning CS0618: 'Autodesk.Revit.DB.Curve.get_EndPoint(int)' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'
C:\a\vs\RoomEditorApp\RoomEditorApp\CmdUpload.cs(280,19): warning CS0618: 'Autodesk.Revit.DB.Curve.get_EndPoint(int)' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'
C:\a\vs\RoomEditorApp\RoomEditorApp\CmdUpload.cs(294,19): warning CS0618: 'Autodesk.Revit.DB.Curve.get_EndPoint(int)' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'
C:\a\vs\RoomEditorApp\RoomEditorApp\CmdUpload.cs(295,19): warning CS0618: 'Autodesk.Revit.DB.Curve.get_EndPoint(int)' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'
C:\a\vs\RoomEditorApp\RoomEditorApp\CmdUpload.cs(337,17): warning CS0618: 'Autodesk.Revit.DB.Curve.get_EndPoint(int)' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'
C:\a\vs\RoomEditorApp\RoomEditorApp\CmdUpload.cs(345,17): warning CS0618: 'Autodesk.Revit.DB.Curve.get_EndPoint(int)' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'
C:\a\vs\RoomEditorApp\RoomEditorApp\CmdUpload.cs(506,25): warning CS0618: 'Autodesk.Revit.DB.Transform.get_Translation(Autodesk.Revit.DB.XYZ)' is obsolete: 'This property is obsolete in Revit 2014. Use Transform.CreateTranslation() instead.'
C:\a\vs\RoomEditorApp\RoomEditorApp\CmdUpload.cs(509,25): warning CS0618: 'Autodesk.Revit.DB.Transform.get_Rotation(Autodesk.Revit.DB.XYZ, Autodesk.Revit.DB.XYZ, double)' is obsolete: 'This property is obsolete in Revit 2014. Use Transform.CreateRotationAtPoint() instead.'
C:\a\vs\RoomEditorApp\RoomEditorApp\CmdUpload.cs(700,21): warning CS0618: 'Autodesk.Revit.DB.Element.Level' is obsolete: 'This property is obsolete in Revit 2014. Call Element.LevelId instead.'
C:\a\vs\RoomEditorApp\RoomEditorApp\DbUpdater.cs(141,25): warning CS0618: 'Autodesk.Revit.Creation.Application.NewLineBound(Autodesk.Revit.DB.XYZ, Autodesk.Revit.DB.XYZ)' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() instead.'
C:\a\vs\RoomEditorApp\RoomEditorApp\DbUpload.cs(71,21): warning CS0618: 'Autodesk.Revit.DB.Element.Level' is obsolete: 'This property is obsolete in Revit 2014. Call Element.LevelId instead.'
C:\a\vs\RoomEditorApp\RoomEditorApp\ContiguousCurveSorter.cs(17,14): warning CS0618: 'Autodesk.Revit.DB.Curve.get_EndPoint(int)' is obsolete: 'This property is obsolete in Revit 2014.  Use Curve.GetEndPoint() instead.'
C:\a\vs\RoomEditorApp\RoomEditorApp\ContiguousCurveSorter.cs(73,16): warning CS0618: 'Autodesk.Revit.Creation.Application.NewLineBound(Autodesk.Revit.DB.XYZ, Autodesk.Revit.DB.XYZ)' is obsolete: 'This method is obsolete in Release 2014.  Use Line.CreateBound() instead.'
C:\a\vs\RoomEditorApp\RoomEditorApp\ContiguousCurveSorter.cs(80,16): warning CS0618: 'Autodesk.Revit.Creation.Application.NewArc(Autodesk.Revit.DB.XYZ, Autodesk.Revit.DB.XYZ, Autodesk.Revit.DB.XYZ)' is obsolete: 'This method is obsolete in Release 2014.  Use Arc.Create() instead.'

Compile complete -- 0 errors, 16 warnings
  RoomEditorApp -> C:\a\vs\RoomEditorApp\RoomEditorApp\bin\Debug\RoomEditorApp.dll
          1 file(s) copied.
          1 file(s) copied.
========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========
